/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "sensor_sync.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SENSOR_SYNC_Trigger_Source, SENSOR_SYNC_Trigger_Source, AUTO)


PB_BIND(SENSOR_SYNC_Counter_Source, SENSOR_SYNC_Counter_Source, AUTO)


PB_BIND(SENSOR_SYNC_TOF_Pulse_Source, SENSOR_SYNC_TOF_Pulse_Source, AUTO)


PB_BIND(SENSOR_SYNC_FSG_Counter_Value, SENSOR_SYNC_FSG_Counter_Value, AUTO)


PB_BIND(SENSOR_SYNC_FSG_Counter_Mode_M, SENSOR_SYNC_FSG_Counter_Mode_M, AUTO)


PB_BIND(SENSOR_SYNC_FSG_Counter_Configuration, SENSOR_SYNC_FSG_Counter_Configuration, AUTO)


PB_BIND(SENSOR_SYNC_FSG_Channel_Configuration, SENSOR_SYNC_FSG_Channel_Configuration, AUTO)


PB_BIND(SENSOR_SYNC_Pulse_Config, SENSOR_SYNC_Pulse_Config, AUTO)


PB_BIND(SENSOR_SYNC_topLevel, SENSOR_SYNC_topLevel, 2)







