#ifndef NU4000_B0_USBC_DEVICE_REG_H
#define NU4000_B0_USBC_DEVICE_REG_H


/* types */
#include "defs.h"

#if !defined(PREFIX_VAL)
#define PREFIX_VAL *
#endif
 
#if !defined(SetGroupBits32) 
#define SetGroupBits32(reg,position,len,value)\
{       \
        UINT32 tmp=reg;\
        tmp&=~(((UINT32)0xFFFFFFFF>>(32-(len)))<<(position));\
        tmp|=((value&((UINT32)0xFFFFFFFF>>(32-(len))))<<(position));\
        reg=tmp;\
}
#endif

#if !defined(GetGroupBits32)
#define GetGroupBits32(reg,position,len) (((reg) & (((UINT32)0xFFFFFFFF>>(32-(len)))<<(position)))>>(position))
#endif


/*****************************************/
/*   USBC_DEVICE (Prototype: USBC_DEVICE)                */
/*****************************************/
#define USBC_DEVICE_BASE 0x0900C700

/* REGISTER: DCFG */

#if defined(_V1) && !defined(DCFG_OFFSET)
#define DCFG_OFFSET 0x0
#endif

#if !defined(USBC_DEVICE_DCFG_OFFSET)
#define USBC_DEVICE_DCFG_OFFSET 0x0
#endif

#if defined(_V1) && !defined(DCFG_REG)
#define DCFG_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DCFG_OFFSET))
#endif

#if defined(_V1) && !defined(DCFG_VAL)
#define DCFG_VAL  PREFIX_VAL(DCFG_REG)
#endif

#define USBC_DEVICE_DCFG_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DCFG_OFFSET))
#define USBC_DEVICE_DCFG_VAL  PREFIX_VAL(USBC_DEVICE_DCFG_REG)

/* FIELDS: */

/* DEVSPD */

#ifndef USBC_DEVICE_DCFG_DEVSPD_POS
#define USBC_DEVICE_DCFG_DEVSPD_POS      0
#endif

#ifndef USBC_DEVICE_DCFG_DEVSPD_LEN
#define USBC_DEVICE_DCFG_DEVSPD_LEN      3
#endif

#if defined(_V1) && !defined(DCFG_DEVSPD_R)
#define DCFG_DEVSPD_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVSPD_POS, USBC_DEVICE_DCFG_DEVSPD_LEN)
#endif

#if defined(_V1) && !defined(DCFG_DEVSPD_W)
#define DCFG_DEVSPD_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVSPD_POS, USBC_DEVICE_DCFG_DEVSPD_LEN,value)
#endif

#define USBC_DEVICE_DCFG_DEVSPD_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVSPD_POS, USBC_DEVICE_DCFG_DEVSPD_LEN)

#define USBC_DEVICE_DCFG_DEVSPD_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVSPD_POS, USBC_DEVICE_DCFG_DEVSPD_LEN,value)


/* DEVADDR */

#ifndef USBC_DEVICE_DCFG_DEVADDR_POS
#define USBC_DEVICE_DCFG_DEVADDR_POS      3
#endif

#ifndef USBC_DEVICE_DCFG_DEVADDR_LEN
#define USBC_DEVICE_DCFG_DEVADDR_LEN      7
#endif

#if defined(_V1) && !defined(DCFG_DEVADDR_R)
#define DCFG_DEVADDR_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVADDR_POS, USBC_DEVICE_DCFG_DEVADDR_LEN)
#endif

#if defined(_V1) && !defined(DCFG_DEVADDR_W)
#define DCFG_DEVADDR_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVADDR_POS, USBC_DEVICE_DCFG_DEVADDR_LEN,value)
#endif

#define USBC_DEVICE_DCFG_DEVADDR_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVADDR_POS, USBC_DEVICE_DCFG_DEVADDR_LEN)

#define USBC_DEVICE_DCFG_DEVADDR_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_DEVADDR_POS, USBC_DEVICE_DCFG_DEVADDR_LEN,value)


/* reserved_10_11 */

#ifndef USBC_DEVICE_DCFG_RESERVED_10_11_POS
#define USBC_DEVICE_DCFG_RESERVED_10_11_POS      10
#endif

#ifndef USBC_DEVICE_DCFG_RESERVED_10_11_LEN
#define USBC_DEVICE_DCFG_RESERVED_10_11_LEN      2
#endif

#if defined(_V1) && !defined(DCFG_RESERVED_10_11_R)
#define DCFG_RESERVED_10_11_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_10_11_POS, USBC_DEVICE_DCFG_RESERVED_10_11_LEN)
#endif

#if defined(_V1) && !defined(DCFG_RESERVED_10_11_W)
#define DCFG_RESERVED_10_11_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_10_11_POS, USBC_DEVICE_DCFG_RESERVED_10_11_LEN,value)
#endif

#define USBC_DEVICE_DCFG_RESERVED_10_11_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_10_11_POS, USBC_DEVICE_DCFG_RESERVED_10_11_LEN)

#define USBC_DEVICE_DCFG_RESERVED_10_11_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_10_11_POS, USBC_DEVICE_DCFG_RESERVED_10_11_LEN,value)


/* INTRNUM */

#ifndef USBC_DEVICE_DCFG_INTRNUM_POS
#define USBC_DEVICE_DCFG_INTRNUM_POS      12
#endif

#ifndef USBC_DEVICE_DCFG_INTRNUM_LEN
#define USBC_DEVICE_DCFG_INTRNUM_LEN      5
#endif

#if defined(_V1) && !defined(DCFG_INTRNUM_R)
#define DCFG_INTRNUM_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_INTRNUM_POS, USBC_DEVICE_DCFG_INTRNUM_LEN)
#endif

#if defined(_V1) && !defined(DCFG_INTRNUM_W)
#define DCFG_INTRNUM_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_INTRNUM_POS, USBC_DEVICE_DCFG_INTRNUM_LEN,value)
#endif

#define USBC_DEVICE_DCFG_INTRNUM_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_INTRNUM_POS, USBC_DEVICE_DCFG_INTRNUM_LEN)

#define USBC_DEVICE_DCFG_INTRNUM_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_INTRNUM_POS, USBC_DEVICE_DCFG_INTRNUM_LEN,value)


/* NUMP */

#ifndef USBC_DEVICE_DCFG_NUMP_POS
#define USBC_DEVICE_DCFG_NUMP_POS      17
#endif

#ifndef USBC_DEVICE_DCFG_NUMP_LEN
#define USBC_DEVICE_DCFG_NUMP_LEN      5
#endif

#if defined(_V1) && !defined(DCFG_NUMP_R)
#define DCFG_NUMP_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_NUMP_POS, USBC_DEVICE_DCFG_NUMP_LEN)
#endif

#if defined(_V1) && !defined(DCFG_NUMP_W)
#define DCFG_NUMP_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_NUMP_POS, USBC_DEVICE_DCFG_NUMP_LEN,value)
#endif

#define USBC_DEVICE_DCFG_NUMP_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_NUMP_POS, USBC_DEVICE_DCFG_NUMP_LEN)

#define USBC_DEVICE_DCFG_NUMP_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_NUMP_POS, USBC_DEVICE_DCFG_NUMP_LEN,value)


/* LPMCAP */

#ifndef USBC_DEVICE_DCFG_LPMCAP_POS
#define USBC_DEVICE_DCFG_LPMCAP_POS      22
#endif

#ifndef USBC_DEVICE_DCFG_LPMCAP_LEN
#define USBC_DEVICE_DCFG_LPMCAP_LEN      1
#endif

#if defined(_V1) && !defined(DCFG_LPMCAP_R)
#define DCFG_LPMCAP_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_LPMCAP_POS, USBC_DEVICE_DCFG_LPMCAP_LEN)
#endif

#if defined(_V1) && !defined(DCFG_LPMCAP_W)
#define DCFG_LPMCAP_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_LPMCAP_POS, USBC_DEVICE_DCFG_LPMCAP_LEN,value)
#endif

#define USBC_DEVICE_DCFG_LPMCAP_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_LPMCAP_POS, USBC_DEVICE_DCFG_LPMCAP_LEN)

#define USBC_DEVICE_DCFG_LPMCAP_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_LPMCAP_POS, USBC_DEVICE_DCFG_LPMCAP_LEN,value)


/* IgnStrmPP */

#ifndef USBC_DEVICE_DCFG_IGNSTRMPP_POS
#define USBC_DEVICE_DCFG_IGNSTRMPP_POS      23
#endif

#ifndef USBC_DEVICE_DCFG_IGNSTRMPP_LEN
#define USBC_DEVICE_DCFG_IGNSTRMPP_LEN      1
#endif

#if defined(_V1) && !defined(DCFG_IGNSTRMPP_R)
#define DCFG_IGNSTRMPP_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_IGNSTRMPP_POS, USBC_DEVICE_DCFG_IGNSTRMPP_LEN)
#endif

#if defined(_V1) && !defined(DCFG_IGNSTRMPP_W)
#define DCFG_IGNSTRMPP_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_IGNSTRMPP_POS, USBC_DEVICE_DCFG_IGNSTRMPP_LEN,value)
#endif

#define USBC_DEVICE_DCFG_IGNSTRMPP_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_IGNSTRMPP_POS, USBC_DEVICE_DCFG_IGNSTRMPP_LEN)

#define USBC_DEVICE_DCFG_IGNSTRMPP_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_IGNSTRMPP_POS, USBC_DEVICE_DCFG_IGNSTRMPP_LEN,value)


/* reserved_24 */

#ifndef USBC_DEVICE_DCFG_RESERVED_24_POS
#define USBC_DEVICE_DCFG_RESERVED_24_POS      24
#endif

#ifndef USBC_DEVICE_DCFG_RESERVED_24_LEN
#define USBC_DEVICE_DCFG_RESERVED_24_LEN      1
#endif

#if defined(_V1) && !defined(DCFG_RESERVED_24_R)
#define DCFG_RESERVED_24_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_24_POS, USBC_DEVICE_DCFG_RESERVED_24_LEN)
#endif

#if defined(_V1) && !defined(DCFG_RESERVED_24_W)
#define DCFG_RESERVED_24_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_24_POS, USBC_DEVICE_DCFG_RESERVED_24_LEN,value)
#endif

#define USBC_DEVICE_DCFG_RESERVED_24_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_24_POS, USBC_DEVICE_DCFG_RESERVED_24_LEN)

#define USBC_DEVICE_DCFG_RESERVED_24_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_24_POS, USBC_DEVICE_DCFG_RESERVED_24_LEN,value)


/* reserved_31_25 */

#ifndef USBC_DEVICE_DCFG_RESERVED_31_25_POS
#define USBC_DEVICE_DCFG_RESERVED_31_25_POS      25
#endif

#ifndef USBC_DEVICE_DCFG_RESERVED_31_25_LEN
#define USBC_DEVICE_DCFG_RESERVED_31_25_LEN      7
#endif

#if defined(_V1) && !defined(DCFG_RESERVED_31_25_R)
#define DCFG_RESERVED_31_25_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_31_25_POS, USBC_DEVICE_DCFG_RESERVED_31_25_LEN)
#endif

#if defined(_V1) && !defined(DCFG_RESERVED_31_25_W)
#define DCFG_RESERVED_31_25_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_31_25_POS, USBC_DEVICE_DCFG_RESERVED_31_25_LEN,value)
#endif

#define USBC_DEVICE_DCFG_RESERVED_31_25_R        GetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_31_25_POS, USBC_DEVICE_DCFG_RESERVED_31_25_LEN)

#define USBC_DEVICE_DCFG_RESERVED_31_25_W(value) SetGroupBits32( (USBC_DEVICE_DCFG_VAL),USBC_DEVICE_DCFG_RESERVED_31_25_POS, USBC_DEVICE_DCFG_RESERVED_31_25_LEN,value)


/* REGISTER: DGCMDPAR */

#if defined(_V1) && !defined(DGCMDPAR_OFFSET)
#define DGCMDPAR_OFFSET 0x10
#endif

#if !defined(USBC_DEVICE_DGCMDPAR_OFFSET)
#define USBC_DEVICE_DGCMDPAR_OFFSET 0x10
#endif

#if defined(_V1) && !defined(DGCMDPAR_REG)
#define DGCMDPAR_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DGCMDPAR_OFFSET))
#endif

#if defined(_V1) && !defined(DGCMDPAR_VAL)
#define DGCMDPAR_VAL  PREFIX_VAL(DGCMDPAR_REG)
#endif

#define USBC_DEVICE_DGCMDPAR_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DGCMDPAR_OFFSET))
#define USBC_DEVICE_DGCMDPAR_VAL  PREFIX_VAL(USBC_DEVICE_DGCMDPAR_REG)

/* FIELDS: */

/* PARAMETER */

#ifndef USBC_DEVICE_DGCMDPAR_PARAMETER_POS
#define USBC_DEVICE_DGCMDPAR_PARAMETER_POS      0
#endif

#ifndef USBC_DEVICE_DGCMDPAR_PARAMETER_LEN
#define USBC_DEVICE_DGCMDPAR_PARAMETER_LEN      32
#endif

#if defined(_V1) && !defined(DGCMDPAR_PARAMETER_R)
#define DGCMDPAR_PARAMETER_R        GetGroupBits32( (USBC_DEVICE_DGCMDPAR_VAL),USBC_DEVICE_DGCMDPAR_PARAMETER_POS, USBC_DEVICE_DGCMDPAR_PARAMETER_LEN)
#endif

#if defined(_V1) && !defined(DGCMDPAR_PARAMETER_W)
#define DGCMDPAR_PARAMETER_W(value) SetGroupBits32( (USBC_DEVICE_DGCMDPAR_VAL),USBC_DEVICE_DGCMDPAR_PARAMETER_POS, USBC_DEVICE_DGCMDPAR_PARAMETER_LEN,value)
#endif

#define USBC_DEVICE_DGCMDPAR_PARAMETER_R        GetGroupBits32( (USBC_DEVICE_DGCMDPAR_VAL),USBC_DEVICE_DGCMDPAR_PARAMETER_POS, USBC_DEVICE_DGCMDPAR_PARAMETER_LEN)

#define USBC_DEVICE_DGCMDPAR_PARAMETER_W(value) SetGroupBits32( (USBC_DEVICE_DGCMDPAR_VAL),USBC_DEVICE_DGCMDPAR_PARAMETER_POS, USBC_DEVICE_DGCMDPAR_PARAMETER_LEN,value)


/* REGISTER: DGCMD */

#if defined(_V1) && !defined(DGCMD_OFFSET)
#define DGCMD_OFFSET 0x14
#endif

#if !defined(USBC_DEVICE_DGCMD_OFFSET)
#define USBC_DEVICE_DGCMD_OFFSET 0x14
#endif

#if defined(_V1) && !defined(DGCMD_REG)
#define DGCMD_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DGCMD_OFFSET))
#endif

#if defined(_V1) && !defined(DGCMD_VAL)
#define DGCMD_VAL  PREFIX_VAL(DGCMD_REG)
#endif

#define USBC_DEVICE_DGCMD_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DGCMD_OFFSET))
#define USBC_DEVICE_DGCMD_VAL  PREFIX_VAL(USBC_DEVICE_DGCMD_REG)

/* FIELDS: */

/* CMDTYP */

#ifndef USBC_DEVICE_DGCMD_CMDTYP_POS
#define USBC_DEVICE_DGCMD_CMDTYP_POS      0
#endif

#ifndef USBC_DEVICE_DGCMD_CMDTYP_LEN
#define USBC_DEVICE_DGCMD_CMDTYP_LEN      8
#endif

#if defined(_V1) && !defined(DGCMD_CMDTYP_R)
#define DGCMD_CMDTYP_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDTYP_POS, USBC_DEVICE_DGCMD_CMDTYP_LEN)
#endif

#if defined(_V1) && !defined(DGCMD_CMDTYP_W)
#define DGCMD_CMDTYP_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDTYP_POS, USBC_DEVICE_DGCMD_CMDTYP_LEN,value)
#endif

#define USBC_DEVICE_DGCMD_CMDTYP_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDTYP_POS, USBC_DEVICE_DGCMD_CMDTYP_LEN)

#define USBC_DEVICE_DGCMD_CMDTYP_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDTYP_POS, USBC_DEVICE_DGCMD_CMDTYP_LEN,value)


/* CMDIOC */

#ifndef USBC_DEVICE_DGCMD_CMDIOC_POS
#define USBC_DEVICE_DGCMD_CMDIOC_POS      8
#endif

#ifndef USBC_DEVICE_DGCMD_CMDIOC_LEN
#define USBC_DEVICE_DGCMD_CMDIOC_LEN      1
#endif

#if defined(_V1) && !defined(DGCMD_CMDIOC_R)
#define DGCMD_CMDIOC_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDIOC_POS, USBC_DEVICE_DGCMD_CMDIOC_LEN)
#endif

#if defined(_V1) && !defined(DGCMD_CMDIOC_W)
#define DGCMD_CMDIOC_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDIOC_POS, USBC_DEVICE_DGCMD_CMDIOC_LEN,value)
#endif

#define USBC_DEVICE_DGCMD_CMDIOC_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDIOC_POS, USBC_DEVICE_DGCMD_CMDIOC_LEN)

#define USBC_DEVICE_DGCMD_CMDIOC_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDIOC_POS, USBC_DEVICE_DGCMD_CMDIOC_LEN,value)


/* reserved_9 */

#ifndef USBC_DEVICE_DGCMD_RESERVED_9_POS
#define USBC_DEVICE_DGCMD_RESERVED_9_POS      9
#endif

#ifndef USBC_DEVICE_DGCMD_RESERVED_9_LEN
#define USBC_DEVICE_DGCMD_RESERVED_9_LEN      1
#endif

#if defined(_V1) && !defined(DGCMD_RESERVED_9_R)
#define DGCMD_RESERVED_9_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_9_POS, USBC_DEVICE_DGCMD_RESERVED_9_LEN)
#endif

#if defined(_V1) && !defined(DGCMD_RESERVED_9_W)
#define DGCMD_RESERVED_9_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_9_POS, USBC_DEVICE_DGCMD_RESERVED_9_LEN,value)
#endif

#define USBC_DEVICE_DGCMD_RESERVED_9_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_9_POS, USBC_DEVICE_DGCMD_RESERVED_9_LEN)

#define USBC_DEVICE_DGCMD_RESERVED_9_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_9_POS, USBC_DEVICE_DGCMD_RESERVED_9_LEN,value)


/* CMDACT */

#ifndef USBC_DEVICE_DGCMD_CMDACT_POS
#define USBC_DEVICE_DGCMD_CMDACT_POS      10
#endif

#ifndef USBC_DEVICE_DGCMD_CMDACT_LEN
#define USBC_DEVICE_DGCMD_CMDACT_LEN      1
#endif

#if defined(_V1) && !defined(DGCMD_CMDACT_R)
#define DGCMD_CMDACT_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDACT_POS, USBC_DEVICE_DGCMD_CMDACT_LEN)
#endif

#if defined(_V1) && !defined(DGCMD_CMDACT_W)
#define DGCMD_CMDACT_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDACT_POS, USBC_DEVICE_DGCMD_CMDACT_LEN,value)
#endif

#define USBC_DEVICE_DGCMD_CMDACT_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDACT_POS, USBC_DEVICE_DGCMD_CMDACT_LEN)

#define USBC_DEVICE_DGCMD_CMDACT_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDACT_POS, USBC_DEVICE_DGCMD_CMDACT_LEN,value)


/* reserved_11 */

#ifndef USBC_DEVICE_DGCMD_RESERVED_11_POS
#define USBC_DEVICE_DGCMD_RESERVED_11_POS      11
#endif

#ifndef USBC_DEVICE_DGCMD_RESERVED_11_LEN
#define USBC_DEVICE_DGCMD_RESERVED_11_LEN      1
#endif

#if defined(_V1) && !defined(DGCMD_RESERVED_11_R)
#define DGCMD_RESERVED_11_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_11_POS, USBC_DEVICE_DGCMD_RESERVED_11_LEN)
#endif

#if defined(_V1) && !defined(DGCMD_RESERVED_11_W)
#define DGCMD_RESERVED_11_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_11_POS, USBC_DEVICE_DGCMD_RESERVED_11_LEN,value)
#endif

#define USBC_DEVICE_DGCMD_RESERVED_11_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_11_POS, USBC_DEVICE_DGCMD_RESERVED_11_LEN)

#define USBC_DEVICE_DGCMD_RESERVED_11_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_11_POS, USBC_DEVICE_DGCMD_RESERVED_11_LEN,value)


/* CMDSTATUS */

#ifndef USBC_DEVICE_DGCMD_CMDSTATUS_POS
#define USBC_DEVICE_DGCMD_CMDSTATUS_POS      12
#endif

#ifndef USBC_DEVICE_DGCMD_CMDSTATUS_LEN
#define USBC_DEVICE_DGCMD_CMDSTATUS_LEN      4
#endif

#if defined(_V1) && !defined(DGCMD_CMDSTATUS_R)
#define DGCMD_CMDSTATUS_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDSTATUS_POS, USBC_DEVICE_DGCMD_CMDSTATUS_LEN)
#endif

#if defined(_V1) && !defined(DGCMD_CMDSTATUS_W)
#define DGCMD_CMDSTATUS_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDSTATUS_POS, USBC_DEVICE_DGCMD_CMDSTATUS_LEN,value)
#endif

#define USBC_DEVICE_DGCMD_CMDSTATUS_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDSTATUS_POS, USBC_DEVICE_DGCMD_CMDSTATUS_LEN)

#define USBC_DEVICE_DGCMD_CMDSTATUS_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_CMDSTATUS_POS, USBC_DEVICE_DGCMD_CMDSTATUS_LEN,value)


/* reserved_31_16 */

#ifndef USBC_DEVICE_DGCMD_RESERVED_31_16_POS
#define USBC_DEVICE_DGCMD_RESERVED_31_16_POS      16
#endif

#ifndef USBC_DEVICE_DGCMD_RESERVED_31_16_LEN
#define USBC_DEVICE_DGCMD_RESERVED_31_16_LEN      16
#endif

#if defined(_V1) && !defined(DGCMD_RESERVED_31_16_R)
#define DGCMD_RESERVED_31_16_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_31_16_POS, USBC_DEVICE_DGCMD_RESERVED_31_16_LEN)
#endif

#if defined(_V1) && !defined(DGCMD_RESERVED_31_16_W)
#define DGCMD_RESERVED_31_16_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_31_16_POS, USBC_DEVICE_DGCMD_RESERVED_31_16_LEN,value)
#endif

#define USBC_DEVICE_DGCMD_RESERVED_31_16_R        GetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_31_16_POS, USBC_DEVICE_DGCMD_RESERVED_31_16_LEN)

#define USBC_DEVICE_DGCMD_RESERVED_31_16_W(value) SetGroupBits32( (USBC_DEVICE_DGCMD_VAL),USBC_DEVICE_DGCMD_RESERVED_31_16_POS, USBC_DEVICE_DGCMD_RESERVED_31_16_LEN,value)


/* REGISTER: DALEPENA */

#if defined(_V1) && !defined(DALEPENA_OFFSET)
#define DALEPENA_OFFSET 0x20
#endif

#if !defined(USBC_DEVICE_DALEPENA_OFFSET)
#define USBC_DEVICE_DALEPENA_OFFSET 0x20
#endif

#if defined(_V1) && !defined(DALEPENA_REG)
#define DALEPENA_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DALEPENA_OFFSET))
#endif

#if defined(_V1) && !defined(DALEPENA_VAL)
#define DALEPENA_VAL  PREFIX_VAL(DALEPENA_REG)
#endif

#define USBC_DEVICE_DALEPENA_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DALEPENA_OFFSET))
#define USBC_DEVICE_DALEPENA_VAL  PREFIX_VAL(USBC_DEVICE_DALEPENA_REG)

/* FIELDS: */

/* USBACTEP */

#ifndef USBC_DEVICE_DALEPENA_USBACTEP_POS
#define USBC_DEVICE_DALEPENA_USBACTEP_POS      0
#endif

#ifndef USBC_DEVICE_DALEPENA_USBACTEP_LEN
#define USBC_DEVICE_DALEPENA_USBACTEP_LEN      32
#endif

#if defined(_V1) && !defined(DALEPENA_USBACTEP_R)
#define DALEPENA_USBACTEP_R        GetGroupBits32( (USBC_DEVICE_DALEPENA_VAL),USBC_DEVICE_DALEPENA_USBACTEP_POS, USBC_DEVICE_DALEPENA_USBACTEP_LEN)
#endif

#if defined(_V1) && !defined(DALEPENA_USBACTEP_W)
#define DALEPENA_USBACTEP_W(value) SetGroupBits32( (USBC_DEVICE_DALEPENA_VAL),USBC_DEVICE_DALEPENA_USBACTEP_POS, USBC_DEVICE_DALEPENA_USBACTEP_LEN,value)
#endif

#define USBC_DEVICE_DALEPENA_USBACTEP_R        GetGroupBits32( (USBC_DEVICE_DALEPENA_VAL),USBC_DEVICE_DALEPENA_USBACTEP_POS, USBC_DEVICE_DALEPENA_USBACTEP_LEN)

#define USBC_DEVICE_DALEPENA_USBACTEP_W(value) SetGroupBits32( (USBC_DEVICE_DALEPENA_VAL),USBC_DEVICE_DALEPENA_USBACTEP_POS, USBC_DEVICE_DALEPENA_USBACTEP_LEN,value)


/* REGISTER: DCTL */

#if defined(_V1) && !defined(DCTL_OFFSET)
#define DCTL_OFFSET 0x4
#endif

#if !defined(USBC_DEVICE_DCTL_OFFSET)
#define USBC_DEVICE_DCTL_OFFSET 0x4
#endif

#if defined(_V1) && !defined(DCTL_REG)
#define DCTL_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DCTL_OFFSET))
#endif

#if defined(_V1) && !defined(DCTL_VAL)
#define DCTL_VAL  PREFIX_VAL(DCTL_REG)
#endif

#define USBC_DEVICE_DCTL_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DCTL_OFFSET))
#define USBC_DEVICE_DCTL_VAL  PREFIX_VAL(USBC_DEVICE_DCTL_REG)

/* FIELDS: */

/* reserved_0 */

#ifndef USBC_DEVICE_DCTL_RESERVED_0_POS
#define USBC_DEVICE_DCTL_RESERVED_0_POS      0
#endif

#ifndef USBC_DEVICE_DCTL_RESERVED_0_LEN
#define USBC_DEVICE_DCTL_RESERVED_0_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_RESERVED_0_R)
#define DCTL_RESERVED_0_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_0_POS, USBC_DEVICE_DCTL_RESERVED_0_LEN)
#endif

#if defined(_V1) && !defined(DCTL_RESERVED_0_W)
#define DCTL_RESERVED_0_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_0_POS, USBC_DEVICE_DCTL_RESERVED_0_LEN,value)
#endif

#define USBC_DEVICE_DCTL_RESERVED_0_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_0_POS, USBC_DEVICE_DCTL_RESERVED_0_LEN)

#define USBC_DEVICE_DCTL_RESERVED_0_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_0_POS, USBC_DEVICE_DCTL_RESERVED_0_LEN,value)


/* TSTCTL */

#ifndef USBC_DEVICE_DCTL_TSTCTL_POS
#define USBC_DEVICE_DCTL_TSTCTL_POS      1
#endif

#ifndef USBC_DEVICE_DCTL_TSTCTL_LEN
#define USBC_DEVICE_DCTL_TSTCTL_LEN      4
#endif

#if defined(_V1) && !defined(DCTL_TSTCTL_R)
#define DCTL_TSTCTL_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_TSTCTL_POS, USBC_DEVICE_DCTL_TSTCTL_LEN)
#endif

#if defined(_V1) && !defined(DCTL_TSTCTL_W)
#define DCTL_TSTCTL_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_TSTCTL_POS, USBC_DEVICE_DCTL_TSTCTL_LEN,value)
#endif

#define USBC_DEVICE_DCTL_TSTCTL_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_TSTCTL_POS, USBC_DEVICE_DCTL_TSTCTL_LEN)

#define USBC_DEVICE_DCTL_TSTCTL_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_TSTCTL_POS, USBC_DEVICE_DCTL_TSTCTL_LEN,value)


/* ULSTCHNGREQ */

#ifndef USBC_DEVICE_DCTL_ULSTCHNGREQ_POS
#define USBC_DEVICE_DCTL_ULSTCHNGREQ_POS      5
#endif

#ifndef USBC_DEVICE_DCTL_ULSTCHNGREQ_LEN
#define USBC_DEVICE_DCTL_ULSTCHNGREQ_LEN      4
#endif

#if defined(_V1) && !defined(DCTL_ULSTCHNGREQ_R)
#define DCTL_ULSTCHNGREQ_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ULSTCHNGREQ_POS, USBC_DEVICE_DCTL_ULSTCHNGREQ_LEN)
#endif

#if defined(_V1) && !defined(DCTL_ULSTCHNGREQ_W)
#define DCTL_ULSTCHNGREQ_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ULSTCHNGREQ_POS, USBC_DEVICE_DCTL_ULSTCHNGREQ_LEN,value)
#endif

#define USBC_DEVICE_DCTL_ULSTCHNGREQ_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ULSTCHNGREQ_POS, USBC_DEVICE_DCTL_ULSTCHNGREQ_LEN)

#define USBC_DEVICE_DCTL_ULSTCHNGREQ_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ULSTCHNGREQ_POS, USBC_DEVICE_DCTL_ULSTCHNGREQ_LEN,value)


/* ACCEPTU1ENA */

#ifndef USBC_DEVICE_DCTL_ACCEPTU1ENA_POS
#define USBC_DEVICE_DCTL_ACCEPTU1ENA_POS      9
#endif

#ifndef USBC_DEVICE_DCTL_ACCEPTU1ENA_LEN
#define USBC_DEVICE_DCTL_ACCEPTU1ENA_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_ACCEPTU1ENA_R)
#define DCTL_ACCEPTU1ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU1ENA_POS, USBC_DEVICE_DCTL_ACCEPTU1ENA_LEN)
#endif

#if defined(_V1) && !defined(DCTL_ACCEPTU1ENA_W)
#define DCTL_ACCEPTU1ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU1ENA_POS, USBC_DEVICE_DCTL_ACCEPTU1ENA_LEN,value)
#endif

#define USBC_DEVICE_DCTL_ACCEPTU1ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU1ENA_POS, USBC_DEVICE_DCTL_ACCEPTU1ENA_LEN)

#define USBC_DEVICE_DCTL_ACCEPTU1ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU1ENA_POS, USBC_DEVICE_DCTL_ACCEPTU1ENA_LEN,value)


/* INITU1ENA */

#ifndef USBC_DEVICE_DCTL_INITU1ENA_POS
#define USBC_DEVICE_DCTL_INITU1ENA_POS      10
#endif

#ifndef USBC_DEVICE_DCTL_INITU1ENA_LEN
#define USBC_DEVICE_DCTL_INITU1ENA_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_INITU1ENA_R)
#define DCTL_INITU1ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU1ENA_POS, USBC_DEVICE_DCTL_INITU1ENA_LEN)
#endif

#if defined(_V1) && !defined(DCTL_INITU1ENA_W)
#define DCTL_INITU1ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU1ENA_POS, USBC_DEVICE_DCTL_INITU1ENA_LEN,value)
#endif

#define USBC_DEVICE_DCTL_INITU1ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU1ENA_POS, USBC_DEVICE_DCTL_INITU1ENA_LEN)

#define USBC_DEVICE_DCTL_INITU1ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU1ENA_POS, USBC_DEVICE_DCTL_INITU1ENA_LEN,value)


/* ACCEPTU2ENA */

#ifndef USBC_DEVICE_DCTL_ACCEPTU2ENA_POS
#define USBC_DEVICE_DCTL_ACCEPTU2ENA_POS      11
#endif

#ifndef USBC_DEVICE_DCTL_ACCEPTU2ENA_LEN
#define USBC_DEVICE_DCTL_ACCEPTU2ENA_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_ACCEPTU2ENA_R)
#define DCTL_ACCEPTU2ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU2ENA_POS, USBC_DEVICE_DCTL_ACCEPTU2ENA_LEN)
#endif

#if defined(_V1) && !defined(DCTL_ACCEPTU2ENA_W)
#define DCTL_ACCEPTU2ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU2ENA_POS, USBC_DEVICE_DCTL_ACCEPTU2ENA_LEN,value)
#endif

#define USBC_DEVICE_DCTL_ACCEPTU2ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU2ENA_POS, USBC_DEVICE_DCTL_ACCEPTU2ENA_LEN)

#define USBC_DEVICE_DCTL_ACCEPTU2ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_ACCEPTU2ENA_POS, USBC_DEVICE_DCTL_ACCEPTU2ENA_LEN,value)


/* INITU2ENA */

#ifndef USBC_DEVICE_DCTL_INITU2ENA_POS
#define USBC_DEVICE_DCTL_INITU2ENA_POS      12
#endif

#ifndef USBC_DEVICE_DCTL_INITU2ENA_LEN
#define USBC_DEVICE_DCTL_INITU2ENA_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_INITU2ENA_R)
#define DCTL_INITU2ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU2ENA_POS, USBC_DEVICE_DCTL_INITU2ENA_LEN)
#endif

#if defined(_V1) && !defined(DCTL_INITU2ENA_W)
#define DCTL_INITU2ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU2ENA_POS, USBC_DEVICE_DCTL_INITU2ENA_LEN,value)
#endif

#define USBC_DEVICE_DCTL_INITU2ENA_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU2ENA_POS, USBC_DEVICE_DCTL_INITU2ENA_LEN)

#define USBC_DEVICE_DCTL_INITU2ENA_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_INITU2ENA_POS, USBC_DEVICE_DCTL_INITU2ENA_LEN,value)


/* reserved_15_13 */

#ifndef USBC_DEVICE_DCTL_RESERVED_15_13_POS
#define USBC_DEVICE_DCTL_RESERVED_15_13_POS      13
#endif

#ifndef USBC_DEVICE_DCTL_RESERVED_15_13_LEN
#define USBC_DEVICE_DCTL_RESERVED_15_13_LEN      3
#endif

#if defined(_V1) && !defined(DCTL_RESERVED_15_13_R)
#define DCTL_RESERVED_15_13_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_15_13_POS, USBC_DEVICE_DCTL_RESERVED_15_13_LEN)
#endif

#if defined(_V1) && !defined(DCTL_RESERVED_15_13_W)
#define DCTL_RESERVED_15_13_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_15_13_POS, USBC_DEVICE_DCTL_RESERVED_15_13_LEN,value)
#endif

#define USBC_DEVICE_DCTL_RESERVED_15_13_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_15_13_POS, USBC_DEVICE_DCTL_RESERVED_15_13_LEN)

#define USBC_DEVICE_DCTL_RESERVED_15_13_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_15_13_POS, USBC_DEVICE_DCTL_RESERVED_15_13_LEN,value)


/* CSS */

#ifndef USBC_DEVICE_DCTL_CSS_POS
#define USBC_DEVICE_DCTL_CSS_POS      16
#endif

#ifndef USBC_DEVICE_DCTL_CSS_LEN
#define USBC_DEVICE_DCTL_CSS_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_CSS_R)
#define DCTL_CSS_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSS_POS, USBC_DEVICE_DCTL_CSS_LEN)
#endif

#if defined(_V1) && !defined(DCTL_CSS_W)
#define DCTL_CSS_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSS_POS, USBC_DEVICE_DCTL_CSS_LEN,value)
#endif

#define USBC_DEVICE_DCTL_CSS_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSS_POS, USBC_DEVICE_DCTL_CSS_LEN)

#define USBC_DEVICE_DCTL_CSS_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSS_POS, USBC_DEVICE_DCTL_CSS_LEN,value)


/* CRS */

#ifndef USBC_DEVICE_DCTL_CRS_POS
#define USBC_DEVICE_DCTL_CRS_POS      17
#endif

#ifndef USBC_DEVICE_DCTL_CRS_LEN
#define USBC_DEVICE_DCTL_CRS_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_CRS_R)
#define DCTL_CRS_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CRS_POS, USBC_DEVICE_DCTL_CRS_LEN)
#endif

#if defined(_V1) && !defined(DCTL_CRS_W)
#define DCTL_CRS_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CRS_POS, USBC_DEVICE_DCTL_CRS_LEN,value)
#endif

#define USBC_DEVICE_DCTL_CRS_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CRS_POS, USBC_DEVICE_DCTL_CRS_LEN)

#define USBC_DEVICE_DCTL_CRS_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CRS_POS, USBC_DEVICE_DCTL_CRS_LEN,value)


/* LPM_NYET_thres */

#ifndef USBC_DEVICE_DCTL_LPM_NYET_THRES_POS
#define USBC_DEVICE_DCTL_LPM_NYET_THRES_POS      20
#endif

#ifndef USBC_DEVICE_DCTL_LPM_NYET_THRES_LEN
#define USBC_DEVICE_DCTL_LPM_NYET_THRES_LEN      4
#endif

#if defined(_V1) && !defined(DCTL_LPM_NYET_THRES_R)
#define DCTL_LPM_NYET_THRES_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_LPM_NYET_THRES_POS, USBC_DEVICE_DCTL_LPM_NYET_THRES_LEN)
#endif

#if defined(_V1) && !defined(DCTL_LPM_NYET_THRES_W)
#define DCTL_LPM_NYET_THRES_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_LPM_NYET_THRES_POS, USBC_DEVICE_DCTL_LPM_NYET_THRES_LEN,value)
#endif

#define USBC_DEVICE_DCTL_LPM_NYET_THRES_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_LPM_NYET_THRES_POS, USBC_DEVICE_DCTL_LPM_NYET_THRES_LEN)

#define USBC_DEVICE_DCTL_LPM_NYET_THRES_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_LPM_NYET_THRES_POS, USBC_DEVICE_DCTL_LPM_NYET_THRES_LEN,value)


/* HIRDTHRES */

#ifndef USBC_DEVICE_DCTL_HIRDTHRES_POS
#define USBC_DEVICE_DCTL_HIRDTHRES_POS      24
#endif

#ifndef USBC_DEVICE_DCTL_HIRDTHRES_LEN
#define USBC_DEVICE_DCTL_HIRDTHRES_LEN      5
#endif

#if defined(_V1) && !defined(DCTL_HIRDTHRES_R)
#define DCTL_HIRDTHRES_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_HIRDTHRES_POS, USBC_DEVICE_DCTL_HIRDTHRES_LEN)
#endif

#if defined(_V1) && !defined(DCTL_HIRDTHRES_W)
#define DCTL_HIRDTHRES_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_HIRDTHRES_POS, USBC_DEVICE_DCTL_HIRDTHRES_LEN,value)
#endif

#define USBC_DEVICE_DCTL_HIRDTHRES_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_HIRDTHRES_POS, USBC_DEVICE_DCTL_HIRDTHRES_LEN)

#define USBC_DEVICE_DCTL_HIRDTHRES_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_HIRDTHRES_POS, USBC_DEVICE_DCTL_HIRDTHRES_LEN,value)


/* reserved_29 */

#ifndef USBC_DEVICE_DCTL_RESERVED_29_POS
#define USBC_DEVICE_DCTL_RESERVED_29_POS      29
#endif

#ifndef USBC_DEVICE_DCTL_RESERVED_29_LEN
#define USBC_DEVICE_DCTL_RESERVED_29_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_RESERVED_29_R)
#define DCTL_RESERVED_29_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_29_POS, USBC_DEVICE_DCTL_RESERVED_29_LEN)
#endif

#if defined(_V1) && !defined(DCTL_RESERVED_29_W)
#define DCTL_RESERVED_29_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_29_POS, USBC_DEVICE_DCTL_RESERVED_29_LEN,value)
#endif

#define USBC_DEVICE_DCTL_RESERVED_29_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_29_POS, USBC_DEVICE_DCTL_RESERVED_29_LEN)

#define USBC_DEVICE_DCTL_RESERVED_29_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RESERVED_29_POS, USBC_DEVICE_DCTL_RESERVED_29_LEN,value)


/* CSFTRST */

#ifndef USBC_DEVICE_DCTL_CSFTRST_POS
#define USBC_DEVICE_DCTL_CSFTRST_POS      30
#endif

#ifndef USBC_DEVICE_DCTL_CSFTRST_LEN
#define USBC_DEVICE_DCTL_CSFTRST_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_CSFTRST_R)
#define DCTL_CSFTRST_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSFTRST_POS, USBC_DEVICE_DCTL_CSFTRST_LEN)
#endif

#if defined(_V1) && !defined(DCTL_CSFTRST_W)
#define DCTL_CSFTRST_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSFTRST_POS, USBC_DEVICE_DCTL_CSFTRST_LEN,value)
#endif

#define USBC_DEVICE_DCTL_CSFTRST_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSFTRST_POS, USBC_DEVICE_DCTL_CSFTRST_LEN)

#define USBC_DEVICE_DCTL_CSFTRST_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_CSFTRST_POS, USBC_DEVICE_DCTL_CSFTRST_LEN,value)


/* RUN_STOP */

#ifndef USBC_DEVICE_DCTL_RUN_STOP_POS
#define USBC_DEVICE_DCTL_RUN_STOP_POS      31
#endif

#ifndef USBC_DEVICE_DCTL_RUN_STOP_LEN
#define USBC_DEVICE_DCTL_RUN_STOP_LEN      1
#endif

#if defined(_V1) && !defined(DCTL_RUN_STOP_R)
#define DCTL_RUN_STOP_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RUN_STOP_POS, USBC_DEVICE_DCTL_RUN_STOP_LEN)
#endif

#if defined(_V1) && !defined(DCTL_RUN_STOP_W)
#define DCTL_RUN_STOP_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RUN_STOP_POS, USBC_DEVICE_DCTL_RUN_STOP_LEN,value)
#endif

#define USBC_DEVICE_DCTL_RUN_STOP_R        GetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RUN_STOP_POS, USBC_DEVICE_DCTL_RUN_STOP_LEN)

#define USBC_DEVICE_DCTL_RUN_STOP_W(value) SetGroupBits32( (USBC_DEVICE_DCTL_VAL),USBC_DEVICE_DCTL_RUN_STOP_POS, USBC_DEVICE_DCTL_RUN_STOP_LEN,value)


/* REGISTER: DEVTEN */

#if defined(_V1) && !defined(DEVTEN_OFFSET)
#define DEVTEN_OFFSET 0x8
#endif

#if !defined(USBC_DEVICE_DEVTEN_OFFSET)
#define USBC_DEVICE_DEVTEN_OFFSET 0x8
#endif

#if defined(_V1) && !defined(DEVTEN_REG)
#define DEVTEN_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DEVTEN_OFFSET))
#endif

#if defined(_V1) && !defined(DEVTEN_VAL)
#define DEVTEN_VAL  PREFIX_VAL(DEVTEN_REG)
#endif

#define USBC_DEVICE_DEVTEN_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DEVTEN_OFFSET))
#define USBC_DEVICE_DEVTEN_VAL  PREFIX_VAL(USBC_DEVICE_DEVTEN_REG)

/* FIELDS: */

/* DISSCONNEVTEN */

#ifndef USBC_DEVICE_DEVTEN_DISSCONNEVTEN_POS
#define USBC_DEVICE_DEVTEN_DISSCONNEVTEN_POS      0
#endif

#ifndef USBC_DEVICE_DEVTEN_DISSCONNEVTEN_LEN
#define USBC_DEVICE_DEVTEN_DISSCONNEVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_DISSCONNEVTEN_R)
#define DEVTEN_DISSCONNEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_DISSCONNEVTEN_POS, USBC_DEVICE_DEVTEN_DISSCONNEVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_DISSCONNEVTEN_W)
#define DEVTEN_DISSCONNEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_DISSCONNEVTEN_POS, USBC_DEVICE_DEVTEN_DISSCONNEVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_DISSCONNEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_DISSCONNEVTEN_POS, USBC_DEVICE_DEVTEN_DISSCONNEVTEN_LEN)

#define USBC_DEVICE_DEVTEN_DISSCONNEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_DISSCONNEVTEN_POS, USBC_DEVICE_DEVTEN_DISSCONNEVTEN_LEN,value)


/* USBRSTEVTEN */

#ifndef USBC_DEVICE_DEVTEN_USBRSTEVTEN_POS
#define USBC_DEVICE_DEVTEN_USBRSTEVTEN_POS      1
#endif

#ifndef USBC_DEVICE_DEVTEN_USBRSTEVTEN_LEN
#define USBC_DEVICE_DEVTEN_USBRSTEVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_USBRSTEVTEN_R)
#define DEVTEN_USBRSTEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_USBRSTEVTEN_POS, USBC_DEVICE_DEVTEN_USBRSTEVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_USBRSTEVTEN_W)
#define DEVTEN_USBRSTEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_USBRSTEVTEN_POS, USBC_DEVICE_DEVTEN_USBRSTEVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_USBRSTEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_USBRSTEVTEN_POS, USBC_DEVICE_DEVTEN_USBRSTEVTEN_LEN)

#define USBC_DEVICE_DEVTEN_USBRSTEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_USBRSTEVTEN_POS, USBC_DEVICE_DEVTEN_USBRSTEVTEN_LEN,value)


/* CONNECTDONEEVTEN */

#ifndef USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_POS
#define USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_POS      2
#endif

#ifndef USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_LEN
#define USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_CONNECTDONEEVTEN_R)
#define DEVTEN_CONNECTDONEEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_POS, USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_CONNECTDONEEVTEN_W)
#define DEVTEN_CONNECTDONEEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_POS, USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_POS, USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_LEN)

#define USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_POS, USBC_DEVICE_DEVTEN_CONNECTDONEEVTEN_LEN,value)


/* ULSTCNGEN */

#ifndef USBC_DEVICE_DEVTEN_ULSTCNGEN_POS
#define USBC_DEVICE_DEVTEN_ULSTCNGEN_POS      3
#endif

#ifndef USBC_DEVICE_DEVTEN_ULSTCNGEN_LEN
#define USBC_DEVICE_DEVTEN_ULSTCNGEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_ULSTCNGEN_R)
#define DEVTEN_ULSTCNGEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ULSTCNGEN_POS, USBC_DEVICE_DEVTEN_ULSTCNGEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_ULSTCNGEN_W)
#define DEVTEN_ULSTCNGEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ULSTCNGEN_POS, USBC_DEVICE_DEVTEN_ULSTCNGEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_ULSTCNGEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ULSTCNGEN_POS, USBC_DEVICE_DEVTEN_ULSTCNGEN_LEN)

#define USBC_DEVICE_DEVTEN_ULSTCNGEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ULSTCNGEN_POS, USBC_DEVICE_DEVTEN_ULSTCNGEN_LEN,value)


/* WKUPEVTEN */

#ifndef USBC_DEVICE_DEVTEN_WKUPEVTEN_POS
#define USBC_DEVICE_DEVTEN_WKUPEVTEN_POS      4
#endif

#ifndef USBC_DEVICE_DEVTEN_WKUPEVTEN_LEN
#define USBC_DEVICE_DEVTEN_WKUPEVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_WKUPEVTEN_R)
#define DEVTEN_WKUPEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_WKUPEVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_WKUPEVTEN_W)
#define DEVTEN_WKUPEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_WKUPEVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_WKUPEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_WKUPEVTEN_LEN)

#define USBC_DEVICE_DEVTEN_WKUPEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_WKUPEVTEN_LEN,value)


/* HibernationReqEvtEn */

#ifndef USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_POS
#define USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_POS      5
#endif

#ifndef USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_LEN
#define USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_HIBERNATIONREQEVTEN_R)
#define DEVTEN_HIBERNATIONREQEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_POS, USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_HIBERNATIONREQEVTEN_W)
#define DEVTEN_HIBERNATIONREQEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_POS, USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_POS, USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_LEN)

#define USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_POS, USBC_DEVICE_DEVTEN_HIBERNATIONREQEVTEN_LEN,value)


/* U3L2L1SuspEn */

#ifndef USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_POS
#define USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_POS      6
#endif

#ifndef USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_LEN
#define USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_U3L2L1SUSPEN_R)
#define DEVTEN_U3L2L1SUSPEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_POS, USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_U3L2L1SUSPEN_W)
#define DEVTEN_U3L2L1SUSPEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_POS, USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_POS, USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_LEN)

#define USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_POS, USBC_DEVICE_DEVTEN_U3L2L1SUSPEN_LEN,value)


/* SOFTEVTEN */

#ifndef USBC_DEVICE_DEVTEN_SOFTEVTEN_POS
#define USBC_DEVICE_DEVTEN_SOFTEVTEN_POS      7
#endif

#ifndef USBC_DEVICE_DEVTEN_SOFTEVTEN_LEN
#define USBC_DEVICE_DEVTEN_SOFTEVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_SOFTEVTEN_R)
#define DEVTEN_SOFTEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_SOFTEVTEN_POS, USBC_DEVICE_DEVTEN_SOFTEVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_SOFTEVTEN_W)
#define DEVTEN_SOFTEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_SOFTEVTEN_POS, USBC_DEVICE_DEVTEN_SOFTEVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_SOFTEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_SOFTEVTEN_POS, USBC_DEVICE_DEVTEN_SOFTEVTEN_LEN)

#define USBC_DEVICE_DEVTEN_SOFTEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_SOFTEVTEN_POS, USBC_DEVICE_DEVTEN_SOFTEVTEN_LEN,value)


/* L1SUSPEN */

#ifndef USBC_DEVICE_DEVTEN_L1SUSPEN_POS
#define USBC_DEVICE_DEVTEN_L1SUSPEN_POS      8
#endif

#ifndef USBC_DEVICE_DEVTEN_L1SUSPEN_LEN
#define USBC_DEVICE_DEVTEN_L1SUSPEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_L1SUSPEN_R)
#define DEVTEN_L1SUSPEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1SUSPEN_POS, USBC_DEVICE_DEVTEN_L1SUSPEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_L1SUSPEN_W)
#define DEVTEN_L1SUSPEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1SUSPEN_POS, USBC_DEVICE_DEVTEN_L1SUSPEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_L1SUSPEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1SUSPEN_POS, USBC_DEVICE_DEVTEN_L1SUSPEN_LEN)

#define USBC_DEVICE_DEVTEN_L1SUSPEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1SUSPEN_POS, USBC_DEVICE_DEVTEN_L1SUSPEN_LEN,value)


/* ERRTICERREVTEN */

#ifndef USBC_DEVICE_DEVTEN_ERRTICERREVTEN_POS
#define USBC_DEVICE_DEVTEN_ERRTICERREVTEN_POS      9
#endif

#ifndef USBC_DEVICE_DEVTEN_ERRTICERREVTEN_LEN
#define USBC_DEVICE_DEVTEN_ERRTICERREVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_ERRTICERREVTEN_R)
#define DEVTEN_ERRTICERREVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ERRTICERREVTEN_POS, USBC_DEVICE_DEVTEN_ERRTICERREVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_ERRTICERREVTEN_W)
#define DEVTEN_ERRTICERREVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ERRTICERREVTEN_POS, USBC_DEVICE_DEVTEN_ERRTICERREVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_ERRTICERREVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ERRTICERREVTEN_POS, USBC_DEVICE_DEVTEN_ERRTICERREVTEN_LEN)

#define USBC_DEVICE_DEVTEN_ERRTICERREVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_ERRTICERREVTEN_POS, USBC_DEVICE_DEVTEN_ERRTICERREVTEN_LEN,value)


/* reserved_10 */

#ifndef USBC_DEVICE_DEVTEN_RESERVED_10_POS
#define USBC_DEVICE_DEVTEN_RESERVED_10_POS      10
#endif

#ifndef USBC_DEVICE_DEVTEN_RESERVED_10_LEN
#define USBC_DEVICE_DEVTEN_RESERVED_10_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_RESERVED_10_R)
#define DEVTEN_RESERVED_10_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_10_POS, USBC_DEVICE_DEVTEN_RESERVED_10_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_RESERVED_10_W)
#define DEVTEN_RESERVED_10_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_10_POS, USBC_DEVICE_DEVTEN_RESERVED_10_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_RESERVED_10_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_10_POS, USBC_DEVICE_DEVTEN_RESERVED_10_LEN)

#define USBC_DEVICE_DEVTEN_RESERVED_10_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_10_POS, USBC_DEVICE_DEVTEN_RESERVED_10_LEN,value)


/* reserved_11 */

#ifndef USBC_DEVICE_DEVTEN_RESERVED_11_POS
#define USBC_DEVICE_DEVTEN_RESERVED_11_POS      11
#endif

#ifndef USBC_DEVICE_DEVTEN_RESERVED_11_LEN
#define USBC_DEVICE_DEVTEN_RESERVED_11_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_RESERVED_11_R)
#define DEVTEN_RESERVED_11_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_11_POS, USBC_DEVICE_DEVTEN_RESERVED_11_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_RESERVED_11_W)
#define DEVTEN_RESERVED_11_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_11_POS, USBC_DEVICE_DEVTEN_RESERVED_11_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_RESERVED_11_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_11_POS, USBC_DEVICE_DEVTEN_RESERVED_11_LEN)

#define USBC_DEVICE_DEVTEN_RESERVED_11_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_11_POS, USBC_DEVICE_DEVTEN_RESERVED_11_LEN,value)


/* VENDEVTSTRCVDEN */

#ifndef USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_POS
#define USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_POS      12
#endif

#ifndef USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_LEN
#define USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_VENDEVTSTRCVDEN_R)
#define DEVTEN_VENDEVTSTRCVDEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_POS, USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_VENDEVTSTRCVDEN_W)
#define DEVTEN_VENDEVTSTRCVDEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_POS, USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_POS, USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_LEN)

#define USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_POS, USBC_DEVICE_DEVTEN_VENDEVTSTRCVDEN_LEN,value)


/* L1WKUPEVTEN */

#ifndef USBC_DEVICE_DEVTEN_L1WKUPEVTEN_POS
#define USBC_DEVICE_DEVTEN_L1WKUPEVTEN_POS      14
#endif

#ifndef USBC_DEVICE_DEVTEN_L1WKUPEVTEN_LEN
#define USBC_DEVICE_DEVTEN_L1WKUPEVTEN_LEN      1
#endif

#if defined(_V1) && !defined(DEVTEN_L1WKUPEVTEN_R)
#define DEVTEN_L1WKUPEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_L1WKUPEVTEN_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_L1WKUPEVTEN_W)
#define DEVTEN_L1WKUPEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_L1WKUPEVTEN_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_L1WKUPEVTEN_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_L1WKUPEVTEN_LEN)

#define USBC_DEVICE_DEVTEN_L1WKUPEVTEN_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_L1WKUPEVTEN_POS, USBC_DEVICE_DEVTEN_L1WKUPEVTEN_LEN,value)


/* reserved_31_15 */

#ifndef USBC_DEVICE_DEVTEN_RESERVED_31_15_POS
#define USBC_DEVICE_DEVTEN_RESERVED_31_15_POS      15
#endif

#ifndef USBC_DEVICE_DEVTEN_RESERVED_31_15_LEN
#define USBC_DEVICE_DEVTEN_RESERVED_31_15_LEN      17
#endif

#if defined(_V1) && !defined(DEVTEN_RESERVED_31_15_R)
#define DEVTEN_RESERVED_31_15_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_31_15_POS, USBC_DEVICE_DEVTEN_RESERVED_31_15_LEN)
#endif

#if defined(_V1) && !defined(DEVTEN_RESERVED_31_15_W)
#define DEVTEN_RESERVED_31_15_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_31_15_POS, USBC_DEVICE_DEVTEN_RESERVED_31_15_LEN,value)
#endif

#define USBC_DEVICE_DEVTEN_RESERVED_31_15_R        GetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_31_15_POS, USBC_DEVICE_DEVTEN_RESERVED_31_15_LEN)

#define USBC_DEVICE_DEVTEN_RESERVED_31_15_W(value) SetGroupBits32( (USBC_DEVICE_DEVTEN_VAL),USBC_DEVICE_DEVTEN_RESERVED_31_15_POS, USBC_DEVICE_DEVTEN_RESERVED_31_15_LEN,value)


/* REGISTER: DSTS */

#if defined(_V1) && !defined(DSTS_OFFSET)
#define DSTS_OFFSET 0xc
#endif

#if !defined(USBC_DEVICE_DSTS_OFFSET)
#define USBC_DEVICE_DSTS_OFFSET 0xc
#endif

#if defined(_V1) && !defined(DSTS_REG)
#define DSTS_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DSTS_OFFSET))
#endif

#if defined(_V1) && !defined(DSTS_VAL)
#define DSTS_VAL  PREFIX_VAL(DSTS_REG)
#endif

#define USBC_DEVICE_DSTS_REG ((volatile UINT32 *) (USBC_DEVICE_BASE + USBC_DEVICE_DSTS_OFFSET))
#define USBC_DEVICE_DSTS_VAL  PREFIX_VAL(USBC_DEVICE_DSTS_REG)

/* FIELDS: */

/* CONNECTSPD */

#ifndef USBC_DEVICE_DSTS_CONNECTSPD_POS
#define USBC_DEVICE_DSTS_CONNECTSPD_POS      0
#endif

#ifndef USBC_DEVICE_DSTS_CONNECTSPD_LEN
#define USBC_DEVICE_DSTS_CONNECTSPD_LEN      3
#endif

#if defined(_V1) && !defined(DSTS_CONNECTSPD_R)
#define DSTS_CONNECTSPD_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_CONNECTSPD_POS, USBC_DEVICE_DSTS_CONNECTSPD_LEN)
#endif

#if defined(_V1) && !defined(DSTS_CONNECTSPD_W)
#define DSTS_CONNECTSPD_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_CONNECTSPD_POS, USBC_DEVICE_DSTS_CONNECTSPD_LEN,value)
#endif

#define USBC_DEVICE_DSTS_CONNECTSPD_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_CONNECTSPD_POS, USBC_DEVICE_DSTS_CONNECTSPD_LEN)

#define USBC_DEVICE_DSTS_CONNECTSPD_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_CONNECTSPD_POS, USBC_DEVICE_DSTS_CONNECTSPD_LEN,value)


/* SOFFN */

#ifndef USBC_DEVICE_DSTS_SOFFN_POS
#define USBC_DEVICE_DSTS_SOFFN_POS      3
#endif

#ifndef USBC_DEVICE_DSTS_SOFFN_LEN
#define USBC_DEVICE_DSTS_SOFFN_LEN      14
#endif

#if defined(_V1) && !defined(DSTS_SOFFN_R)
#define DSTS_SOFFN_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SOFFN_POS, USBC_DEVICE_DSTS_SOFFN_LEN)
#endif

#if defined(_V1) && !defined(DSTS_SOFFN_W)
#define DSTS_SOFFN_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SOFFN_POS, USBC_DEVICE_DSTS_SOFFN_LEN,value)
#endif

#define USBC_DEVICE_DSTS_SOFFN_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SOFFN_POS, USBC_DEVICE_DSTS_SOFFN_LEN)

#define USBC_DEVICE_DSTS_SOFFN_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SOFFN_POS, USBC_DEVICE_DSTS_SOFFN_LEN,value)


/* RXFIFOEMPTY */

#ifndef USBC_DEVICE_DSTS_RXFIFOEMPTY_POS
#define USBC_DEVICE_DSTS_RXFIFOEMPTY_POS      17
#endif

#ifndef USBC_DEVICE_DSTS_RXFIFOEMPTY_LEN
#define USBC_DEVICE_DSTS_RXFIFOEMPTY_LEN      1
#endif

#if defined(_V1) && !defined(DSTS_RXFIFOEMPTY_R)
#define DSTS_RXFIFOEMPTY_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RXFIFOEMPTY_POS, USBC_DEVICE_DSTS_RXFIFOEMPTY_LEN)
#endif

#if defined(_V1) && !defined(DSTS_RXFIFOEMPTY_W)
#define DSTS_RXFIFOEMPTY_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RXFIFOEMPTY_POS, USBC_DEVICE_DSTS_RXFIFOEMPTY_LEN,value)
#endif

#define USBC_DEVICE_DSTS_RXFIFOEMPTY_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RXFIFOEMPTY_POS, USBC_DEVICE_DSTS_RXFIFOEMPTY_LEN)

#define USBC_DEVICE_DSTS_RXFIFOEMPTY_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RXFIFOEMPTY_POS, USBC_DEVICE_DSTS_RXFIFOEMPTY_LEN,value)


/* USBLNKST */

#ifndef USBC_DEVICE_DSTS_USBLNKST_POS
#define USBC_DEVICE_DSTS_USBLNKST_POS      18
#endif

#ifndef USBC_DEVICE_DSTS_USBLNKST_LEN
#define USBC_DEVICE_DSTS_USBLNKST_LEN      4
#endif

#if defined(_V1) && !defined(DSTS_USBLNKST_R)
#define DSTS_USBLNKST_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_USBLNKST_POS, USBC_DEVICE_DSTS_USBLNKST_LEN)
#endif

#if defined(_V1) && !defined(DSTS_USBLNKST_W)
#define DSTS_USBLNKST_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_USBLNKST_POS, USBC_DEVICE_DSTS_USBLNKST_LEN,value)
#endif

#define USBC_DEVICE_DSTS_USBLNKST_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_USBLNKST_POS, USBC_DEVICE_DSTS_USBLNKST_LEN)

#define USBC_DEVICE_DSTS_USBLNKST_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_USBLNKST_POS, USBC_DEVICE_DSTS_USBLNKST_LEN,value)


/* DEVCTRLHLT */

#ifndef USBC_DEVICE_DSTS_DEVCTRLHLT_POS
#define USBC_DEVICE_DSTS_DEVCTRLHLT_POS      22
#endif

#ifndef USBC_DEVICE_DSTS_DEVCTRLHLT_LEN
#define USBC_DEVICE_DSTS_DEVCTRLHLT_LEN      1
#endif

#if defined(_V1) && !defined(DSTS_DEVCTRLHLT_R)
#define DSTS_DEVCTRLHLT_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DEVCTRLHLT_POS, USBC_DEVICE_DSTS_DEVCTRLHLT_LEN)
#endif

#if defined(_V1) && !defined(DSTS_DEVCTRLHLT_W)
#define DSTS_DEVCTRLHLT_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DEVCTRLHLT_POS, USBC_DEVICE_DSTS_DEVCTRLHLT_LEN,value)
#endif

#define USBC_DEVICE_DSTS_DEVCTRLHLT_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DEVCTRLHLT_POS, USBC_DEVICE_DSTS_DEVCTRLHLT_LEN)

#define USBC_DEVICE_DSTS_DEVCTRLHLT_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DEVCTRLHLT_POS, USBC_DEVICE_DSTS_DEVCTRLHLT_LEN,value)


/* COREIDLE */

#ifndef USBC_DEVICE_DSTS_COREIDLE_POS
#define USBC_DEVICE_DSTS_COREIDLE_POS      23
#endif

#ifndef USBC_DEVICE_DSTS_COREIDLE_LEN
#define USBC_DEVICE_DSTS_COREIDLE_LEN      1
#endif

#if defined(_V1) && !defined(DSTS_COREIDLE_R)
#define DSTS_COREIDLE_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_COREIDLE_POS, USBC_DEVICE_DSTS_COREIDLE_LEN)
#endif

#if defined(_V1) && !defined(DSTS_COREIDLE_W)
#define DSTS_COREIDLE_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_COREIDLE_POS, USBC_DEVICE_DSTS_COREIDLE_LEN,value)
#endif

#define USBC_DEVICE_DSTS_COREIDLE_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_COREIDLE_POS, USBC_DEVICE_DSTS_COREIDLE_LEN)

#define USBC_DEVICE_DSTS_COREIDLE_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_COREIDLE_POS, USBC_DEVICE_DSTS_COREIDLE_LEN,value)


/* SSS */

#ifndef USBC_DEVICE_DSTS_SSS_POS
#define USBC_DEVICE_DSTS_SSS_POS      24
#endif

#ifndef USBC_DEVICE_DSTS_SSS_LEN
#define USBC_DEVICE_DSTS_SSS_LEN      1
#endif

#if defined(_V1) && !defined(DSTS_SSS_R)
#define DSTS_SSS_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SSS_POS, USBC_DEVICE_DSTS_SSS_LEN)
#endif

#if defined(_V1) && !defined(DSTS_SSS_W)
#define DSTS_SSS_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SSS_POS, USBC_DEVICE_DSTS_SSS_LEN,value)
#endif

#define USBC_DEVICE_DSTS_SSS_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SSS_POS, USBC_DEVICE_DSTS_SSS_LEN)

#define USBC_DEVICE_DSTS_SSS_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SSS_POS, USBC_DEVICE_DSTS_SSS_LEN,value)


/* RSS */

#ifndef USBC_DEVICE_DSTS_RSS_POS
#define USBC_DEVICE_DSTS_RSS_POS      25
#endif

#ifndef USBC_DEVICE_DSTS_RSS_LEN
#define USBC_DEVICE_DSTS_RSS_LEN      1
#endif

#if defined(_V1) && !defined(DSTS_RSS_R)
#define DSTS_RSS_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RSS_POS, USBC_DEVICE_DSTS_RSS_LEN)
#endif

#if defined(_V1) && !defined(DSTS_RSS_W)
#define DSTS_RSS_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RSS_POS, USBC_DEVICE_DSTS_RSS_LEN,value)
#endif

#define USBC_DEVICE_DSTS_RSS_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RSS_POS, USBC_DEVICE_DSTS_RSS_LEN)

#define USBC_DEVICE_DSTS_RSS_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RSS_POS, USBC_DEVICE_DSTS_RSS_LEN,value)


/* reserved_27_26 */

#ifndef USBC_DEVICE_DSTS_RESERVED_27_26_POS
#define USBC_DEVICE_DSTS_RESERVED_27_26_POS      26
#endif

#ifndef USBC_DEVICE_DSTS_RESERVED_27_26_LEN
#define USBC_DEVICE_DSTS_RESERVED_27_26_LEN      2
#endif

#if defined(_V1) && !defined(DSTS_RESERVED_27_26_R)
#define DSTS_RESERVED_27_26_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_27_26_POS, USBC_DEVICE_DSTS_RESERVED_27_26_LEN)
#endif

#if defined(_V1) && !defined(DSTS_RESERVED_27_26_W)
#define DSTS_RESERVED_27_26_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_27_26_POS, USBC_DEVICE_DSTS_RESERVED_27_26_LEN,value)
#endif

#define USBC_DEVICE_DSTS_RESERVED_27_26_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_27_26_POS, USBC_DEVICE_DSTS_RESERVED_27_26_LEN)

#define USBC_DEVICE_DSTS_RESERVED_27_26_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_27_26_POS, USBC_DEVICE_DSTS_RESERVED_27_26_LEN,value)


/* SRE */

#ifndef USBC_DEVICE_DSTS_SRE_POS
#define USBC_DEVICE_DSTS_SRE_POS      28
#endif

#ifndef USBC_DEVICE_DSTS_SRE_LEN
#define USBC_DEVICE_DSTS_SRE_LEN      1
#endif

#if defined(_V1) && !defined(DSTS_SRE_R)
#define DSTS_SRE_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SRE_POS, USBC_DEVICE_DSTS_SRE_LEN)
#endif

#if defined(_V1) && !defined(DSTS_SRE_W)
#define DSTS_SRE_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SRE_POS, USBC_DEVICE_DSTS_SRE_LEN,value)
#endif

#define USBC_DEVICE_DSTS_SRE_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SRE_POS, USBC_DEVICE_DSTS_SRE_LEN)

#define USBC_DEVICE_DSTS_SRE_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_SRE_POS, USBC_DEVICE_DSTS_SRE_LEN,value)


/* DCNRD */

#ifndef USBC_DEVICE_DSTS_DCNRD_POS
#define USBC_DEVICE_DSTS_DCNRD_POS      29
#endif

#ifndef USBC_DEVICE_DSTS_DCNRD_LEN
#define USBC_DEVICE_DSTS_DCNRD_LEN      1
#endif

#if defined(_V1) && !defined(DSTS_DCNRD_R)
#define DSTS_DCNRD_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DCNRD_POS, USBC_DEVICE_DSTS_DCNRD_LEN)
#endif

#if defined(_V1) && !defined(DSTS_DCNRD_W)
#define DSTS_DCNRD_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DCNRD_POS, USBC_DEVICE_DSTS_DCNRD_LEN,value)
#endif

#define USBC_DEVICE_DSTS_DCNRD_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DCNRD_POS, USBC_DEVICE_DSTS_DCNRD_LEN)

#define USBC_DEVICE_DSTS_DCNRD_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_DCNRD_POS, USBC_DEVICE_DSTS_DCNRD_LEN,value)


/* reserved_31_30 */

#ifndef USBC_DEVICE_DSTS_RESERVED_31_30_POS
#define USBC_DEVICE_DSTS_RESERVED_31_30_POS      30
#endif

#ifndef USBC_DEVICE_DSTS_RESERVED_31_30_LEN
#define USBC_DEVICE_DSTS_RESERVED_31_30_LEN      2
#endif

#if defined(_V1) && !defined(DSTS_RESERVED_31_30_R)
#define DSTS_RESERVED_31_30_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_31_30_POS, USBC_DEVICE_DSTS_RESERVED_31_30_LEN)
#endif

#if defined(_V1) && !defined(DSTS_RESERVED_31_30_W)
#define DSTS_RESERVED_31_30_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_31_30_POS, USBC_DEVICE_DSTS_RESERVED_31_30_LEN,value)
#endif

#define USBC_DEVICE_DSTS_RESERVED_31_30_R        GetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_31_30_POS, USBC_DEVICE_DSTS_RESERVED_31_30_LEN)

#define USBC_DEVICE_DSTS_RESERVED_31_30_W(value) SetGroupBits32( (USBC_DEVICE_DSTS_VAL),USBC_DEVICE_DSTS_RESERVED_31_30_POS, USBC_DEVICE_DSTS_RESERVED_31_30_LEN,value)


/* OFFSET TABLE: */
#define usbc_device_offset_tbl_values	DCFG_OFFSET, DGCMDPAR_OFFSET, DGCMD_OFFSET, DALEPENA_OFFSET, DCTL_OFFSET, DEVTEN_OFFSET, DSTS_OFFSET


/* REGISTERS RESET VAL: */
#define usbc_device_regs_reset_val	0x80804, 0x0, 0x0, 0x0, 0xF00000, 0x0, 0xD20004

#endif

/* End of USBC_DEVICE */
/* ///////////////////////////////////////////////////////////////////////*/
