/* c_eip28.h
 *
 * Configuration options for the EIP28 Driver Library.
 * The project-specific cs_eip28.h file is included,
 * where-after defaults are provided for missing parameters.
 *
 * Do not edit this file; edit cs_eip28.h instead.
 */

/*****************************************************************************
* Copyright (c) 2007-2018 INSIDE Secure B.V. All Rights Reserved.
*
* This confidential and proprietary software may be used only as authorized
* by a licensing agreement from INSIDE Secure.
*
* The entire notice above must be reproduced on all authorized copies that
* may only be made to the extent permitted by a licensing agreement from
* INSIDE Secure.
*
* For more information or support, please go to our online support system at
* https://customersupport.insidesecure.com.
* In case you do not have an account for this system, please send an e-mail
* to ESSEmbeddedHW-Support@insidesecure.com.
*****************************************************************************/

// get project-level configuration settings
#include "cs_eip28.h"


// Disable strict checking of vectors in PKA RAM if the strict
// argument check is disabled
#ifndef EIP28_STRICT_ARGS
#ifdef EIP28_STRICT_VECTORS
#undef EIP28_STRICT_VECTORS
#endif
#endif


// provide backup values for all missing configuration parameters

#ifndef EIP28_VECTOR_BITS_MAX
#define EIP28_VECTOR_BITS_MAX  4096
#endif

// other configuration parameters that cannot be set in cs_eip28.h

#ifdef EIP28_VECTOR_MAXLEN
#undef EIP28_VECTOR_MAXLEN
#endif

#define EIP28_VECTOR_MAXLEN (EIP28_VECTOR_BITS_MAX/32)

#ifdef EIP28_REMOVE_DIVIDE
#ifdef EIP28_REMOVE_MODULUS
#define EIP28_REMOVE_READRESULT_REMAINDER
#endif
#endif


#ifdef EIP28_REMOVE_ECCADD
#ifdef EIP28_REMOVE_ECCMUL
#define EIP28_REMOVE_READRESULT_ECCSTATUS
#endif
#endif


/* end of file c_eip28.h */
