/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "metadata.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(INU_metadata_Sensor_ID, INU_metadata_Sensor_ID, AUTO)


PB_BIND(INU_metadata_Sensor, INU_metadata_Sensor, AUTO)


PB_BIND(INU_metadata_FrameCounter, INU_metadata_FrameCounter, AUTO)


PB_BIND(INU_metadata_ISO, INU_metadata_ISO, AUTO)


PB_BIND(INU_metadata_Exposure, INU_metadata_Exposure, AUTO)


PB_BIND(INU_metadata_Gain, INU_metadata_Gain, AUTO)


PB_BIND(INU_metadata_WhiteBalance_Temperature, INU_metadata_WhiteBalance_Temperature, AUTO)


PB_BIND(INU_metadata_EVCompensation, INU_metadata_EVCompensation, AUTO)


PB_BIND(INU_metadata_FlickerCompensation, INU_metadata_FlickerCompensation, AUTO)


PB_BIND(INU_metadata_Sharpness, INU_metadata_Sharpness, AUTO)


PB_BIND(INU_metadata_NoiseReduction, INU_metadata_NoiseReduction, AUTO)


PB_BIND(INU_metadata_FrameRate, INU_metadata_FrameRate, AUTO)


PB_BIND(INU_metadata_CCM_In_use, INU_metadata_CCM_In_use, AUTO)


PB_BIND(INU_metadata_AFCropPositon, INU_metadata_AFCropPositon, AUTO)


PB_BIND(INU_metadata_AFFocusPosition, INU_metadata_AFFocusPosition, AUTO)


PB_BIND(INU_metadata_RGBHistogram, INU_metadata_RGBHistogram, AUTO)


PB_BIND(INU_metadata_ContrastValue, INU_metadata_ContrastValue, AUTO)


PB_BIND(INU_metadata_EdgeEnhancement, INU_metadata_EdgeEnhancement, AUTO)


PB_BIND(INU_metadata_ROI, INU_metadata_ROI, AUTO)


PB_BIND(INU_metadata_ISP_WBGain, INU_metadata_ISP_WBGain, AUTO)


PB_BIND(INU_metadata_ISP_ColourCorrectionOffset, INU_metadata_ISP_ColourCorrectionOffset, AUTO)


PB_BIND(INU_metadata_ISP_AWB_closedLoop, INU_metadata_ISP_AWB_closedLoop, AUTO)


PB_BIND(INU_metadata_ISP_AE_closedLoop, INU_metadata_ISP_AE_closedLoop, AUTO)


PB_BIND(INU_metadata_ISP_ColourCorrectionCoefficient, INU_metadata_ISP_ColourCorrectionCoefficient, AUTO)


PB_BIND(INU_metadata_ISP_AWB, INU_metadata_ISP_AWB, AUTO)


PB_BIND(INU_metadata_ISP_WBPameters, INU_metadata_ISP_WBPameters, AUTO)


PB_BIND(INU_metadata_ISP_AE, INU_metadata_ISP_AE, AUTO)


PB_BIND(INU_metadata_ISP_ExpoParams, INU_metadata_ISP_ExpoParams, AUTO)


PB_BIND(INU_metadata_Command_Sync, INU_metadata_Command_Sync, AUTO)


PB_BIND(INU_metadata_Sensor_MetaData, INU_metadata_Sensor_MetaData, 2)


PB_BIND(INU_metadata_Manual_Sensor_Command, INU_metadata_Manual_Sensor_Command, AUTO)


PB_BIND(INU_metadata_Timestamp, INU_metadata_Timestamp, AUTO)


PB_BIND(INU_metadata_FrameID, INU_metadata_FrameID, AUTO)


PB_BIND(INU_metadata_Debug_Timing_Information, INU_metadata_Debug_Timing_Information, AUTO)


PB_BIND(INU_metadata_Debug, INU_metadata_Debug, AUTO)


PB_BIND(INU_metadata_State, INU_metadata_State, 2)


PB_BIND(INU_metadata_TopLevel, INU_metadata_TopLevel, 2)


PB_BIND(INU_metadata_UART_Debug, INU_metadata_UART_Debug, AUTO)


PB_BIND(INU_metadata_IMU_Batching, INU_metadata_IMU_Batching, AUTO)


PB_BIND(INU_metadata_IMU_Timestamp, INU_metadata_IMU_Timestamp, AUTO)


PB_BIND(INU_metadata_RTC_Timestamp, INU_metadata_RTC_Timestamp, AUTO)











