#ifndef _M_TBL_H_
#define _M_TBL_H_

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
   //compound types
   M_FIRST_COMPOUND_TYPE_E = 0,
   M_INU_CMDG_posTemperatureT = M_FIRST_COMPOUND_TYPE_E,
   M_INUG_ioctlCalibrationPathInfoT,
   M_INU_DEFSG_sensorOffsetsT,
   M_INTERNAL_CMDG_getBufT,
   M_INTERNAL_CMDG_sendBufT,
   M_INTERNAL_CMDG_waitBufAckT,
   M_INTERNAL_CMDG_lutChunkHdrT,
   M_INTERNAL_CMDG_CdnnLoadNetworkHdrT,
   M_INTERNAL_CMDG_CdnnReleaseAllHdrT,
   M_INTERNAL_CMDG_CdnnAllocNetworkHdrT,
   M_INTERNAL_CMDG_VisionProcLoadBackgroundHdrT,
   M_INTERNAL_CMDG_BackgroundReleaseHdrT,
   M_INTERNAL_CMDG_VisionProcAllocBackgroundHdrT,
   M_INTERNAL_CMDG_cevaAppChunkHdrT,
   M_INTERNAL_CMDG_sendBufChunkHdrT,
   M_INTERNAL_CMDG_getReadFuncT,
   M_INTERNAL_CMDG_readBufChunkHdrT,
   M_INTERNAL_CMDG_flashChunkHdrT,
   M_INTERNAL_CMDG_pingT,
   M_INTERNAL_CMDG_AllocGpBufHdrT,
   M_INTERNAL_CMDG_FreeGpBufHdrT,
   M_INTERNAL_CMDG_SendGpFileHdrT,
   M_INTERNAL_CMDG_UpdateRawNandSecT,
   M_inu_device__watchdog_timeout_t,
   M_inu_device__socRegT,
   M_inu_device__i2cRegT,
   M_inu_device__attRegT,
   M_inu_device__waitRegT,
   M_inu_device__readRegT,
   M_inu_device__writeRegT,
   M_inu_device__version,
   M_inu_device__readWriteBuf,
   M_inu_device__pwmConfigT,
   M_inu_device__calibUpdateT,
   M_inu_device__eepromAccessT,
   M_inu_device__powerDownT,
   M_INUG_ioctlDbControlT,
   M_inu_device__powerModeT,
   M_inu_device__tuningParamsT,
   M_inu_device__set_time_t,
   M_inu_device__get_time_t,
   M_inu_device__get_rtc_lock_t,
   M_inu_sensor__gain_t,
   M_inu_sensor__runtimeCfg_t,
   M_inu_sensor__getFocusParams_t,
   M_inu_sensor__setFocusParams_t,
   M_inu_sensor__setCropParams_t,
   M_INUG_ioctlBufferRdT,
   M_inu_device__alternateProjCfgT,
   M_INUG_ioctlLoggerSetParamsT,
   M_INTERNAL_CMDG_logDataHdrT,
   M_INUG_ioctlCalibrationRdT,
   M_INUG_ioctlCalibrationHdrRdT,
   M_INUG_ioctlEraseDynCalibrationT,
   M_INUG_ioctlBootSetModeT,
   M_INUG_ioctlProjectorSetModeT,
   M_INUG_ioctlProjectorGetModeT,
   M_INTERNAL_CMDG_getWriteFuncT,
   M_INUG_ioctlSysGetModeT,
   M_INUG_configMetaT,
   M_INUG_ioctlSysSetModeT,
   M_INUG_ioctlSysUart2LbProbeT,
   M_inu_ref__container,
   M_inu_ref__CtorParams,
   M_inu_ref__DtorParams,
   M_inu_graph__CtorParams,
   M_inu_log__configT,
   M_inu_logger__CtorParams,
   M_inu_node__CtorParams,
   M_inu_data__CtorParams,
   M_inu_function__CtorParams,
   M_inu_image__descriptor,
   M_inu_image__sensorInfoT,
   M_inu_image__CtorParams,
   M_inu_cva_data__descriptor_t,
   M_inu_cva_data__CtorParams,
   M_inu_imu_data__chDescriptorT,
   M_inu_imu_data__descriptorT,
   M_inu_imu__CtorParams,
   M_inu_imu_data__CtorParams,
   M_inu_imu__temperatureParams,
   M_inu_temperature__CtorParams,
   M_inu_temperature_data__CtorParams,
   M_inu_soc_channel__CtorParams,
   M_inu_soc_channel__cropParamsT,
   M_inu_soc_channel__userParamsT,
   M_inu_isp_channel__CtorParams,
   M_inu_image__userInfoT,
   M_inu_cva_channel__CtorParams,
   M_inu_streamer__CtorParams,
   M_inu_sensor__resolution_t,
   M_inu_sensor__parameter_list_t,
   M_inu_sensor__CtorParams,
   M_inu_sensors_group__CtorParams,
   M_inu_fdk__CtorParams,
   M_inu_function__startParamsT,
   M_inu_function__stopParamsT,
   M_inu_data__hdr_t,
   M_inu_imu_data__hdr_t,
   M_inu_temperature_data__hdr_t,
   M_inu_image__hdr_t,
   M_inu_cva_data__hdr_t,
   M_inu_fast_orb_data__hdr_t,
   M_inu_cdnn_data__tailCevaFieldsT,
   M_inu_cdnn_data__tailSynopsysFieldsT,
   M_inu_cdnn_data__tailFieldsT,
   M_inu_cdnn_data__tailHeaderT,
   M_inu_cdnn_data__hdr_t,
   M_inu_slam_data__hdr_t,
   M_inu_tsnr_data__hdr_t,
   M_inu_point_cloud_data__hdr_t,
   M_inu_soc_writer__CtorParams,
   M_inu_histogram__CtorParams,
   M_inu_histogram_data__CtorParams,
   M_inu_histogram__roiT,
   M_inu_histogram_data__hdr_t,
   M_inu_histogram__roiCfgT,
   M_inu_sensor_control__CtorParams,
   M_inu_graph__send_config_db_params,
   M_inu_device__refListEntry,
   M_inu_device__refList,
   M_inu_fast_orb__CtorParams,
   M_inu_fast_orb_data__CtorParams,
   M_inu_cdnn__CtorParams,
   M_inu_cdnn_data__CtorParams,
   M_inu_cdnn__networkIdSetT,
   M_inu_vision_proc__CtorParams,
   M_StereoMatcherT,
   M_FrameMatcherT,
   M_KeyframesT,
   M_MapPointCullingT,
   M_KeyframeCullingT,
   M_TrackingT,
   M_LocalBundleAdjustmentT,
   M_LocalizationT,
   M_inu_slam__parameter_list_t,
   M_inu_slam__CtorParams,
   M_inu_slam_data__CtorParams,
   M_INUG_ioctlChainHdrT,
   M_inu_sensor_control__parameter_list_t,
   M_inu_tsnr_calc__parameter_list_t,
   M_inu_tsnr_calc__CtorParams,
   M_inu_tsnr_data__CtorParams,
   M_inu_point_cloud_data__CtorParams,
   M_inu_device__setflashSectionHdr,
   M_inu_compress__CtorParams,
   M_inu_load_network__CtorParams,
   M_inu_load_background__CtorParams,
   M_inu_dpe_pp__CtorParams,
   M_inu_pp__CtorParams,
   M_VISION_PROCG_bokehParamsT,
   M_VISION_PROCG_backgroundRemovalParamsT,
   M_VISION_PROCG_lowLightIspParamsT,
   M_VISION_PROCG_autoFramingParamsT,
   M_inu_pp__parameter_list_t,
   M_inu_device__selectTempSensor_t,
   M_inu_vision_proc__parameter_list_t,
   M_inu_isp_channel__commandT,
   M_inu_mipi_channel__CtorParams,
   M_inu_device__sensorSync,
   M_inu_device__sensorUpdateT,
   M_inu_metadata_injector__CtorParams,
   //Extended structures put to the end of the list
   M_inu_device__dphyRegT,
   M_inu_device__tempRegT,
   M_NUM_COMPOUND_TYPES_E,
   //builtin types
   M_FIRST_BUILTIN_TYPE_E = M_NUM_COMPOUND_TYPES_E,
   M_INT8 = M_FIRST_BUILTIN_TYPE_E,
   M_INT16,
   M_INT32,
   M_INT64,
   M_BPTR,
   M_LAST_BUILTIN_TYPE_E = M_INT64,
   M_NUM_TYPES_E,

   M_BUILTIN,
   M_INVALID_ENTRY = (~0),

} marshal_id_e;

#ifdef __cplusplus
}
#endif

#endif //_M_TBL_H_
