#ifndef NU4000_B0_SPI1_REG_H
#define NU4000_B0_SPI1_REG_H


/* types */
#include "defs.h"

#if !defined(PREFIX_VAL)
#define PREFIX_VAL *
#endif
 
#if !defined(SetGroupBits32) 
#define SetGroupBits32(reg,position,len,value)\
{       \
        UINT32 tmp=reg;\
        tmp&=~(((UINT32)0xFFFFFFFF>>(32-(len)))<<(position));\
        tmp|=((value&((UINT32)0xFFFFFFFF>>(32-(len))))<<(position));\
        reg=tmp;\
}
#endif

#if !defined(GetGroupBits32)
#define GetGroupBits32(reg,position,len) (((reg) & (((UINT32)0xFFFFFFFF>>(32-(len)))<<(position)))>>(position))
#endif


/*****************************************/
/*   SPI1 (Prototype: SPI)                */
/*****************************************/
#define SPI1_BASE 0x08048000

/* REGISTER: ISPI_CONFIGURATION */

#if defined(_V1) && !defined(ISPI_CONFIGURATION_OFFSET)
#define ISPI_CONFIGURATION_OFFSET 0x0
#endif

#if !defined(SPI_ISPI_CONFIGURATION_OFFSET)
#define SPI_ISPI_CONFIGURATION_OFFSET 0x0
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_REG)
#define ISPI_CONFIGURATION_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_CONFIGURATION_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_VAL)
#define ISPI_CONFIGURATION_VAL  PREFIX_VAL(ISPI_CONFIGURATION_REG)
#endif

#define SPI1_ISPI_CONFIGURATION_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_CONFIGURATION_OFFSET))
#define SPI1_ISPI_CONFIGURATION_VAL  PREFIX_VAL(SPI1_ISPI_CONFIGURATION_REG)

/* FIELDS: */

/* SPI_EN */

#ifndef SPI_ISPI_CONFIGURATION_SPI_EN_POS
#define SPI_ISPI_CONFIGURATION_SPI_EN_POS      0
#endif

#ifndef SPI_ISPI_CONFIGURATION_SPI_EN_LEN
#define SPI_ISPI_CONFIGURATION_SPI_EN_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_SPI_EN_R)
#define ISPI_CONFIGURATION_SPI_EN_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SPI_EN_POS, SPI_ISPI_CONFIGURATION_SPI_EN_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_SPI_EN_W)
#define ISPI_CONFIGURATION_SPI_EN_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SPI_EN_POS, SPI_ISPI_CONFIGURATION_SPI_EN_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_SPI_EN_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SPI_EN_POS, SPI_ISPI_CONFIGURATION_SPI_EN_LEN)

#define SPI1_ISPI_CONFIGURATION_SPI_EN_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SPI_EN_POS, SPI_ISPI_CONFIGURATION_SPI_EN_LEN,value)


/* TI_MODE */

#ifndef SPI_ISPI_CONFIGURATION_TI_MODE_POS
#define SPI_ISPI_CONFIGURATION_TI_MODE_POS      2
#endif

#ifndef SPI_ISPI_CONFIGURATION_TI_MODE_LEN
#define SPI_ISPI_CONFIGURATION_TI_MODE_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_TI_MODE_R)
#define ISPI_CONFIGURATION_TI_MODE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TI_MODE_POS, SPI_ISPI_CONFIGURATION_TI_MODE_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_TI_MODE_W)
#define ISPI_CONFIGURATION_TI_MODE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TI_MODE_POS, SPI_ISPI_CONFIGURATION_TI_MODE_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_TI_MODE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TI_MODE_POS, SPI_ISPI_CONFIGURATION_TI_MODE_LEN)

#define SPI1_ISPI_CONFIGURATION_TI_MODE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TI_MODE_POS, SPI_ISPI_CONFIGURATION_TI_MODE_LEN,value)


/* MASTER */

#ifndef SPI_ISPI_CONFIGURATION_MASTER_POS
#define SPI_ISPI_CONFIGURATION_MASTER_POS      3
#endif

#ifndef SPI_ISPI_CONFIGURATION_MASTER_LEN
#define SPI_ISPI_CONFIGURATION_MASTER_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_MASTER_R)
#define ISPI_CONFIGURATION_MASTER_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_MASTER_POS, SPI_ISPI_CONFIGURATION_MASTER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_MASTER_W)
#define ISPI_CONFIGURATION_MASTER_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_MASTER_POS, SPI_ISPI_CONFIGURATION_MASTER_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_MASTER_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_MASTER_POS, SPI_ISPI_CONFIGURATION_MASTER_LEN)

#define SPI1_ISPI_CONFIGURATION_MASTER_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_MASTER_POS, SPI_ISPI_CONFIGURATION_MASTER_LEN,value)


/* CLK_PHASE */

#ifndef SPI_ISPI_CONFIGURATION_CLK_PHASE_POS
#define SPI_ISPI_CONFIGURATION_CLK_PHASE_POS      4
#endif

#ifndef SPI_ISPI_CONFIGURATION_CLK_PHASE_LEN
#define SPI_ISPI_CONFIGURATION_CLK_PHASE_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CLK_PHASE_R)
#define ISPI_CONFIGURATION_CLK_PHASE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_PHASE_POS, SPI_ISPI_CONFIGURATION_CLK_PHASE_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CLK_PHASE_W)
#define ISPI_CONFIGURATION_CLK_PHASE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_PHASE_POS, SPI_ISPI_CONFIGURATION_CLK_PHASE_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_CLK_PHASE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_PHASE_POS, SPI_ISPI_CONFIGURATION_CLK_PHASE_LEN)

#define SPI1_ISPI_CONFIGURATION_CLK_PHASE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_PHASE_POS, SPI_ISPI_CONFIGURATION_CLK_PHASE_LEN,value)


/* CLK_POL */

#ifndef SPI_ISPI_CONFIGURATION_CLK_POL_POS
#define SPI_ISPI_CONFIGURATION_CLK_POL_POS      5
#endif

#ifndef SPI_ISPI_CONFIGURATION_CLK_POL_LEN
#define SPI_ISPI_CONFIGURATION_CLK_POL_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CLK_POL_R)
#define ISPI_CONFIGURATION_CLK_POL_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_POL_POS, SPI_ISPI_CONFIGURATION_CLK_POL_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CLK_POL_W)
#define ISPI_CONFIGURATION_CLK_POL_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_POL_POS, SPI_ISPI_CONFIGURATION_CLK_POL_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_CLK_POL_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_POL_POS, SPI_ISPI_CONFIGURATION_CLK_POL_LEN)

#define SPI1_ISPI_CONFIGURATION_CLK_POL_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_POL_POS, SPI_ISPI_CONFIGURATION_CLK_POL_LEN,value)


/* TX_PHASE */

#ifndef SPI_ISPI_CONFIGURATION_TX_PHASE_POS
#define SPI_ISPI_CONFIGURATION_TX_PHASE_POS      6
#endif

#ifndef SPI_ISPI_CONFIGURATION_TX_PHASE_LEN
#define SPI_ISPI_CONFIGURATION_TX_PHASE_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_TX_PHASE_R)
#define ISPI_CONFIGURATION_TX_PHASE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TX_PHASE_POS, SPI_ISPI_CONFIGURATION_TX_PHASE_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_TX_PHASE_W)
#define ISPI_CONFIGURATION_TX_PHASE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TX_PHASE_POS, SPI_ISPI_CONFIGURATION_TX_PHASE_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_TX_PHASE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TX_PHASE_POS, SPI_ISPI_CONFIGURATION_TX_PHASE_LEN)

#define SPI1_ISPI_CONFIGURATION_TX_PHASE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_TX_PHASE_POS, SPI_ISPI_CONFIGURATION_TX_PHASE_LEN,value)


/* RX_PHASE */

#ifndef SPI_ISPI_CONFIGURATION_RX_PHASE_POS
#define SPI_ISPI_CONFIGURATION_RX_PHASE_POS      7
#endif

#ifndef SPI_ISPI_CONFIGURATION_RX_PHASE_LEN
#define SPI_ISPI_CONFIGURATION_RX_PHASE_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_RX_PHASE_R)
#define ISPI_CONFIGURATION_RX_PHASE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_PHASE_POS, SPI_ISPI_CONFIGURATION_RX_PHASE_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_RX_PHASE_W)
#define ISPI_CONFIGURATION_RX_PHASE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_PHASE_POS, SPI_ISPI_CONFIGURATION_RX_PHASE_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_RX_PHASE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_PHASE_POS, SPI_ISPI_CONFIGURATION_RX_PHASE_LEN)

#define SPI1_ISPI_CONFIGURATION_RX_PHASE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_PHASE_POS, SPI_ISPI_CONFIGURATION_RX_PHASE_LEN,value)


/* SAMPLE_BITS */

#ifndef SPI_ISPI_CONFIGURATION_SAMPLE_BITS_POS
#define SPI_ISPI_CONFIGURATION_SAMPLE_BITS_POS      8
#endif

#ifndef SPI_ISPI_CONFIGURATION_SAMPLE_BITS_LEN
#define SPI_ISPI_CONFIGURATION_SAMPLE_BITS_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_SAMPLE_BITS_R)
#define ISPI_CONFIGURATION_SAMPLE_BITS_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SAMPLE_BITS_POS, SPI_ISPI_CONFIGURATION_SAMPLE_BITS_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_SAMPLE_BITS_W)
#define ISPI_CONFIGURATION_SAMPLE_BITS_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SAMPLE_BITS_POS, SPI_ISPI_CONFIGURATION_SAMPLE_BITS_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_SAMPLE_BITS_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SAMPLE_BITS_POS, SPI_ISPI_CONFIGURATION_SAMPLE_BITS_LEN)

#define SPI1_ISPI_CONFIGURATION_SAMPLE_BITS_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_SAMPLE_BITS_POS, SPI_ISPI_CONFIGURATION_SAMPLE_BITS_LEN,value)


/* CONST_OEN */

#ifndef SPI_ISPI_CONFIGURATION_CONST_OEN_POS
#define SPI_ISPI_CONFIGURATION_CONST_OEN_POS      10
#endif

#ifndef SPI_ISPI_CONFIGURATION_CONST_OEN_LEN
#define SPI_ISPI_CONFIGURATION_CONST_OEN_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CONST_OEN_R)
#define ISPI_CONFIGURATION_CONST_OEN_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CONST_OEN_POS, SPI_ISPI_CONFIGURATION_CONST_OEN_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CONST_OEN_W)
#define ISPI_CONFIGURATION_CONST_OEN_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CONST_OEN_POS, SPI_ISPI_CONFIGURATION_CONST_OEN_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_CONST_OEN_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CONST_OEN_POS, SPI_ISPI_CONFIGURATION_CONST_OEN_LEN)

#define SPI1_ISPI_CONFIGURATION_CONST_OEN_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CONST_OEN_POS, SPI_ISPI_CONFIGURATION_CONST_OEN_LEN,value)


/* FIFO_PACK */

#ifndef SPI_ISPI_CONFIGURATION_FIFO_PACK_POS
#define SPI_ISPI_CONFIGURATION_FIFO_PACK_POS      11
#endif

#ifndef SPI_ISPI_CONFIGURATION_FIFO_PACK_LEN
#define SPI_ISPI_CONFIGURATION_FIFO_PACK_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_FIFO_PACK_R)
#define ISPI_CONFIGURATION_FIFO_PACK_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_FIFO_PACK_POS, SPI_ISPI_CONFIGURATION_FIFO_PACK_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_FIFO_PACK_W)
#define ISPI_CONFIGURATION_FIFO_PACK_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_FIFO_PACK_POS, SPI_ISPI_CONFIGURATION_FIFO_PACK_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_FIFO_PACK_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_FIFO_PACK_POS, SPI_ISPI_CONFIGURATION_FIFO_PACK_LEN)

#define SPI1_ISPI_CONFIGURATION_FIFO_PACK_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_FIFO_PACK_POS, SPI_ISPI_CONFIGURATION_FIFO_PACK_LEN,value)


/* LSB_FIRST */

#ifndef SPI_ISPI_CONFIGURATION_LSB_FIRST_POS
#define SPI_ISPI_CONFIGURATION_LSB_FIRST_POS      12
#endif

#ifndef SPI_ISPI_CONFIGURATION_LSB_FIRST_LEN
#define SPI_ISPI_CONFIGURATION_LSB_FIRST_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_LSB_FIRST_R)
#define ISPI_CONFIGURATION_LSB_FIRST_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_LSB_FIRST_POS, SPI_ISPI_CONFIGURATION_LSB_FIRST_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_LSB_FIRST_W)
#define ISPI_CONFIGURATION_LSB_FIRST_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_LSB_FIRST_POS, SPI_ISPI_CONFIGURATION_LSB_FIRST_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_LSB_FIRST_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_LSB_FIRST_POS, SPI_ISPI_CONFIGURATION_LSB_FIRST_LEN)

#define SPI1_ISPI_CONFIGURATION_LSB_FIRST_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_LSB_FIRST_POS, SPI_ISPI_CONFIGURATION_LSB_FIRST_LEN,value)


/* RX_MODE */

#ifndef SPI_ISPI_CONFIGURATION_RX_MODE_POS
#define SPI_ISPI_CONFIGURATION_RX_MODE_POS      13
#endif

#ifndef SPI_ISPI_CONFIGURATION_RX_MODE_LEN
#define SPI_ISPI_CONFIGURATION_RX_MODE_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_RX_MODE_R)
#define ISPI_CONFIGURATION_RX_MODE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_MODE_POS, SPI_ISPI_CONFIGURATION_RX_MODE_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_RX_MODE_W)
#define ISPI_CONFIGURATION_RX_MODE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_MODE_POS, SPI_ISPI_CONFIGURATION_RX_MODE_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_RX_MODE_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_MODE_POS, SPI_ISPI_CONFIGURATION_RX_MODE_LEN)

#define SPI1_ISPI_CONFIGURATION_RX_MODE_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_RX_MODE_POS, SPI_ISPI_CONFIGURATION_RX_MODE_LEN,value)


/* CLK_DIV */

#ifndef SPI_ISPI_CONFIGURATION_CLK_DIV_POS
#define SPI_ISPI_CONFIGURATION_CLK_DIV_POS      24
#endif

#ifndef SPI_ISPI_CONFIGURATION_CLK_DIV_LEN
#define SPI_ISPI_CONFIGURATION_CLK_DIV_LEN      8
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CLK_DIV_R)
#define ISPI_CONFIGURATION_CLK_DIV_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_DIV_POS, SPI_ISPI_CONFIGURATION_CLK_DIV_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CONFIGURATION_CLK_DIV_W)
#define ISPI_CONFIGURATION_CLK_DIV_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_DIV_POS, SPI_ISPI_CONFIGURATION_CLK_DIV_LEN,value)
#endif

#define SPI1_ISPI_CONFIGURATION_CLK_DIV_R        GetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_DIV_POS, SPI_ISPI_CONFIGURATION_CLK_DIV_LEN)

#define SPI1_ISPI_CONFIGURATION_CLK_DIV_W(value) SetGroupBits32( (SPI1_ISPI_CONFIGURATION_VAL),SPI_ISPI_CONFIGURATION_CLK_DIV_POS, SPI_ISPI_CONFIGURATION_CLK_DIV_LEN,value)


/* REGISTER: ISPI_INT_RAW */

#if defined(_V1) && !defined(ISPI_INT_RAW_OFFSET)
#define ISPI_INT_RAW_OFFSET 0x10
#endif

#if !defined(SPI_ISPI_INT_RAW_OFFSET)
#define SPI_ISPI_INT_RAW_OFFSET 0x10
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_REG)
#define ISPI_INT_RAW_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_INT_RAW_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_VAL)
#define ISPI_INT_RAW_VAL  PREFIX_VAL(ISPI_INT_RAW_REG)
#endif

#define SPI1_ISPI_INT_RAW_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_INT_RAW_OFFSET))
#define SPI1_ISPI_INT_RAW_VAL  PREFIX_VAL(SPI1_ISPI_INT_RAW_REG)

/* FIELDS: */

/* INT_RAW_RX_OVER */

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_POS
#define SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_POS      0
#endif

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_LEN
#define SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_OVER_R)
#define ISPI_INT_RAW_INT_RAW_RX_OVER_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_OVER_W)
#define ISPI_INT_RAW_INT_RAW_RX_OVER_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_LEN,value)
#endif

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_OVER_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_LEN)

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_OVER_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_OVER_LEN,value)


/* INT_RAW_TX_UNDER */

#ifndef SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_POS
#define SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_POS      1
#endif

#ifndef SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_LEN
#define SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_TX_UNDER_R)
#define ISPI_INT_RAW_INT_RAW_TX_UNDER_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_TX_UNDER_W)
#define ISPI_INT_RAW_INT_RAW_TX_UNDER_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_LEN,value)
#endif

#define SPI1_ISPI_INT_RAW_INT_RAW_TX_UNDER_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_LEN)

#define SPI1_ISPI_INT_RAW_INT_RAW_TX_UNDER_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_UNDER_LEN,value)


/* INT_RAW_RX_THR */

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_THR_POS
#define SPI_ISPI_INT_RAW_INT_RAW_RX_THR_POS      2
#endif

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_THR_LEN
#define SPI_ISPI_INT_RAW_INT_RAW_RX_THR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_THR_R)
#define ISPI_INT_RAW_INT_RAW_RX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_THR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_THR_W)
#define ISPI_INT_RAW_INT_RAW_RX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_THR_LEN,value)
#endif

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_THR_LEN)

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_THR_LEN,value)


/* INT_RAW_TX_THR */

#ifndef SPI_ISPI_INT_RAW_INT_RAW_TX_THR_POS
#define SPI_ISPI_INT_RAW_INT_RAW_TX_THR_POS      3
#endif

#ifndef SPI_ISPI_INT_RAW_INT_RAW_TX_THR_LEN
#define SPI_ISPI_INT_RAW_INT_RAW_TX_THR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_TX_THR_R)
#define ISPI_INT_RAW_INT_RAW_TX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_THR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_TX_THR_W)
#define ISPI_INT_RAW_INT_RAW_TX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_THR_LEN,value)
#endif

#define SPI1_ISPI_INT_RAW_INT_RAW_TX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_THR_LEN)

#define SPI1_ISPI_INT_RAW_INT_RAW_TX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_TX_THR_POS, SPI_ISPI_INT_RAW_INT_RAW_TX_THR_LEN,value)


/* INT_RAW_RX_TIME */

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_POS
#define SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_POS      4
#endif

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_LEN
#define SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_TIME_R)
#define ISPI_INT_RAW_INT_RAW_RX_TIME_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_TIME_W)
#define ISPI_INT_RAW_INT_RAW_RX_TIME_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_LEN,value)
#endif

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_TIME_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_LEN)

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_TIME_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_LEN,value)


/* INT_RAW_RX_TIME_CUR */

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_POS
#define SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_POS      5
#endif

#ifndef SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_LEN
#define SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_R)
#define ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_W)
#define ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_LEN,value)
#endif

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_R        GetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_LEN)

#define SPI1_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_W(value) SetGroupBits32( (SPI1_ISPI_INT_RAW_VAL),SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_POS, SPI_ISPI_INT_RAW_INT_RAW_RX_TIME_CUR_LEN,value)


/* REGISTER: ISPI_INT_EN */

#if defined(_V1) && !defined(ISPI_INT_EN_OFFSET)
#define ISPI_INT_EN_OFFSET 0x14
#endif

#if !defined(SPI_ISPI_INT_EN_OFFSET)
#define SPI_ISPI_INT_EN_OFFSET 0x14
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_REG)
#define ISPI_INT_EN_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_INT_EN_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_VAL)
#define ISPI_INT_EN_VAL  PREFIX_VAL(ISPI_INT_EN_REG)
#endif

#define SPI1_ISPI_INT_EN_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_INT_EN_OFFSET))
#define SPI1_ISPI_INT_EN_VAL  PREFIX_VAL(SPI1_ISPI_INT_EN_REG)

/* FIELDS: */

/* INT_EN_RX_OVER */

#ifndef SPI_ISPI_INT_EN_INT_EN_RX_OVER_POS
#define SPI_ISPI_INT_EN_INT_EN_RX_OVER_POS      0
#endif

#ifndef SPI_ISPI_INT_EN_INT_EN_RX_OVER_LEN
#define SPI_ISPI_INT_EN_INT_EN_RX_OVER_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_RX_OVER_R)
#define ISPI_INT_EN_INT_EN_RX_OVER_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_OVER_POS, SPI_ISPI_INT_EN_INT_EN_RX_OVER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_RX_OVER_W)
#define ISPI_INT_EN_INT_EN_RX_OVER_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_OVER_POS, SPI_ISPI_INT_EN_INT_EN_RX_OVER_LEN,value)
#endif

#define SPI1_ISPI_INT_EN_INT_EN_RX_OVER_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_OVER_POS, SPI_ISPI_INT_EN_INT_EN_RX_OVER_LEN)

#define SPI1_ISPI_INT_EN_INT_EN_RX_OVER_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_OVER_POS, SPI_ISPI_INT_EN_INT_EN_RX_OVER_LEN,value)


/* INT_EN_TX_UNDER */

#ifndef SPI_ISPI_INT_EN_INT_EN_TX_UNDER_POS
#define SPI_ISPI_INT_EN_INT_EN_TX_UNDER_POS      1
#endif

#ifndef SPI_ISPI_INT_EN_INT_EN_TX_UNDER_LEN
#define SPI_ISPI_INT_EN_INT_EN_TX_UNDER_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_TX_UNDER_R)
#define ISPI_INT_EN_INT_EN_TX_UNDER_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_UNDER_POS, SPI_ISPI_INT_EN_INT_EN_TX_UNDER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_TX_UNDER_W)
#define ISPI_INT_EN_INT_EN_TX_UNDER_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_UNDER_POS, SPI_ISPI_INT_EN_INT_EN_TX_UNDER_LEN,value)
#endif

#define SPI1_ISPI_INT_EN_INT_EN_TX_UNDER_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_UNDER_POS, SPI_ISPI_INT_EN_INT_EN_TX_UNDER_LEN)

#define SPI1_ISPI_INT_EN_INT_EN_TX_UNDER_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_UNDER_POS, SPI_ISPI_INT_EN_INT_EN_TX_UNDER_LEN,value)


/* INT_EN_RX_THR */

#ifndef SPI_ISPI_INT_EN_INT_EN_RX_THR_POS
#define SPI_ISPI_INT_EN_INT_EN_RX_THR_POS      2
#endif

#ifndef SPI_ISPI_INT_EN_INT_EN_RX_THR_LEN
#define SPI_ISPI_INT_EN_INT_EN_RX_THR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_RX_THR_R)
#define ISPI_INT_EN_INT_EN_RX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_THR_POS, SPI_ISPI_INT_EN_INT_EN_RX_THR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_RX_THR_W)
#define ISPI_INT_EN_INT_EN_RX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_THR_POS, SPI_ISPI_INT_EN_INT_EN_RX_THR_LEN,value)
#endif

#define SPI1_ISPI_INT_EN_INT_EN_RX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_THR_POS, SPI_ISPI_INT_EN_INT_EN_RX_THR_LEN)

#define SPI1_ISPI_INT_EN_INT_EN_RX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_THR_POS, SPI_ISPI_INT_EN_INT_EN_RX_THR_LEN,value)


/* INT_EN_TX_THR */

#ifndef SPI_ISPI_INT_EN_INT_EN_TX_THR_POS
#define SPI_ISPI_INT_EN_INT_EN_TX_THR_POS      3
#endif

#ifndef SPI_ISPI_INT_EN_INT_EN_TX_THR_LEN
#define SPI_ISPI_INT_EN_INT_EN_TX_THR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_TX_THR_R)
#define ISPI_INT_EN_INT_EN_TX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_THR_POS, SPI_ISPI_INT_EN_INT_EN_TX_THR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_TX_THR_W)
#define ISPI_INT_EN_INT_EN_TX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_THR_POS, SPI_ISPI_INT_EN_INT_EN_TX_THR_LEN,value)
#endif

#define SPI1_ISPI_INT_EN_INT_EN_TX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_THR_POS, SPI_ISPI_INT_EN_INT_EN_TX_THR_LEN)

#define SPI1_ISPI_INT_EN_INT_EN_TX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_TX_THR_POS, SPI_ISPI_INT_EN_INT_EN_TX_THR_LEN,value)


/* INT_EN_RX_TIME */

#ifndef SPI_ISPI_INT_EN_INT_EN_RX_TIME_POS
#define SPI_ISPI_INT_EN_INT_EN_RX_TIME_POS      4
#endif

#ifndef SPI_ISPI_INT_EN_INT_EN_RX_TIME_LEN
#define SPI_ISPI_INT_EN_INT_EN_RX_TIME_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_RX_TIME_R)
#define ISPI_INT_EN_INT_EN_RX_TIME_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_TIME_POS, SPI_ISPI_INT_EN_INT_EN_RX_TIME_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_EN_INT_EN_RX_TIME_W)
#define ISPI_INT_EN_INT_EN_RX_TIME_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_TIME_POS, SPI_ISPI_INT_EN_INT_EN_RX_TIME_LEN,value)
#endif

#define SPI1_ISPI_INT_EN_INT_EN_RX_TIME_R        GetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_TIME_POS, SPI_ISPI_INT_EN_INT_EN_RX_TIME_LEN)

#define SPI1_ISPI_INT_EN_INT_EN_RX_TIME_W(value) SetGroupBits32( (SPI1_ISPI_INT_EN_VAL),SPI_ISPI_INT_EN_INT_EN_RX_TIME_POS, SPI_ISPI_INT_EN_INT_EN_RX_TIME_LEN,value)


/* REGISTER: ISPI_INT_STAT */

#if defined(_V1) && !defined(ISPI_INT_STAT_OFFSET)
#define ISPI_INT_STAT_OFFSET 0x18
#endif

#if !defined(SPI_ISPI_INT_STAT_OFFSET)
#define SPI_ISPI_INT_STAT_OFFSET 0x18
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_REG)
#define ISPI_INT_STAT_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_INT_STAT_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_VAL)
#define ISPI_INT_STAT_VAL  PREFIX_VAL(ISPI_INT_STAT_REG)
#endif

#define SPI1_ISPI_INT_STAT_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_INT_STAT_OFFSET))
#define SPI1_ISPI_INT_STAT_VAL  PREFIX_VAL(SPI1_ISPI_INT_STAT_REG)

/* FIELDS: */

/* INT_RX_OVER */

#ifndef SPI_ISPI_INT_STAT_INT_RX_OVER_POS
#define SPI_ISPI_INT_STAT_INT_RX_OVER_POS      0
#endif

#ifndef SPI_ISPI_INT_STAT_INT_RX_OVER_LEN
#define SPI_ISPI_INT_STAT_INT_RX_OVER_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_OVER_R)
#define ISPI_INT_STAT_INT_RX_OVER_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_OVER_POS, SPI_ISPI_INT_STAT_INT_RX_OVER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_OVER_W)
#define ISPI_INT_STAT_INT_RX_OVER_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_OVER_POS, SPI_ISPI_INT_STAT_INT_RX_OVER_LEN,value)
#endif

#define SPI1_ISPI_INT_STAT_INT_RX_OVER_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_OVER_POS, SPI_ISPI_INT_STAT_INT_RX_OVER_LEN)

#define SPI1_ISPI_INT_STAT_INT_RX_OVER_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_OVER_POS, SPI_ISPI_INT_STAT_INT_RX_OVER_LEN,value)


/* INT_TX_UNDER */

#ifndef SPI_ISPI_INT_STAT_INT_TX_UNDER_POS
#define SPI_ISPI_INT_STAT_INT_TX_UNDER_POS      1
#endif

#ifndef SPI_ISPI_INT_STAT_INT_TX_UNDER_LEN
#define SPI_ISPI_INT_STAT_INT_TX_UNDER_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_TX_UNDER_R)
#define ISPI_INT_STAT_INT_TX_UNDER_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_UNDER_POS, SPI_ISPI_INT_STAT_INT_TX_UNDER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_TX_UNDER_W)
#define ISPI_INT_STAT_INT_TX_UNDER_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_UNDER_POS, SPI_ISPI_INT_STAT_INT_TX_UNDER_LEN,value)
#endif

#define SPI1_ISPI_INT_STAT_INT_TX_UNDER_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_UNDER_POS, SPI_ISPI_INT_STAT_INT_TX_UNDER_LEN)

#define SPI1_ISPI_INT_STAT_INT_TX_UNDER_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_UNDER_POS, SPI_ISPI_INT_STAT_INT_TX_UNDER_LEN,value)


/* INT_RX_THR */

#ifndef SPI_ISPI_INT_STAT_INT_RX_THR_POS
#define SPI_ISPI_INT_STAT_INT_RX_THR_POS      2
#endif

#ifndef SPI_ISPI_INT_STAT_INT_RX_THR_LEN
#define SPI_ISPI_INT_STAT_INT_RX_THR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_THR_R)
#define ISPI_INT_STAT_INT_RX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_THR_POS, SPI_ISPI_INT_STAT_INT_RX_THR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_THR_W)
#define ISPI_INT_STAT_INT_RX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_THR_POS, SPI_ISPI_INT_STAT_INT_RX_THR_LEN,value)
#endif

#define SPI1_ISPI_INT_STAT_INT_RX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_THR_POS, SPI_ISPI_INT_STAT_INT_RX_THR_LEN)

#define SPI1_ISPI_INT_STAT_INT_RX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_THR_POS, SPI_ISPI_INT_STAT_INT_RX_THR_LEN,value)


/* INT_TX_THR */

#ifndef SPI_ISPI_INT_STAT_INT_TX_THR_POS
#define SPI_ISPI_INT_STAT_INT_TX_THR_POS      3
#endif

#ifndef SPI_ISPI_INT_STAT_INT_TX_THR_LEN
#define SPI_ISPI_INT_STAT_INT_TX_THR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_TX_THR_R)
#define ISPI_INT_STAT_INT_TX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_THR_POS, SPI_ISPI_INT_STAT_INT_TX_THR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_TX_THR_W)
#define ISPI_INT_STAT_INT_TX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_THR_POS, SPI_ISPI_INT_STAT_INT_TX_THR_LEN,value)
#endif

#define SPI1_ISPI_INT_STAT_INT_TX_THR_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_THR_POS, SPI_ISPI_INT_STAT_INT_TX_THR_LEN)

#define SPI1_ISPI_INT_STAT_INT_TX_THR_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_TX_THR_POS, SPI_ISPI_INT_STAT_INT_TX_THR_LEN,value)


/* INT_RX_TIME */

#ifndef SPI_ISPI_INT_STAT_INT_RX_TIME_POS
#define SPI_ISPI_INT_STAT_INT_RX_TIME_POS      4
#endif

#ifndef SPI_ISPI_INT_STAT_INT_RX_TIME_LEN
#define SPI_ISPI_INT_STAT_INT_RX_TIME_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_TIME_R)
#define ISPI_INT_STAT_INT_RX_TIME_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_TIME_W)
#define ISPI_INT_STAT_INT_RX_TIME_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_LEN,value)
#endif

#define SPI1_ISPI_INT_STAT_INT_RX_TIME_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_LEN)

#define SPI1_ISPI_INT_STAT_INT_RX_TIME_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_LEN,value)


/* INT_RX_TIME_CUR */

#ifndef SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_POS
#define SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_POS      5
#endif

#ifndef SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_LEN
#define SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_TIME_CUR_R)
#define ISPI_INT_STAT_INT_RX_TIME_CUR_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_LEN)
#endif

#if defined(_V1) && !defined(ISPI_INT_STAT_INT_RX_TIME_CUR_W)
#define ISPI_INT_STAT_INT_RX_TIME_CUR_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_LEN,value)
#endif

#define SPI1_ISPI_INT_STAT_INT_RX_TIME_CUR_R        GetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_LEN)

#define SPI1_ISPI_INT_STAT_INT_RX_TIME_CUR_W(value) SetGroupBits32( (SPI1_ISPI_INT_STAT_VAL),SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_POS, SPI_ISPI_INT_STAT_INT_RX_TIME_CUR_LEN,value)


/* REGISTER: ISPI_RX_TIMER */

#if defined(_V1) && !defined(ISPI_RX_TIMER_OFFSET)
#define ISPI_RX_TIMER_OFFSET 0x1c
#endif

#if !defined(SPI_ISPI_RX_TIMER_OFFSET)
#define SPI_ISPI_RX_TIMER_OFFSET 0x1c
#endif

#if defined(_V1) && !defined(ISPI_RX_TIMER_REG)
#define ISPI_RX_TIMER_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_RX_TIMER_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_RX_TIMER_VAL)
#define ISPI_RX_TIMER_VAL  PREFIX_VAL(ISPI_RX_TIMER_REG)
#endif

#define SPI1_ISPI_RX_TIMER_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_RX_TIMER_OFFSET))
#define SPI1_ISPI_RX_TIMER_VAL  PREFIX_VAL(SPI1_ISPI_RX_TIMER_REG)

/* FIELDS: */

/* RX_TIMEOUT */

#ifndef SPI_ISPI_RX_TIMER_RX_TIMEOUT_POS
#define SPI_ISPI_RX_TIMER_RX_TIMEOUT_POS      0
#endif

#ifndef SPI_ISPI_RX_TIMER_RX_TIMEOUT_LEN
#define SPI_ISPI_RX_TIMER_RX_TIMEOUT_LEN      8
#endif

#if defined(_V1) && !defined(ISPI_RX_TIMER_RX_TIMEOUT_R)
#define ISPI_RX_TIMER_RX_TIMEOUT_R        GetGroupBits32( (SPI1_ISPI_RX_TIMER_VAL),SPI_ISPI_RX_TIMER_RX_TIMEOUT_POS, SPI_ISPI_RX_TIMER_RX_TIMEOUT_LEN)
#endif

#if defined(_V1) && !defined(ISPI_RX_TIMER_RX_TIMEOUT_W)
#define ISPI_RX_TIMER_RX_TIMEOUT_W(value) SetGroupBits32( (SPI1_ISPI_RX_TIMER_VAL),SPI_ISPI_RX_TIMER_RX_TIMEOUT_POS, SPI_ISPI_RX_TIMER_RX_TIMEOUT_LEN,value)
#endif

#define SPI1_ISPI_RX_TIMER_RX_TIMEOUT_R        GetGroupBits32( (SPI1_ISPI_RX_TIMER_VAL),SPI_ISPI_RX_TIMER_RX_TIMEOUT_POS, SPI_ISPI_RX_TIMER_RX_TIMEOUT_LEN)

#define SPI1_ISPI_RX_TIMER_RX_TIMEOUT_W(value) SetGroupBits32( (SPI1_ISPI_RX_TIMER_VAL),SPI_ISPI_RX_TIMER_RX_TIMEOUT_POS, SPI_ISPI_RX_TIMER_RX_TIMEOUT_LEN,value)


/* REGISTER: ISPI_STATUS */

#if defined(_V1) && !defined(ISPI_STATUS_OFFSET)
#define ISPI_STATUS_OFFSET 0x20
#endif

#if !defined(SPI_ISPI_STATUS_OFFSET)
#define SPI_ISPI_STATUS_OFFSET 0x20
#endif

#if defined(_V1) && !defined(ISPI_STATUS_REG)
#define ISPI_STATUS_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_STATUS_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_STATUS_VAL)
#define ISPI_STATUS_VAL  PREFIX_VAL(ISPI_STATUS_REG)
#endif

#define SPI1_ISPI_STATUS_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_STATUS_OFFSET))
#define SPI1_ISPI_STATUS_VAL  PREFIX_VAL(SPI1_ISPI_STATUS_REG)

/* FIELDS: */

/* RX_ENTRIES */

#ifndef SPI_ISPI_STATUS_RX_ENTRIES_POS
#define SPI_ISPI_STATUS_RX_ENTRIES_POS      0
#endif

#ifndef SPI_ISPI_STATUS_RX_ENTRIES_LEN
#define SPI_ISPI_STATUS_RX_ENTRIES_LEN      7
#endif

#if defined(_V1) && !defined(ISPI_STATUS_RX_ENTRIES_R)
#define ISPI_STATUS_RX_ENTRIES_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_RX_ENTRIES_POS, SPI_ISPI_STATUS_RX_ENTRIES_LEN)
#endif

#if defined(_V1) && !defined(ISPI_STATUS_RX_ENTRIES_W)
#define ISPI_STATUS_RX_ENTRIES_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_RX_ENTRIES_POS, SPI_ISPI_STATUS_RX_ENTRIES_LEN,value)
#endif

#define SPI1_ISPI_STATUS_RX_ENTRIES_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_RX_ENTRIES_POS, SPI_ISPI_STATUS_RX_ENTRIES_LEN)

#define SPI1_ISPI_STATUS_RX_ENTRIES_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_RX_ENTRIES_POS, SPI_ISPI_STATUS_RX_ENTRIES_LEN,value)


/* FILTER */

#ifndef SPI_ISPI_STATUS_FILTER_POS
#define SPI_ISPI_STATUS_FILTER_POS      14
#endif

#ifndef SPI_ISPI_STATUS_FILTER_LEN
#define SPI_ISPI_STATUS_FILTER_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_STATUS_FILTER_R)
#define ISPI_STATUS_FILTER_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_FILTER_POS, SPI_ISPI_STATUS_FILTER_LEN)
#endif

#if defined(_V1) && !defined(ISPI_STATUS_FILTER_W)
#define ISPI_STATUS_FILTER_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_FILTER_POS, SPI_ISPI_STATUS_FILTER_LEN,value)
#endif

#define SPI1_ISPI_STATUS_FILTER_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_FILTER_POS, SPI_ISPI_STATUS_FILTER_LEN)

#define SPI1_ISPI_STATUS_FILTER_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_FILTER_POS, SPI_ISPI_STATUS_FILTER_LEN,value)


/* TX_ENTRIES */

#ifndef SPI_ISPI_STATUS_TX_ENTRIES_POS
#define SPI_ISPI_STATUS_TX_ENTRIES_POS      16
#endif

#ifndef SPI_ISPI_STATUS_TX_ENTRIES_LEN
#define SPI_ISPI_STATUS_TX_ENTRIES_LEN      7
#endif

#if defined(_V1) && !defined(ISPI_STATUS_TX_ENTRIES_R)
#define ISPI_STATUS_TX_ENTRIES_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_TX_ENTRIES_POS, SPI_ISPI_STATUS_TX_ENTRIES_LEN)
#endif

#if defined(_V1) && !defined(ISPI_STATUS_TX_ENTRIES_W)
#define ISPI_STATUS_TX_ENTRIES_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_TX_ENTRIES_POS, SPI_ISPI_STATUS_TX_ENTRIES_LEN,value)
#endif

#define SPI1_ISPI_STATUS_TX_ENTRIES_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_TX_ENTRIES_POS, SPI_ISPI_STATUS_TX_ENTRIES_LEN)

#define SPI1_ISPI_STATUS_TX_ENTRIES_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_TX_ENTRIES_POS, SPI_ISPI_STATUS_TX_ENTRIES_LEN,value)


/* SPI_BUSY */

#ifndef SPI_ISPI_STATUS_SPI_BUSY_POS
#define SPI_ISPI_STATUS_SPI_BUSY_POS      31
#endif

#ifndef SPI_ISPI_STATUS_SPI_BUSY_LEN
#define SPI_ISPI_STATUS_SPI_BUSY_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_STATUS_SPI_BUSY_R)
#define ISPI_STATUS_SPI_BUSY_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_SPI_BUSY_POS, SPI_ISPI_STATUS_SPI_BUSY_LEN)
#endif

#if defined(_V1) && !defined(ISPI_STATUS_SPI_BUSY_W)
#define ISPI_STATUS_SPI_BUSY_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_SPI_BUSY_POS, SPI_ISPI_STATUS_SPI_BUSY_LEN,value)
#endif

#define SPI1_ISPI_STATUS_SPI_BUSY_R        GetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_SPI_BUSY_POS, SPI_ISPI_STATUS_SPI_BUSY_LEN)

#define SPI1_ISPI_STATUS_SPI_BUSY_W(value) SetGroupBits32( (SPI1_ISPI_STATUS_VAL),SPI_ISPI_STATUS_SPI_BUSY_POS, SPI_ISPI_STATUS_SPI_BUSY_LEN,value)


/* REGISTER: ISPI_CS */

#if defined(_V1) && !defined(ISPI_CS_OFFSET)
#define ISPI_CS_OFFSET 0x24
#endif

#if !defined(SPI_ISPI_CS_OFFSET)
#define SPI_ISPI_CS_OFFSET 0x24
#endif

#if defined(_V1) && !defined(ISPI_CS_REG)
#define ISPI_CS_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_CS_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_CS_VAL)
#define ISPI_CS_VAL  PREFIX_VAL(ISPI_CS_REG)
#endif

#define SPI1_ISPI_CS_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_CS_OFFSET))
#define SPI1_ISPI_CS_VAL  PREFIX_VAL(SPI1_ISPI_CS_REG)

/* FIELDS: */

/* CS_EN */

#ifndef SPI_ISPI_CS_CS_EN_POS
#define SPI_ISPI_CS_CS_EN_POS      0
#endif

#ifndef SPI_ISPI_CS_CS_EN_LEN
#define SPI_ISPI_CS_CS_EN_LEN      4
#endif

#if defined(_V1) && !defined(ISPI_CS_CS_EN_R)
#define ISPI_CS_CS_EN_R        GetGroupBits32( (SPI1_ISPI_CS_VAL),SPI_ISPI_CS_CS_EN_POS, SPI_ISPI_CS_CS_EN_LEN)
#endif

#if defined(_V1) && !defined(ISPI_CS_CS_EN_W)
#define ISPI_CS_CS_EN_W(value) SetGroupBits32( (SPI1_ISPI_CS_VAL),SPI_ISPI_CS_CS_EN_POS, SPI_ISPI_CS_CS_EN_LEN,value)
#endif

#define SPI1_ISPI_CS_CS_EN_R        GetGroupBits32( (SPI1_ISPI_CS_VAL),SPI_ISPI_CS_CS_EN_POS, SPI_ISPI_CS_CS_EN_LEN)

#define SPI1_ISPI_CS_CS_EN_W(value) SetGroupBits32( (SPI1_ISPI_CS_VAL),SPI_ISPI_CS_CS_EN_POS, SPI_ISPI_CS_CS_EN_LEN,value)


/* REGISTER: ISPI_FILTER */

#if defined(_V1) && !defined(ISPI_FILTER_OFFSET)
#define ISPI_FILTER_OFFSET 0x28
#endif

#if !defined(SPI_ISPI_FILTER_OFFSET)
#define SPI_ISPI_FILTER_OFFSET 0x28
#endif

#if defined(_V1) && !defined(ISPI_FILTER_REG)
#define ISPI_FILTER_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_FILTER_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_FILTER_VAL)
#define ISPI_FILTER_VAL  PREFIX_VAL(ISPI_FILTER_REG)
#endif

#define SPI1_ISPI_FILTER_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_FILTER_OFFSET))
#define SPI1_ISPI_FILTER_VAL  PREFIX_VAL(SPI1_ISPI_FILTER_REG)

/* FIELDS: */

/* FILTER_MODE */

#ifndef SPI_ISPI_FILTER_FILTER_MODE_POS
#define SPI_ISPI_FILTER_FILTER_MODE_POS      0
#endif

#ifndef SPI_ISPI_FILTER_FILTER_MODE_LEN
#define SPI_ISPI_FILTER_FILTER_MODE_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_FILTER_FILTER_MODE_R)
#define ISPI_FILTER_FILTER_MODE_R        GetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_MODE_POS, SPI_ISPI_FILTER_FILTER_MODE_LEN)
#endif

#if defined(_V1) && !defined(ISPI_FILTER_FILTER_MODE_W)
#define ISPI_FILTER_FILTER_MODE_W(value) SetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_MODE_POS, SPI_ISPI_FILTER_FILTER_MODE_LEN,value)
#endif

#define SPI1_ISPI_FILTER_FILTER_MODE_R        GetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_MODE_POS, SPI_ISPI_FILTER_FILTER_MODE_LEN)

#define SPI1_ISPI_FILTER_FILTER_MODE_W(value) SetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_MODE_POS, SPI_ISPI_FILTER_FILTER_MODE_LEN,value)


/* FILTER_PACKET */

#ifndef SPI_ISPI_FILTER_FILTER_PACKET_POS
#define SPI_ISPI_FILTER_FILTER_PACKET_POS      4
#endif

#ifndef SPI_ISPI_FILTER_FILTER_PACKET_LEN
#define SPI_ISPI_FILTER_FILTER_PACKET_LEN      4
#endif

#if defined(_V1) && !defined(ISPI_FILTER_FILTER_PACKET_R)
#define ISPI_FILTER_FILTER_PACKET_R        GetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_PACKET_POS, SPI_ISPI_FILTER_FILTER_PACKET_LEN)
#endif

#if defined(_V1) && !defined(ISPI_FILTER_FILTER_PACKET_W)
#define ISPI_FILTER_FILTER_PACKET_W(value) SetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_PACKET_POS, SPI_ISPI_FILTER_FILTER_PACKET_LEN,value)
#endif

#define SPI1_ISPI_FILTER_FILTER_PACKET_R        GetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_PACKET_POS, SPI_ISPI_FILTER_FILTER_PACKET_LEN)

#define SPI1_ISPI_FILTER_FILTER_PACKET_W(value) SetGroupBits32( (SPI1_ISPI_FILTER_VAL),SPI_ISPI_FILTER_FILTER_PACKET_POS, SPI_ISPI_FILTER_FILTER_PACKET_LEN,value)


/* REGISTER: ISPI_FILTER_PATTERN */

#if defined(_V1) && !defined(ISPI_FILTER_PATTERN_OFFSET)
#define ISPI_FILTER_PATTERN_OFFSET 0x2c
#endif

#if !defined(SPI_ISPI_FILTER_PATTERN_OFFSET)
#define SPI_ISPI_FILTER_PATTERN_OFFSET 0x2c
#endif

#if defined(_V1) && !defined(ISPI_FILTER_PATTERN_REG)
#define ISPI_FILTER_PATTERN_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_FILTER_PATTERN_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_FILTER_PATTERN_VAL)
#define ISPI_FILTER_PATTERN_VAL  PREFIX_VAL(ISPI_FILTER_PATTERN_REG)
#endif

#define SPI1_ISPI_FILTER_PATTERN_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_FILTER_PATTERN_OFFSET))
#define SPI1_ISPI_FILTER_PATTERN_VAL  PREFIX_VAL(SPI1_ISPI_FILTER_PATTERN_REG)

/* FIELDS: */

/* FILTER_PAT */

#ifndef SPI_ISPI_FILTER_PATTERN_FILTER_PAT_POS
#define SPI_ISPI_FILTER_PATTERN_FILTER_PAT_POS      0
#endif

#ifndef SPI_ISPI_FILTER_PATTERN_FILTER_PAT_LEN
#define SPI_ISPI_FILTER_PATTERN_FILTER_PAT_LEN      32
#endif

#if defined(_V1) && !defined(ISPI_FILTER_PATTERN_FILTER_PAT_R)
#define ISPI_FILTER_PATTERN_FILTER_PAT_R        GetGroupBits32( (SPI1_ISPI_FILTER_PATTERN_VAL),SPI_ISPI_FILTER_PATTERN_FILTER_PAT_POS, SPI_ISPI_FILTER_PATTERN_FILTER_PAT_LEN)
#endif

#if defined(_V1) && !defined(ISPI_FILTER_PATTERN_FILTER_PAT_W)
#define ISPI_FILTER_PATTERN_FILTER_PAT_W(value) SetGroupBits32( (SPI1_ISPI_FILTER_PATTERN_VAL),SPI_ISPI_FILTER_PATTERN_FILTER_PAT_POS, SPI_ISPI_FILTER_PATTERN_FILTER_PAT_LEN,value)
#endif

#define SPI1_ISPI_FILTER_PATTERN_FILTER_PAT_R        GetGroupBits32( (SPI1_ISPI_FILTER_PATTERN_VAL),SPI_ISPI_FILTER_PATTERN_FILTER_PAT_POS, SPI_ISPI_FILTER_PATTERN_FILTER_PAT_LEN)

#define SPI1_ISPI_FILTER_PATTERN_FILTER_PAT_W(value) SetGroupBits32( (SPI1_ISPI_FILTER_PATTERN_VAL),SPI_ISPI_FILTER_PATTERN_FILTER_PAT_POS, SPI_ISPI_FILTER_PATTERN_FILTER_PAT_LEN,value)


/* REGISTER: ISPI_TX_SETUP */

#if defined(_V1) && !defined(ISPI_TX_SETUP_OFFSET)
#define ISPI_TX_SETUP_OFFSET 0x30
#endif

#if !defined(SPI_ISPI_TX_SETUP_OFFSET)
#define SPI_ISPI_TX_SETUP_OFFSET 0x30
#endif

#if defined(_V1) && !defined(ISPI_TX_SETUP_REG)
#define ISPI_TX_SETUP_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_TX_SETUP_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_TX_SETUP_VAL)
#define ISPI_TX_SETUP_VAL  PREFIX_VAL(ISPI_TX_SETUP_REG)
#endif

#define SPI1_ISPI_TX_SETUP_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_TX_SETUP_OFFSET))
#define SPI1_ISPI_TX_SETUP_VAL  PREFIX_VAL(SPI1_ISPI_TX_SETUP_REG)

/* FIELDS: */

/* TX_SET */

#ifndef SPI_ISPI_TX_SETUP_TX_SET_POS
#define SPI_ISPI_TX_SETUP_TX_SET_POS      0
#endif

#ifndef SPI_ISPI_TX_SETUP_TX_SET_LEN
#define SPI_ISPI_TX_SETUP_TX_SET_LEN      8
#endif

#if defined(_V1) && !defined(ISPI_TX_SETUP_TX_SET_R)
#define ISPI_TX_SETUP_TX_SET_R        GetGroupBits32( (SPI1_ISPI_TX_SETUP_VAL),SPI_ISPI_TX_SETUP_TX_SET_POS, SPI_ISPI_TX_SETUP_TX_SET_LEN)
#endif

#if defined(_V1) && !defined(ISPI_TX_SETUP_TX_SET_W)
#define ISPI_TX_SETUP_TX_SET_W(value) SetGroupBits32( (SPI1_ISPI_TX_SETUP_VAL),SPI_ISPI_TX_SETUP_TX_SET_POS, SPI_ISPI_TX_SETUP_TX_SET_LEN,value)
#endif

#define SPI1_ISPI_TX_SETUP_TX_SET_R        GetGroupBits32( (SPI1_ISPI_TX_SETUP_VAL),SPI_ISPI_TX_SETUP_TX_SET_POS, SPI_ISPI_TX_SETUP_TX_SET_LEN)

#define SPI1_ISPI_TX_SETUP_TX_SET_W(value) SetGroupBits32( (SPI1_ISPI_TX_SETUP_VAL),SPI_ISPI_TX_SETUP_TX_SET_POS, SPI_ISPI_TX_SETUP_TX_SET_LEN,value)


/* REGISTER: ISPI_RX_BIT_ORDER */

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_OFFSET)
#define ISPI_RX_BIT_ORDER_OFFSET 0x34
#endif

#if !defined(SPI_ISPI_RX_BIT_ORDER_OFFSET)
#define SPI_ISPI_RX_BIT_ORDER_OFFSET 0x34
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_REG)
#define ISPI_RX_BIT_ORDER_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_RX_BIT_ORDER_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_VAL)
#define ISPI_RX_BIT_ORDER_VAL  PREFIX_VAL(ISPI_RX_BIT_ORDER_REG)
#endif

#define SPI1_ISPI_RX_BIT_ORDER_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_RX_BIT_ORDER_OFFSET))
#define SPI1_ISPI_RX_BIT_ORDER_VAL  PREFIX_VAL(SPI1_ISPI_RX_BIT_ORDER_REG)

/* FIELDS: */

/* SDI_BIT_LOCATION */

#ifndef SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_POS
#define SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_POS      0
#endif

#ifndef SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_LEN
#define SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_R)
#define ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_LEN)
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_W)
#define ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_LEN,value)
#endif

#define SPI1_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_LEN)

#define SPI1_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_BIT_LOCATION_LEN,value)


/* SDO_BIT_LOCATION */

#ifndef SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_POS
#define SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_POS      4
#endif

#ifndef SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_LEN
#define SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_R)
#define ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_LEN)
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_W)
#define ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_LEN,value)
#endif

#define SPI1_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_LEN)

#define SPI1_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDO_BIT_LOCATION_LEN,value)


/* SDI_ADD2_BIT_LOCATION */

#ifndef SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_POS
#define SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_POS      8
#endif

#ifndef SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_LEN
#define SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_R)
#define ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_LEN)
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_W)
#define ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_LEN,value)
#endif

#define SPI1_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_LEN)

#define SPI1_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD2_BIT_LOCATION_LEN,value)


/* SDI_ADD3_BIT_LOCATION */

#ifndef SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_POS
#define SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_POS      12
#endif

#ifndef SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_LEN
#define SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_LEN      2
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_R)
#define ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_LEN)
#endif

#if defined(_V1) && !defined(ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_W)
#define ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_LEN,value)
#endif

#define SPI1_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_R        GetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_LEN)

#define SPI1_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_W(value) SetGroupBits32( (SPI1_ISPI_RX_BIT_ORDER_VAL),SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_POS, SPI_ISPI_RX_BIT_ORDER_SDI_ADD3_BIT_LOCATION_LEN,value)


/* REGISTER: ISPI_ACTIVATE_CS */

#if defined(_V1) && !defined(ISPI_ACTIVATE_CS_OFFSET)
#define ISPI_ACTIVATE_CS_OFFSET 0x38
#endif

#if !defined(SPI_ISPI_ACTIVATE_CS_OFFSET)
#define SPI_ISPI_ACTIVATE_CS_OFFSET 0x38
#endif

#if defined(_V1) && !defined(ISPI_ACTIVATE_CS_REG)
#define ISPI_ACTIVATE_CS_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_ACTIVATE_CS_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_ACTIVATE_CS_VAL)
#define ISPI_ACTIVATE_CS_VAL  PREFIX_VAL(ISPI_ACTIVATE_CS_REG)
#endif

#define SPI1_ISPI_ACTIVATE_CS_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_ACTIVATE_CS_OFFSET))
#define SPI1_ISPI_ACTIVATE_CS_VAL  PREFIX_VAL(SPI1_ISPI_ACTIVATE_CS_REG)

/* FIELDS: */

/* ACTIVATE_CS */

#ifndef SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_POS
#define SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_POS      0
#endif

#ifndef SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_LEN
#define SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_LEN      4
#endif

#if defined(_V1) && !defined(ISPI_ACTIVATE_CS_ACTIVATE_CS_R)
#define ISPI_ACTIVATE_CS_ACTIVATE_CS_R        GetGroupBits32( (SPI1_ISPI_ACTIVATE_CS_VAL),SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_POS, SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_LEN)
#endif

#if defined(_V1) && !defined(ISPI_ACTIVATE_CS_ACTIVATE_CS_W)
#define ISPI_ACTIVATE_CS_ACTIVATE_CS_W(value) SetGroupBits32( (SPI1_ISPI_ACTIVATE_CS_VAL),SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_POS, SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_LEN,value)
#endif

#define SPI1_ISPI_ACTIVATE_CS_ACTIVATE_CS_R        GetGroupBits32( (SPI1_ISPI_ACTIVATE_CS_VAL),SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_POS, SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_LEN)

#define SPI1_ISPI_ACTIVATE_CS_ACTIVATE_CS_W(value) SetGroupBits32( (SPI1_ISPI_ACTIVATE_CS_VAL),SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_POS, SPI_ISPI_ACTIVATE_CS_ACTIVATE_CS_LEN,value)


/* REGISTER: ISPI_GEN_PARAM */

#if defined(_V1) && !defined(ISPI_GEN_PARAM_OFFSET)
#define ISPI_GEN_PARAM_OFFSET 0x3C
#endif

#if !defined(SPI_ISPI_GEN_PARAM_OFFSET)
#define SPI_ISPI_GEN_PARAM_OFFSET 0x3C
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_REG)
#define ISPI_GEN_PARAM_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_GEN_PARAM_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_VAL)
#define ISPI_GEN_PARAM_VAL  PREFIX_VAL(ISPI_GEN_PARAM_REG)
#endif

#define SPI1_ISPI_GEN_PARAM_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_GEN_PARAM_OFFSET))
#define SPI1_ISPI_GEN_PARAM_VAL  PREFIX_VAL(SPI1_ISPI_GEN_PARAM_REG)

/* FIELDS: */

/* SPI_RX_FIFO_BYTES_LOG */

#ifndef SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_POS
#define SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_POS      0
#endif

#ifndef SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_LEN
#define SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_LEN      4
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_R)
#define ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_LEN)
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_W)
#define ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_LEN,value)
#endif

#define SPI1_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_LEN)

#define SPI1_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_RX_FIFO_BYTES_LOG_LEN,value)


/* SPI_TX_FIFO_BYTES_LOG */

#ifndef SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_POS
#define SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_POS      4
#endif

#ifndef SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_LEN
#define SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_LEN      4
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_R)
#define ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_LEN)
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_W)
#define ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_LEN,value)
#endif

#define SPI1_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_LEN)

#define SPI1_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_POS, SPI_ISPI_GEN_PARAM_SPI_TX_FIFO_BYTES_LOG_LEN,value)


/* SPI_CS_NUM */

#ifndef SPI_ISPI_GEN_PARAM_SPI_CS_NUM_POS
#define SPI_ISPI_GEN_PARAM_SPI_CS_NUM_POS      8
#endif

#ifndef SPI_ISPI_GEN_PARAM_SPI_CS_NUM_LEN
#define SPI_ISPI_GEN_PARAM_SPI_CS_NUM_LEN      6
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_CS_NUM_R)
#define ISPI_GEN_PARAM_SPI_CS_NUM_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_CS_NUM_POS, SPI_ISPI_GEN_PARAM_SPI_CS_NUM_LEN)
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_CS_NUM_W)
#define ISPI_GEN_PARAM_SPI_CS_NUM_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_CS_NUM_POS, SPI_ISPI_GEN_PARAM_SPI_CS_NUM_LEN,value)
#endif

#define SPI1_ISPI_GEN_PARAM_SPI_CS_NUM_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_CS_NUM_POS, SPI_ISPI_GEN_PARAM_SPI_CS_NUM_LEN)

#define SPI1_ISPI_GEN_PARAM_SPI_CS_NUM_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_CS_NUM_POS, SPI_ISPI_GEN_PARAM_SPI_CS_NUM_LEN,value)


/* SPI_TIMER_BITS */

#ifndef SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_POS
#define SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_POS      16
#endif

#ifndef SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_LEN
#define SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_LEN      6
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_TIMER_BITS_R)
#define ISPI_GEN_PARAM_SPI_TIMER_BITS_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_POS, SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_LEN)
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_TIMER_BITS_W)
#define ISPI_GEN_PARAM_SPI_TIMER_BITS_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_POS, SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_LEN,value)
#endif

#define SPI1_ISPI_GEN_PARAM_SPI_TIMER_BITS_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_POS, SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_LEN)

#define SPI1_ISPI_GEN_PARAM_SPI_TIMER_BITS_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_POS, SPI_ISPI_GEN_PARAM_SPI_TIMER_BITS_LEN,value)


/* SPI_IP_VERSION */

#ifndef SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_POS
#define SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_POS      24
#endif

#ifndef SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_LEN
#define SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_LEN      8
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_IP_VERSION_R)
#define ISPI_GEN_PARAM_SPI_IP_VERSION_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_POS, SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_LEN)
#endif

#if defined(_V1) && !defined(ISPI_GEN_PARAM_SPI_IP_VERSION_W)
#define ISPI_GEN_PARAM_SPI_IP_VERSION_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_POS, SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_LEN,value)
#endif

#define SPI1_ISPI_GEN_PARAM_SPI_IP_VERSION_R        GetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_POS, SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_LEN)

#define SPI1_ISPI_GEN_PARAM_SPI_IP_VERSION_W(value) SetGroupBits32( (SPI1_ISPI_GEN_PARAM_VAL),SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_POS, SPI_ISPI_GEN_PARAM_SPI_IP_VERSION_LEN,value)


/* REGISTER: ISPI_COMMAND */

#if defined(_V1) && !defined(ISPI_COMMAND_OFFSET)
#define ISPI_COMMAND_OFFSET 0x4
#endif

#if !defined(SPI_ISPI_COMMAND_OFFSET)
#define SPI_ISPI_COMMAND_OFFSET 0x4
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_REG)
#define ISPI_COMMAND_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_COMMAND_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_VAL)
#define ISPI_COMMAND_VAL  PREFIX_VAL(ISPI_COMMAND_REG)
#endif

#define SPI1_ISPI_COMMAND_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_COMMAND_OFFSET))
#define SPI1_ISPI_COMMAND_VAL  PREFIX_VAL(SPI1_ISPI_COMMAND_REG)

/* FIELDS: */

/* RX_RESET */

#ifndef SPI_ISPI_COMMAND_RX_RESET_POS
#define SPI_ISPI_COMMAND_RX_RESET_POS      0
#endif

#ifndef SPI_ISPI_COMMAND_RX_RESET_LEN
#define SPI_ISPI_COMMAND_RX_RESET_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_RX_RESET_R)
#define ISPI_COMMAND_RX_RESET_R        GetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_RX_RESET_POS, SPI_ISPI_COMMAND_RX_RESET_LEN)
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_RX_RESET_W)
#define ISPI_COMMAND_RX_RESET_W(value) SetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_RX_RESET_POS, SPI_ISPI_COMMAND_RX_RESET_LEN,value)
#endif

#define SPI1_ISPI_COMMAND_RX_RESET_R        GetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_RX_RESET_POS, SPI_ISPI_COMMAND_RX_RESET_LEN)

#define SPI1_ISPI_COMMAND_RX_RESET_W(value) SetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_RX_RESET_POS, SPI_ISPI_COMMAND_RX_RESET_LEN,value)


/* TX_RESET */

#ifndef SPI_ISPI_COMMAND_TX_RESET_POS
#define SPI_ISPI_COMMAND_TX_RESET_POS      1
#endif

#ifndef SPI_ISPI_COMMAND_TX_RESET_LEN
#define SPI_ISPI_COMMAND_TX_RESET_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_TX_RESET_R)
#define ISPI_COMMAND_TX_RESET_R        GetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_TX_RESET_POS, SPI_ISPI_COMMAND_TX_RESET_LEN)
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_TX_RESET_W)
#define ISPI_COMMAND_TX_RESET_W(value) SetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_TX_RESET_POS, SPI_ISPI_COMMAND_TX_RESET_LEN,value)
#endif

#define SPI1_ISPI_COMMAND_TX_RESET_R        GetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_TX_RESET_POS, SPI_ISPI_COMMAND_TX_RESET_LEN)

#define SPI1_ISPI_COMMAND_TX_RESET_W(value) SetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_TX_RESET_POS, SPI_ISPI_COMMAND_TX_RESET_LEN,value)


/* WAIT_RX */

#ifndef SPI_ISPI_COMMAND_WAIT_RX_POS
#define SPI_ISPI_COMMAND_WAIT_RX_POS      4
#endif

#ifndef SPI_ISPI_COMMAND_WAIT_RX_LEN
#define SPI_ISPI_COMMAND_WAIT_RX_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_WAIT_RX_R)
#define ISPI_COMMAND_WAIT_RX_R        GetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_WAIT_RX_POS, SPI_ISPI_COMMAND_WAIT_RX_LEN)
#endif

#if defined(_V1) && !defined(ISPI_COMMAND_WAIT_RX_W)
#define ISPI_COMMAND_WAIT_RX_W(value) SetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_WAIT_RX_POS, SPI_ISPI_COMMAND_WAIT_RX_LEN,value)
#endif

#define SPI1_ISPI_COMMAND_WAIT_RX_R        GetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_WAIT_RX_POS, SPI_ISPI_COMMAND_WAIT_RX_LEN)

#define SPI1_ISPI_COMMAND_WAIT_RX_W(value) SetGroupBits32( (SPI1_ISPI_COMMAND_VAL),SPI_ISPI_COMMAND_WAIT_RX_POS, SPI_ISPI_COMMAND_WAIT_RX_LEN,value)


/* REGISTER: ISPI_FIFO */

#if defined(_V1) && !defined(ISPI_FIFO_OFFSET)
#define ISPI_FIFO_OFFSET 0x8
#endif

#if !defined(SPI_ISPI_FIFO_OFFSET)
#define SPI_ISPI_FIFO_OFFSET 0x8
#endif

#if defined(_V1) && !defined(ISPI_FIFO_REG)
#define ISPI_FIFO_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_FIFO_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_FIFO_VAL)
#define ISPI_FIFO_VAL  PREFIX_VAL(ISPI_FIFO_REG)
#endif

#define SPI1_ISPI_FIFO_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_FIFO_OFFSET))
#define SPI1_ISPI_FIFO_VAL  PREFIX_VAL(SPI1_ISPI_FIFO_REG)

/* FIELDS: */

/* Rd_RX_FIFO_Wr_TX_FIFO */

#ifndef SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_POS
#define SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_POS      0
#endif

#ifndef SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_LEN
#define SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_LEN      32
#endif

#if defined(_V1) && !defined(ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_R)
#define ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_R        GetGroupBits32( (SPI1_ISPI_FIFO_VAL),SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_POS, SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_LEN)
#endif

#if defined(_V1) && !defined(ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_W)
#define ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_W(value) SetGroupBits32( (SPI1_ISPI_FIFO_VAL),SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_POS, SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_LEN,value)
#endif

#define SPI1_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_R        GetGroupBits32( (SPI1_ISPI_FIFO_VAL),SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_POS, SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_LEN)

#define SPI1_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_W(value) SetGroupBits32( (SPI1_ISPI_FIFO_VAL),SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_POS, SPI_ISPI_FIFO_RD_RX_FIFO_WR_TX_FIFO_LEN,value)


/* REGISTER: ISPI_DMA */

#if defined(_V1) && !defined(ISPI_DMA_OFFSET)
#define ISPI_DMA_OFFSET 0xC
#endif

#if !defined(SPI_ISPI_DMA_OFFSET)
#define SPI_ISPI_DMA_OFFSET 0xC
#endif

#if defined(_V1) && !defined(ISPI_DMA_REG)
#define ISPI_DMA_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_DMA_OFFSET))
#endif

#if defined(_V1) && !defined(ISPI_DMA_VAL)
#define ISPI_DMA_VAL  PREFIX_VAL(ISPI_DMA_REG)
#endif

#define SPI1_ISPI_DMA_REG ((volatile UINT32 *) (SPI1_BASE + SPI_ISPI_DMA_OFFSET))
#define SPI1_ISPI_DMA_VAL  PREFIX_VAL(SPI1_ISPI_DMA_REG)

/* FIELDS: */

/* RX_THRESHOLD */

#ifndef SPI_ISPI_DMA_RX_THRESHOLD_POS
#define SPI_ISPI_DMA_RX_THRESHOLD_POS      0
#endif

#ifndef SPI_ISPI_DMA_RX_THRESHOLD_LEN
#define SPI_ISPI_DMA_RX_THRESHOLD_LEN      6
#endif

#if defined(_V1) && !defined(ISPI_DMA_RX_THRESHOLD_R)
#define ISPI_DMA_RX_THRESHOLD_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_THRESHOLD_POS, SPI_ISPI_DMA_RX_THRESHOLD_LEN)
#endif

#if defined(_V1) && !defined(ISPI_DMA_RX_THRESHOLD_W)
#define ISPI_DMA_RX_THRESHOLD_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_THRESHOLD_POS, SPI_ISPI_DMA_RX_THRESHOLD_LEN,value)
#endif

#define SPI1_ISPI_DMA_RX_THRESHOLD_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_THRESHOLD_POS, SPI_ISPI_DMA_RX_THRESHOLD_LEN)

#define SPI1_ISPI_DMA_RX_THRESHOLD_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_THRESHOLD_POS, SPI_ISPI_DMA_RX_THRESHOLD_LEN,value)


/* RX_DMA_EN */

#ifndef SPI_ISPI_DMA_RX_DMA_EN_POS
#define SPI_ISPI_DMA_RX_DMA_EN_POS      15
#endif

#ifndef SPI_ISPI_DMA_RX_DMA_EN_LEN
#define SPI_ISPI_DMA_RX_DMA_EN_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_DMA_RX_DMA_EN_R)
#define ISPI_DMA_RX_DMA_EN_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_DMA_EN_POS, SPI_ISPI_DMA_RX_DMA_EN_LEN)
#endif

#if defined(_V1) && !defined(ISPI_DMA_RX_DMA_EN_W)
#define ISPI_DMA_RX_DMA_EN_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_DMA_EN_POS, SPI_ISPI_DMA_RX_DMA_EN_LEN,value)
#endif

#define SPI1_ISPI_DMA_RX_DMA_EN_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_DMA_EN_POS, SPI_ISPI_DMA_RX_DMA_EN_LEN)

#define SPI1_ISPI_DMA_RX_DMA_EN_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_RX_DMA_EN_POS, SPI_ISPI_DMA_RX_DMA_EN_LEN,value)


/* TX_THRESHOLD */

#ifndef SPI_ISPI_DMA_TX_THRESHOLD_POS
#define SPI_ISPI_DMA_TX_THRESHOLD_POS      16
#endif

#ifndef SPI_ISPI_DMA_TX_THRESHOLD_LEN
#define SPI_ISPI_DMA_TX_THRESHOLD_LEN      6
#endif

#if defined(_V1) && !defined(ISPI_DMA_TX_THRESHOLD_R)
#define ISPI_DMA_TX_THRESHOLD_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_THRESHOLD_POS, SPI_ISPI_DMA_TX_THRESHOLD_LEN)
#endif

#if defined(_V1) && !defined(ISPI_DMA_TX_THRESHOLD_W)
#define ISPI_DMA_TX_THRESHOLD_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_THRESHOLD_POS, SPI_ISPI_DMA_TX_THRESHOLD_LEN,value)
#endif

#define SPI1_ISPI_DMA_TX_THRESHOLD_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_THRESHOLD_POS, SPI_ISPI_DMA_TX_THRESHOLD_LEN)

#define SPI1_ISPI_DMA_TX_THRESHOLD_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_THRESHOLD_POS, SPI_ISPI_DMA_TX_THRESHOLD_LEN,value)


/* TX_DMA_EN */

#ifndef SPI_ISPI_DMA_TX_DMA_EN_POS
#define SPI_ISPI_DMA_TX_DMA_EN_POS      31
#endif

#ifndef SPI_ISPI_DMA_TX_DMA_EN_LEN
#define SPI_ISPI_DMA_TX_DMA_EN_LEN      1
#endif

#if defined(_V1) && !defined(ISPI_DMA_TX_DMA_EN_R)
#define ISPI_DMA_TX_DMA_EN_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_DMA_EN_POS, SPI_ISPI_DMA_TX_DMA_EN_LEN)
#endif

#if defined(_V1) && !defined(ISPI_DMA_TX_DMA_EN_W)
#define ISPI_DMA_TX_DMA_EN_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_DMA_EN_POS, SPI_ISPI_DMA_TX_DMA_EN_LEN,value)
#endif

#define SPI1_ISPI_DMA_TX_DMA_EN_R        GetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_DMA_EN_POS, SPI_ISPI_DMA_TX_DMA_EN_LEN)

#define SPI1_ISPI_DMA_TX_DMA_EN_W(value) SetGroupBits32( (SPI1_ISPI_DMA_VAL),SPI_ISPI_DMA_TX_DMA_EN_POS, SPI_ISPI_DMA_TX_DMA_EN_LEN,value)


/* OFFSET TABLE: */
#define spi1_offset_tbl_values	ISPI_CONFIGURATION_OFFSET, ISPI_INT_RAW_OFFSET, ISPI_INT_EN_OFFSET, ISPI_INT_STAT_OFFSET, ISPI_RX_TIMER_OFFSET, ISPI_STATUS_OFFSET, ISPI_CS_OFFSET, ISPI_FILTER_OFFSET, ISPI_FILTER_PATTERN_OFFSET, ISPI_TX_SETUP_OFFSET, ISPI_RX_BIT_ORDER_OFFSET, ISPI_ACTIVATE_CS_OFFSET, ISPI_GEN_PARAM_OFFSET, ISPI_COMMAND_OFFSET, ISPI_FIFO_OFFSET, ISPI_DMA_OFFSET


/* REGISTERS RESET VAL: */
#define spi1_regs_reset_val	0x0, 0x0, 0x0, 0x0, 0xFF, 0x0, 0x1, 0x0, 0x0, 0x0, 0x3210, 0x0, 0x2000066, 0x0, 0x0, 0x0

#endif

/* End of SPI1 */
/* ///////////////////////////////////////////////////////////////////////*/
