set(__ANDROID_API_LEVEL__ $ENV{ANDROID_API_LEVEL})

set(CMAKE_SYSTEM_VERSION ${__ANDROID_API_LEVEL__} CACHE TYPE INTERNAL FORCE)
set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK})
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_ANDROID_API ${__ANDROID_API_LEVEL__})
set(CMAKE_ANDROID_ARCH_ABI arm64-v8a)
set(CMAKE_CXX_STANDARD 17)

#set(CMAKE_ANDROID_STL_TYPE gnustl_static)

SET(CMAKE_PLATFORM_NAME android_ndk23b_android-${__ANDROID_API_LEVEL__}-arm64-v8a)


