#ifndef _INU_REF_API_H_
#define _INU_REF_API_H_

#define MAX_NAME_LEN 255

#define MAX_UART_PORT_NAME_LEN 64
#define MAX_CDC_PORT_NAME_LEN  MAX_UART_PORT_NAME_LEN

#define INU_REF__FUNCTION_MASK_SHIFT        (8)
#define INU_REF__DATA_MASK_SHIFT            (9)


#define INU_REF__IS_FUNCTION_TYPE(INU__REF) ((INU__REF >> INU_REF__FUNCTION_MASK_SHIFT) & 0x1)
#define INU_REF__IS_DATA_TYPE(INU__REF)     ((INU__REF >> INU_REF__DATA_MASK_SHIFT) & 0x1)
#define INU_REF__FUNCTION_TYPE(MODULE)      (MODULE | (1 << INU_REF__FUNCTION_MASK_SHIFT))
#define INU_REF__DATA_TYPE(MODULE)          (MODULE | (1 << INU_REF__DATA_MASK_SHIFT))


typedef enum
{
   INU_DEVICE_REF_TYPE        = INU_DEVICE,
   INU_LOAD_NETWORK_REF_TYPE  = INU_LOAD_NETWORK,
   INU_LOAD_BACKGROUND_REF_TYPE	= INU_LOAD_BACKGROUND,
   INU_LOGGER_REF_TYPE        = INU_LOGGER,
   INU_GRAPH_REF_TYPE         = INU_GRAPH,

   INU_SENSOR_REF_TYPE         = INU_REF__FUNCTION_TYPE(INU_SENSOR),
   INU_SENSORS_GROUP_REF_TYPE  = INU_REF__FUNCTION_TYPE(INU_SENSORS_GROUP),
   INU_SOC_CHANNEL_REF_TYPE    = INU_REF__FUNCTION_TYPE(INU_SOC_CHANNEL),
   INU_ISP_CHANNEL_REF_TYPE    = INU_REF__FUNCTION_TYPE(INU_ISP_CHANNEL),
   INU_HISTOGRAM_REF_TYPE      = INU_REF__FUNCTION_TYPE(INU_HISTOGRAM),
   INU_SOC_WRITER_REF_TYPE     = INU_REF__FUNCTION_TYPE(INU_SOC_WRITER),
   INU_FDK_REF_TYPE            = INU_REF__FUNCTION_TYPE(INU_FDK),
   INU_FDK_DSO_REF_TYPE        = INU_REF__FUNCTION_TYPE(INU_FDK_DSO),
   INU_IMU_REF_TYPE            = INU_REF__FUNCTION_TYPE(INU_IMU),
   INU_TEMPERATURE_REF_TYPE    = INU_REF__FUNCTION_TYPE(INU_TEMPERATURE),
   INU_STREAMER_REF_TYPE       = INU_REF__FUNCTION_TYPE(INU_STREAMER),
   INU_SENSOR_CONTROL_REF_TYPE = INU_REF__FUNCTION_TYPE(INU_SENSOR_CONTROL),
   INU_FAST_ORB_REF_TYPE       = INU_REF__FUNCTION_TYPE(INU_FAST_ORB),
   INU_CVA_CHANNEL_REF_TYPE    = INU_REF__FUNCTION_TYPE(INU_CVA_CHANNEL),
   INU_CDNN_REF_TYPE           = INU_REF__FUNCTION_TYPE(INU_CDNN),
   INU_VISION_PROC_REF_TYPE 	 = INU_REF__FUNCTION_TYPE(INU_VISION_PROC),
   INU_SLAM_REF_TYPE           = INU_REF__FUNCTION_TYPE(INU_SLAM),
   INU_DPE_PP_REF_TYPE         = INU_REF__FUNCTION_TYPE(INU_DPE_PP),
   INU_PP_REF_TYPE             = INU_REF__FUNCTION_TYPE(INU_PP),
   INU_TSNR_CALC_REF_TYPE      = INU_REF__FUNCTION_TYPE(INU_TSNR_CALC),
   INU_COMPRESS_REF_TYPE       = INU_REF__FUNCTION_TYPE(INU_COMPRESS),
   INU_MIPI_CHANNEL_REF_TYPE   = INU_REF__FUNCTION_TYPE(INU_MIPI_CHANNEL),
   INU_METADATA_INJECT_REF_TYPE = INU_REF__FUNCTION_TYPE(INU_METADATA_INJECT),

   INU_IMAGE_REF_TYPE            = INU_REF__DATA_TYPE(INU_IMAGE),
   INU_IMU_DATA_REF_TYPE         = INU_REF__DATA_TYPE(INU_IMU_DATA),
   INU_TEMPERATURE_DATA_REF_TYPE = INU_REF__DATA_TYPE(INU_TEMPERATURE_DATA),
   INU_RAW_DATA_REF_TYPE         = INU_REF__DATA_TYPE(INU_RAW_DATA),
   INU_FAST_ORB_DATA_REF_TYPE    = INU_REF__DATA_TYPE(INU_FAST_ORB_DATA),
   INU_CVA_DATA_REF_TYPE         = INU_REF__DATA_TYPE(INU_CVA_DATA),
   INU_CDNN_DATA_REF_TYPE        = INU_REF__DATA_TYPE(INU_CDNN_DATA),
   INU_SLAM_DATA_REF_TYPE        = INU_REF__DATA_TYPE(INU_SLAM_DATA),
   INU_TSNR_DATA_REF_TYPE        = INU_REF__DATA_TYPE(INU_TSNR_DATA),
   INU_POINT_CLOUD_DATA_REF_TYPE = INU_REF__DATA_TYPE(INU_POINT_CLOUD_DATA),
   INU_HISTOGRAM_DATA_REF_TYPE   = INU_REF__DATA_TYPE(INU_HISTOGRAM_DATA),

   
   INU_FACTORY__REF_NUM          = INU_REF__DATA_TYPE(MODULE_ID__MAX_E) + 1,
}inu_ref__types;


BOOLEAN inu_ref__instanceOf(inu_refH refH, inu_ref__types type);
ERRG_codeE inu_ref__check(inu_refH me);
BOOLEAN inu_ref__standAloneModeCodeIgnr(inu_refH refH, UINT32 cmd);
BOOLEAN inu_ref__standAloneMode(inu_refH refH);
const char *inu_ref__getUserName(inu_refH me);
inu_ref__types inu_ref__getRefType(inu_refH me);
unsigned int inu_ref__getRefId(inu_refH me);


#endif
