#ifndef NU4000_B0_WDT3_REG_H
#define NU4000_B0_WDT3_REG_H


/* types */
#include "defs.h"

#if !defined(PREFIX_VAL)
#define PREFIX_VAL *
#endif
 
#if !defined(SetGroupBits32) 
#define SetGroupBits32(reg,position,len,value)\
{       \
        UINT32 tmp=reg;\
        tmp&=~(((UINT32)0xFFFFFFFF>>(32-(len)))<<(position));\
        tmp|=((value&((UINT32)0xFFFFFFFF>>(32-(len))))<<(position));\
        reg=tmp;\
}
#endif

#if !defined(GetGroupBits32)
#define GetGroupBits32(reg,position,len) (((reg) & (((UINT32)0xFFFFFFFF>>(32-(len)))<<(position)))>>(position))
#endif


/*****************************************/
/*   WDT3 (Prototype: WDT)                */
/*****************************************/
#define WDT3_BASE 0x08118000

/* REGISTER: WDT_CR */

#if defined(_V1) && !defined(WDT_CR_OFFSET)
#define WDT_CR_OFFSET 0x0
#endif

#if !defined(WDT_WDT_CR_OFFSET)
#define WDT_WDT_CR_OFFSET 0x0
#endif

#if defined(_V1) && !defined(WDT_CR_REG)
#define WDT_CR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_CR_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_CR_VAL)
#define WDT_CR_VAL  PREFIX_VAL(WDT_CR_REG)
#endif

#define WDT3_WDT_CR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_CR_OFFSET))
#define WDT3_WDT_CR_VAL  PREFIX_VAL(WDT3_WDT_CR_REG)

/* FIELDS: */

/* WDT_EN */

#ifndef WDT_WDT_CR_WDT_EN_POS
#define WDT_WDT_CR_WDT_EN_POS      0
#endif

#ifndef WDT_WDT_CR_WDT_EN_LEN
#define WDT_WDT_CR_WDT_EN_LEN      1
#endif

#if defined(_V1) && !defined(WDT_CR_WDT_EN_R)
#define WDT_CR_WDT_EN_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_WDT_EN_POS, WDT_WDT_CR_WDT_EN_LEN)
#endif

#if defined(_V1) && !defined(WDT_CR_WDT_EN_W)
#define WDT_CR_WDT_EN_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_WDT_EN_POS, WDT_WDT_CR_WDT_EN_LEN,value)
#endif

#define WDT3_WDT_CR_WDT_EN_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_WDT_EN_POS, WDT_WDT_CR_WDT_EN_LEN)

#define WDT3_WDT_CR_WDT_EN_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_WDT_EN_POS, WDT_WDT_CR_WDT_EN_LEN,value)


/* RMOD */

#ifndef WDT_WDT_CR_RMOD_POS
#define WDT_WDT_CR_RMOD_POS      1
#endif

#ifndef WDT_WDT_CR_RMOD_LEN
#define WDT_WDT_CR_RMOD_LEN      1
#endif

#if defined(_V1) && !defined(WDT_CR_RMOD_R)
#define WDT_CR_RMOD_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RMOD_POS, WDT_WDT_CR_RMOD_LEN)
#endif

#if defined(_V1) && !defined(WDT_CR_RMOD_W)
#define WDT_CR_RMOD_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RMOD_POS, WDT_WDT_CR_RMOD_LEN,value)
#endif

#define WDT3_WDT_CR_RMOD_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RMOD_POS, WDT_WDT_CR_RMOD_LEN)

#define WDT3_WDT_CR_RMOD_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RMOD_POS, WDT_WDT_CR_RMOD_LEN,value)


/* RPL */

#ifndef WDT_WDT_CR_RPL_POS
#define WDT_WDT_CR_RPL_POS      2
#endif

#ifndef WDT_WDT_CR_RPL_LEN
#define WDT_WDT_CR_RPL_LEN      3
#endif

#if defined(_V1) && !defined(WDT_CR_RPL_R)
#define WDT_CR_RPL_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RPL_POS, WDT_WDT_CR_RPL_LEN)
#endif

#if defined(_V1) && !defined(WDT_CR_RPL_W)
#define WDT_CR_RPL_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RPL_POS, WDT_WDT_CR_RPL_LEN,value)
#endif

#define WDT3_WDT_CR_RPL_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RPL_POS, WDT_WDT_CR_RPL_LEN)

#define WDT3_WDT_CR_RPL_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RPL_POS, WDT_WDT_CR_RPL_LEN,value)


/* RSVD_WDT_CR */

#ifndef WDT_WDT_CR_RSVD_WDT_CR_POS
#define WDT_WDT_CR_RSVD_WDT_CR_POS      5
#endif

#ifndef WDT_WDT_CR_RSVD_WDT_CR_LEN
#define WDT_WDT_CR_RSVD_WDT_CR_LEN      27
#endif

#if defined(_V1) && !defined(WDT_CR_RSVD_WDT_CR_R)
#define WDT_CR_RSVD_WDT_CR_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RSVD_WDT_CR_POS, WDT_WDT_CR_RSVD_WDT_CR_LEN)
#endif

#if defined(_V1) && !defined(WDT_CR_RSVD_WDT_CR_W)
#define WDT_CR_RSVD_WDT_CR_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RSVD_WDT_CR_POS, WDT_WDT_CR_RSVD_WDT_CR_LEN,value)
#endif

#define WDT3_WDT_CR_RSVD_WDT_CR_R        GetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RSVD_WDT_CR_POS, WDT_WDT_CR_RSVD_WDT_CR_LEN)

#define WDT3_WDT_CR_RSVD_WDT_CR_W(value) SetGroupBits32( (WDT3_WDT_CR_VAL),WDT_WDT_CR_RSVD_WDT_CR_POS, WDT_WDT_CR_RSVD_WDT_CR_LEN,value)


/* REGISTER: WDT_STAT */

#if defined(_V1) && !defined(WDT_STAT_OFFSET)
#define WDT_STAT_OFFSET 0x10
#endif

#if !defined(WDT_WDT_STAT_OFFSET)
#define WDT_WDT_STAT_OFFSET 0x10
#endif

#if defined(_V1) && !defined(WDT_STAT_REG)
#define WDT_STAT_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_STAT_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_STAT_VAL)
#define WDT_STAT_VAL  PREFIX_VAL(WDT_STAT_REG)
#endif

#define WDT3_WDT_STAT_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_STAT_OFFSET))
#define WDT3_WDT_STAT_VAL  PREFIX_VAL(WDT3_WDT_STAT_REG)

/* FIELDS: */

/* wdt_stat */

#ifndef WDT_WDT_STAT_WDT_STAT_POS
#define WDT_WDT_STAT_WDT_STAT_POS      0
#endif

#ifndef WDT_WDT_STAT_WDT_STAT_LEN
#define WDT_WDT_STAT_WDT_STAT_LEN      1
#endif

#if defined(_V1) && !defined(WDT_STAT_WDT_STAT_R)
#define WDT_STAT_WDT_STAT_R        GetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_WDT_STAT_POS, WDT_WDT_STAT_WDT_STAT_LEN)
#endif

#if defined(_V1) && !defined(WDT_STAT_WDT_STAT_W)
#define WDT_STAT_WDT_STAT_W(value) SetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_WDT_STAT_POS, WDT_WDT_STAT_WDT_STAT_LEN,value)
#endif

#define WDT3_WDT_STAT_WDT_STAT_R        GetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_WDT_STAT_POS, WDT_WDT_STAT_WDT_STAT_LEN)

#define WDT3_WDT_STAT_WDT_STAT_W(value) SetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_WDT_STAT_POS, WDT_WDT_STAT_WDT_STAT_LEN,value)


/* RSVD_WDT_STAT */

#ifndef WDT_WDT_STAT_RSVD_WDT_STAT_POS
#define WDT_WDT_STAT_RSVD_WDT_STAT_POS      1
#endif

#ifndef WDT_WDT_STAT_RSVD_WDT_STAT_LEN
#define WDT_WDT_STAT_RSVD_WDT_STAT_LEN      31
#endif

#if defined(_V1) && !defined(WDT_STAT_RSVD_WDT_STAT_R)
#define WDT_STAT_RSVD_WDT_STAT_R        GetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_RSVD_WDT_STAT_POS, WDT_WDT_STAT_RSVD_WDT_STAT_LEN)
#endif

#if defined(_V1) && !defined(WDT_STAT_RSVD_WDT_STAT_W)
#define WDT_STAT_RSVD_WDT_STAT_W(value) SetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_RSVD_WDT_STAT_POS, WDT_WDT_STAT_RSVD_WDT_STAT_LEN,value)
#endif

#define WDT3_WDT_STAT_RSVD_WDT_STAT_R        GetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_RSVD_WDT_STAT_POS, WDT_WDT_STAT_RSVD_WDT_STAT_LEN)

#define WDT3_WDT_STAT_RSVD_WDT_STAT_W(value) SetGroupBits32( (WDT3_WDT_STAT_VAL),WDT_WDT_STAT_RSVD_WDT_STAT_POS, WDT_WDT_STAT_RSVD_WDT_STAT_LEN,value)


/* REGISTER: WDT_EOI */

#if defined(_V1) && !defined(WDT_EOI_OFFSET)
#define WDT_EOI_OFFSET 0x14
#endif

#if !defined(WDT_WDT_EOI_OFFSET)
#define WDT_WDT_EOI_OFFSET 0x14
#endif

#if defined(_V1) && !defined(WDT_EOI_REG)
#define WDT_EOI_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_EOI_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_EOI_VAL)
#define WDT_EOI_VAL  PREFIX_VAL(WDT_EOI_REG)
#endif

#define WDT3_WDT_EOI_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_EOI_OFFSET))
#define WDT3_WDT_EOI_VAL  PREFIX_VAL(WDT3_WDT_EOI_REG)

/* FIELDS: */

/* wdt_eoi */

#ifndef WDT_WDT_EOI_WDT_EOI_POS
#define WDT_WDT_EOI_WDT_EOI_POS      0
#endif

#ifndef WDT_WDT_EOI_WDT_EOI_LEN
#define WDT_WDT_EOI_WDT_EOI_LEN      1
#endif

#if defined(_V1) && !defined(WDT_EOI_WDT_EOI_R)
#define WDT_EOI_WDT_EOI_R        GetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_WDT_EOI_POS, WDT_WDT_EOI_WDT_EOI_LEN)
#endif

#if defined(_V1) && !defined(WDT_EOI_WDT_EOI_W)
#define WDT_EOI_WDT_EOI_W(value) SetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_WDT_EOI_POS, WDT_WDT_EOI_WDT_EOI_LEN,value)
#endif

#define WDT3_WDT_EOI_WDT_EOI_R        GetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_WDT_EOI_POS, WDT_WDT_EOI_WDT_EOI_LEN)

#define WDT3_WDT_EOI_WDT_EOI_W(value) SetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_WDT_EOI_POS, WDT_WDT_EOI_WDT_EOI_LEN,value)


/* RSVD_WDT_EOI */

#ifndef WDT_WDT_EOI_RSVD_WDT_EOI_POS
#define WDT_WDT_EOI_RSVD_WDT_EOI_POS      1
#endif

#ifndef WDT_WDT_EOI_RSVD_WDT_EOI_LEN
#define WDT_WDT_EOI_RSVD_WDT_EOI_LEN      31
#endif

#if defined(_V1) && !defined(WDT_EOI_RSVD_WDT_EOI_R)
#define WDT_EOI_RSVD_WDT_EOI_R        GetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_RSVD_WDT_EOI_POS, WDT_WDT_EOI_RSVD_WDT_EOI_LEN)
#endif

#if defined(_V1) && !defined(WDT_EOI_RSVD_WDT_EOI_W)
#define WDT_EOI_RSVD_WDT_EOI_W(value) SetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_RSVD_WDT_EOI_POS, WDT_WDT_EOI_RSVD_WDT_EOI_LEN,value)
#endif

#define WDT3_WDT_EOI_RSVD_WDT_EOI_R        GetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_RSVD_WDT_EOI_POS, WDT_WDT_EOI_RSVD_WDT_EOI_LEN)

#define WDT3_WDT_EOI_RSVD_WDT_EOI_W(value) SetGroupBits32( (WDT3_WDT_EOI_VAL),WDT_WDT_EOI_RSVD_WDT_EOI_POS, WDT_WDT_EOI_RSVD_WDT_EOI_LEN,value)


/* REGISTER: WDT_TORR */

#if defined(_V1) && !defined(WDT_TORR_OFFSET)
#define WDT_TORR_OFFSET 0x4
#endif

#if !defined(WDT_WDT_TORR_OFFSET)
#define WDT_WDT_TORR_OFFSET 0x4
#endif

#if defined(_V1) && !defined(WDT_TORR_REG)
#define WDT_TORR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_TORR_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_TORR_VAL)
#define WDT_TORR_VAL  PREFIX_VAL(WDT_TORR_REG)
#endif

#define WDT3_WDT_TORR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_TORR_OFFSET))
#define WDT3_WDT_TORR_VAL  PREFIX_VAL(WDT3_WDT_TORR_REG)

/* FIELDS: */

/* TOP */

#ifndef WDT_WDT_TORR_TOP_POS
#define WDT_WDT_TORR_TOP_POS      0
#endif

#ifndef WDT_WDT_TORR_TOP_LEN
#define WDT_WDT_TORR_TOP_LEN      4
#endif

#if defined(_V1) && !defined(WDT_TORR_TOP_R)
#define WDT_TORR_TOP_R        GetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_POS, WDT_WDT_TORR_TOP_LEN)
#endif

#if defined(_V1) && !defined(WDT_TORR_TOP_W)
#define WDT_TORR_TOP_W(value) SetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_POS, WDT_WDT_TORR_TOP_LEN,value)
#endif

#define WDT3_WDT_TORR_TOP_R        GetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_POS, WDT_WDT_TORR_TOP_LEN)

#define WDT3_WDT_TORR_TOP_W(value) SetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_POS, WDT_WDT_TORR_TOP_LEN,value)


/* TOP_INIT */

#ifndef WDT_WDT_TORR_TOP_INIT_POS
#define WDT_WDT_TORR_TOP_INIT_POS      4
#endif

#ifndef WDT_WDT_TORR_TOP_INIT_LEN
#define WDT_WDT_TORR_TOP_INIT_LEN      4
#endif

#if defined(_V1) && !defined(WDT_TORR_TOP_INIT_R)
#define WDT_TORR_TOP_INIT_R        GetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_INIT_POS, WDT_WDT_TORR_TOP_INIT_LEN)
#endif

#if defined(_V1) && !defined(WDT_TORR_TOP_INIT_W)
#define WDT_TORR_TOP_INIT_W(value) SetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_INIT_POS, WDT_WDT_TORR_TOP_INIT_LEN,value)
#endif

#define WDT3_WDT_TORR_TOP_INIT_R        GetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_INIT_POS, WDT_WDT_TORR_TOP_INIT_LEN)

#define WDT3_WDT_TORR_TOP_INIT_W(value) SetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_TOP_INIT_POS, WDT_WDT_TORR_TOP_INIT_LEN,value)


/* Reserved */

#ifndef WDT_WDT_TORR_RESERVED_POS
#define WDT_WDT_TORR_RESERVED_POS      8
#endif

#ifndef WDT_WDT_TORR_RESERVED_LEN
#define WDT_WDT_TORR_RESERVED_LEN      24
#endif

#if defined(_V1) && !defined(WDT_TORR_RESERVED_R)
#define WDT_TORR_RESERVED_R        GetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_RESERVED_POS, WDT_WDT_TORR_RESERVED_LEN)
#endif

#if defined(_V1) && !defined(WDT_TORR_RESERVED_W)
#define WDT_TORR_RESERVED_W(value) SetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_RESERVED_POS, WDT_WDT_TORR_RESERVED_LEN,value)
#endif

#define WDT3_WDT_TORR_RESERVED_R        GetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_RESERVED_POS, WDT_WDT_TORR_RESERVED_LEN)

#define WDT3_WDT_TORR_RESERVED_W(value) SetGroupBits32( (WDT3_WDT_TORR_VAL),WDT_WDT_TORR_RESERVED_POS, WDT_WDT_TORR_RESERVED_LEN,value)


/* REGISTER: WDT_CCVR */

#if defined(_V1) && !defined(WDT_CCVR_OFFSET)
#define WDT_CCVR_OFFSET 0x8
#endif

#if !defined(WDT_WDT_CCVR_OFFSET)
#define WDT_WDT_CCVR_OFFSET 0x8
#endif

#if defined(_V1) && !defined(WDT_CCVR_REG)
#define WDT_CCVR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_CCVR_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_CCVR_VAL)
#define WDT_CCVR_VAL  PREFIX_VAL(WDT_CCVR_REG)
#endif

#define WDT3_WDT_CCVR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_CCVR_OFFSET))
#define WDT3_WDT_CCVR_VAL  PREFIX_VAL(WDT3_WDT_CCVR_REG)

/* FIELDS: */

/* wdt_ccvr */

#ifndef WDT_WDT_CCVR_WDT_CCVR_POS
#define WDT_WDT_CCVR_WDT_CCVR_POS      0
#endif

#ifndef WDT_WDT_CCVR_WDT_CCVR_LEN
#define WDT_WDT_CCVR_WDT_CCVR_LEN      32
#endif

#if defined(_V1) && !defined(WDT_CCVR_WDT_CCVR_R)
#define WDT_CCVR_WDT_CCVR_R        GetGroupBits32( (WDT3_WDT_CCVR_VAL),WDT_WDT_CCVR_WDT_CCVR_POS, WDT_WDT_CCVR_WDT_CCVR_LEN)
#endif

#if defined(_V1) && !defined(WDT_CCVR_WDT_CCVR_W)
#define WDT_CCVR_WDT_CCVR_W(value) SetGroupBits32( (WDT3_WDT_CCVR_VAL),WDT_WDT_CCVR_WDT_CCVR_POS, WDT_WDT_CCVR_WDT_CCVR_LEN,value)
#endif

#define WDT3_WDT_CCVR_WDT_CCVR_R        GetGroupBits32( (WDT3_WDT_CCVR_VAL),WDT_WDT_CCVR_WDT_CCVR_POS, WDT_WDT_CCVR_WDT_CCVR_LEN)

#define WDT3_WDT_CCVR_WDT_CCVR_W(value) SetGroupBits32( (WDT3_WDT_CCVR_VAL),WDT_WDT_CCVR_WDT_CCVR_POS, WDT_WDT_CCVR_WDT_CCVR_LEN,value)


/* REGISTER: WDT_CRR */

#if defined(_V1) && !defined(WDT_CRR_OFFSET)
#define WDT_CRR_OFFSET 0xc
#endif

#if !defined(WDT_WDT_CRR_OFFSET)
#define WDT_WDT_CRR_OFFSET 0xc
#endif

#if defined(_V1) && !defined(WDT_CRR_REG)
#define WDT_CRR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_CRR_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_CRR_VAL)
#define WDT_CRR_VAL  PREFIX_VAL(WDT_CRR_REG)
#endif

#define WDT3_WDT_CRR_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_CRR_OFFSET))
#define WDT3_WDT_CRR_VAL  PREFIX_VAL(WDT3_WDT_CRR_REG)

/* FIELDS: */

/* wdt_crr */

#ifndef WDT_WDT_CRR_WDT_CRR_POS
#define WDT_WDT_CRR_WDT_CRR_POS      0
#endif

#ifndef WDT_WDT_CRR_WDT_CRR_LEN
#define WDT_WDT_CRR_WDT_CRR_LEN      8
#endif

#if defined(_V1) && !defined(WDT_CRR_WDT_CRR_R)
#define WDT_CRR_WDT_CRR_R        GetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_WDT_CRR_POS, WDT_WDT_CRR_WDT_CRR_LEN)
#endif

#if defined(_V1) && !defined(WDT_CRR_WDT_CRR_W)
#define WDT_CRR_WDT_CRR_W(value) SetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_WDT_CRR_POS, WDT_WDT_CRR_WDT_CRR_LEN,value)
#endif

#define WDT3_WDT_CRR_WDT_CRR_R        GetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_WDT_CRR_POS, WDT_WDT_CRR_WDT_CRR_LEN)

#define WDT3_WDT_CRR_WDT_CRR_W(value) SetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_WDT_CRR_POS, WDT_WDT_CRR_WDT_CRR_LEN,value)


/* RSVD_WDT_CRR */

#ifndef WDT_WDT_CRR_RSVD_WDT_CRR_POS
#define WDT_WDT_CRR_RSVD_WDT_CRR_POS      8
#endif

#ifndef WDT_WDT_CRR_RSVD_WDT_CRR_LEN
#define WDT_WDT_CRR_RSVD_WDT_CRR_LEN      24
#endif

#if defined(_V1) && !defined(WDT_CRR_RSVD_WDT_CRR_R)
#define WDT_CRR_RSVD_WDT_CRR_R        GetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_RSVD_WDT_CRR_POS, WDT_WDT_CRR_RSVD_WDT_CRR_LEN)
#endif

#if defined(_V1) && !defined(WDT_CRR_RSVD_WDT_CRR_W)
#define WDT_CRR_RSVD_WDT_CRR_W(value) SetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_RSVD_WDT_CRR_POS, WDT_WDT_CRR_RSVD_WDT_CRR_LEN,value)
#endif

#define WDT3_WDT_CRR_RSVD_WDT_CRR_R        GetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_RSVD_WDT_CRR_POS, WDT_WDT_CRR_RSVD_WDT_CRR_LEN)

#define WDT3_WDT_CRR_RSVD_WDT_CRR_W(value) SetGroupBits32( (WDT3_WDT_CRR_VAL),WDT_WDT_CRR_RSVD_WDT_CRR_POS, WDT_WDT_CRR_RSVD_WDT_CRR_LEN,value)


/* REGISTER: WDT_COMP_PARAM_5 */

#if defined(_V1) && !defined(WDT_COMP_PARAM_5_OFFSET)
#define WDT_COMP_PARAM_5_OFFSET 0xe4
#endif

#if !defined(WDT_WDT_COMP_PARAM_5_OFFSET)
#define WDT_WDT_COMP_PARAM_5_OFFSET 0xe4
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_5_REG)
#define WDT_COMP_PARAM_5_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_5_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_5_VAL)
#define WDT_COMP_PARAM_5_VAL  PREFIX_VAL(WDT_COMP_PARAM_5_REG)
#endif

#define WDT3_WDT_COMP_PARAM_5_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_5_OFFSET))
#define WDT3_WDT_COMP_PARAM_5_VAL  PREFIX_VAL(WDT3_WDT_COMP_PARAM_5_REG)

/* FIELDS: */

/* WDT_CPARAM5_FLD */

#ifndef WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_POS
#define WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_POS      0
#endif

#ifndef WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_LEN
#define WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_LEN      32
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_R)
#define WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_5_VAL),WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_POS, WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_W)
#define WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_5_VAL),WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_POS, WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_5_VAL),WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_POS, WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_LEN)

#define WDT3_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_5_VAL),WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_POS, WDT_WDT_COMP_PARAM_5_WDT_CPARAM5_FLD_LEN,value)


/* REGISTER: WDT_COMP_PARAM_4 */

#if defined(_V1) && !defined(WDT_COMP_PARAM_4_OFFSET)
#define WDT_COMP_PARAM_4_OFFSET 0xe8
#endif

#if !defined(WDT_WDT_COMP_PARAM_4_OFFSET)
#define WDT_WDT_COMP_PARAM_4_OFFSET 0xe8
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_4_REG)
#define WDT_COMP_PARAM_4_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_4_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_4_VAL)
#define WDT_COMP_PARAM_4_VAL  PREFIX_VAL(WDT_COMP_PARAM_4_REG)
#endif

#define WDT3_WDT_COMP_PARAM_4_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_4_OFFSET))
#define WDT3_WDT_COMP_PARAM_4_VAL  PREFIX_VAL(WDT3_WDT_COMP_PARAM_4_REG)

/* FIELDS: */

/* WDT_CPARAM4_FLD */

#ifndef WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_POS
#define WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_POS      0
#endif

#ifndef WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_LEN
#define WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_LEN      32
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_R)
#define WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_4_VAL),WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_POS, WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_W)
#define WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_4_VAL),WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_POS, WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_4_VAL),WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_POS, WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_LEN)

#define WDT3_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_4_VAL),WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_POS, WDT_WDT_COMP_PARAM_4_WDT_CPARAM4_FLD_LEN,value)


/* REGISTER: WDT_COMP_PARAM_3 */

#if defined(_V1) && !defined(WDT_COMP_PARAM_3_OFFSET)
#define WDT_COMP_PARAM_3_OFFSET 0xec
#endif

#if !defined(WDT_WDT_COMP_PARAM_3_OFFSET)
#define WDT_WDT_COMP_PARAM_3_OFFSET 0xec
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_3_REG)
#define WDT_COMP_PARAM_3_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_3_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_3_VAL)
#define WDT_COMP_PARAM_3_VAL  PREFIX_VAL(WDT_COMP_PARAM_3_REG)
#endif

#define WDT3_WDT_COMP_PARAM_3_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_3_OFFSET))
#define WDT3_WDT_COMP_PARAM_3_VAL  PREFIX_VAL(WDT3_WDT_COMP_PARAM_3_REG)

/* FIELDS: */

/* WDT_CPARAM3_FLD */

#ifndef WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_POS
#define WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_POS      0
#endif

#ifndef WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_LEN
#define WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_LEN      32
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_R)
#define WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_3_VAL),WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_POS, WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_W)
#define WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_3_VAL),WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_POS, WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_3_VAL),WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_POS, WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_LEN)

#define WDT3_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_3_VAL),WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_POS, WDT_WDT_COMP_PARAM_3_WDT_CPARAM3_FLD_LEN,value)


/* REGISTER: WDT_COMP_PARAM_2 */

#if defined(_V1) && !defined(WDT_COMP_PARAM_2_OFFSET)
#define WDT_COMP_PARAM_2_OFFSET 0xf0
#endif

#if !defined(WDT_WDT_COMP_PARAM_2_OFFSET)
#define WDT_WDT_COMP_PARAM_2_OFFSET 0xf0
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_2_REG)
#define WDT_COMP_PARAM_2_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_2_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_2_VAL)
#define WDT_COMP_PARAM_2_VAL  PREFIX_VAL(WDT_COMP_PARAM_2_REG)
#endif

#define WDT3_WDT_COMP_PARAM_2_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_2_OFFSET))
#define WDT3_WDT_COMP_PARAM_2_VAL  PREFIX_VAL(WDT3_WDT_COMP_PARAM_2_REG)

/* FIELDS: */

/* WDT_CPARAM2_FLD */

#ifndef WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_POS
#define WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_POS      0
#endif

#ifndef WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_LEN
#define WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_LEN      32
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_R)
#define WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_2_VAL),WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_POS, WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_W)
#define WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_2_VAL),WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_POS, WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_2_VAL),WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_POS, WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_LEN)

#define WDT3_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_2_VAL),WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_POS, WDT_WDT_COMP_PARAM_2_WDT_CPARAM2_FLD_LEN,value)


/* REGISTER: WDT_COMP_PARAM_1 */

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_OFFSET)
#define WDT_COMP_PARAM_1_OFFSET 0xf4
#endif

#if !defined(WDT_WDT_COMP_PARAM_1_OFFSET)
#define WDT_WDT_COMP_PARAM_1_OFFSET 0xf4
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_REG)
#define WDT_COMP_PARAM_1_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_1_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_VAL)
#define WDT_COMP_PARAM_1_VAL  PREFIX_VAL(WDT_COMP_PARAM_1_REG)
#endif

#define WDT3_WDT_COMP_PARAM_1_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_PARAM_1_OFFSET))
#define WDT3_WDT_COMP_PARAM_1_VAL  PREFIX_VAL(WDT3_WDT_COMP_PARAM_1_REG)

/* FIELDS: */

/* WDT_ALWAYS_EN */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_POS
#define WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_POS      0
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_ALWAYS_EN_R)
#define WDT_COMP_PARAM_1_WDT_ALWAYS_EN_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_POS, WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_ALWAYS_EN_W)
#define WDT_COMP_PARAM_1_WDT_ALWAYS_EN_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_POS, WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_POS, WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_POS, WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_LEN,value)


/* WDT_DFLT_RMOD */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_POS
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_POS      1
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_RMOD_R)
#define WDT_COMP_PARAM_1_WDT_DFLT_RMOD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_RMOD_W)
#define WDT_COMP_PARAM_1_WDT_DFLT_RMOD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_LEN,value)


/* WDT_DUAL_TOP */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_POS
#define WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_POS      2
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DUAL_TOP_R)
#define WDT_COMP_PARAM_1_WDT_DUAL_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DUAL_TOP_W)
#define WDT_COMP_PARAM_1_WDT_DUAL_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_DUAL_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_DUAL_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_LEN,value)


/* WDT_HC_RMOD */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_POS
#define WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_POS      3
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_HC_RMOD_R)
#define WDT_COMP_PARAM_1_WDT_HC_RMOD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_HC_RMOD_W)
#define WDT_COMP_PARAM_1_WDT_HC_RMOD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_HC_RMOD_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_HC_RMOD_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_LEN,value)


/* WDT_HC_RPL */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_POS
#define WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_POS      4
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_HC_RPL_R)
#define WDT_COMP_PARAM_1_WDT_HC_RPL_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_HC_RPL_W)
#define WDT_COMP_PARAM_1_WDT_HC_RPL_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_HC_RPL_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_HC_RPL_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_LEN,value)


/* WDT_HC_TOP */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_POS
#define WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_POS      5
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_HC_TOP_R)
#define WDT_COMP_PARAM_1_WDT_HC_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_HC_TOP_W)
#define WDT_COMP_PARAM_1_WDT_HC_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_HC_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_HC_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_LEN,value)


/* WDT_USE_FIX_TOP */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_POS
#define WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_POS      6
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_R)
#define WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_W)
#define WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_LEN,value)


/* WDT_PAUSE */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_PAUSE_POS
#define WDT_WDT_COMP_PARAM_1_WDT_PAUSE_POS      7
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_PAUSE_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_PAUSE_LEN      1
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_PAUSE_R)
#define WDT_COMP_PARAM_1_WDT_PAUSE_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_PAUSE_POS, WDT_WDT_COMP_PARAM_1_WDT_PAUSE_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_PAUSE_W)
#define WDT_COMP_PARAM_1_WDT_PAUSE_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_PAUSE_POS, WDT_WDT_COMP_PARAM_1_WDT_PAUSE_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_PAUSE_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_PAUSE_POS, WDT_WDT_COMP_PARAM_1_WDT_PAUSE_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_PAUSE_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_PAUSE_POS, WDT_WDT_COMP_PARAM_1_WDT_PAUSE_LEN,value)


/* APB_DATA_WIDTH */

#ifndef WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_POS
#define WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_POS      8
#endif

#ifndef WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_LEN
#define WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_LEN      2
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_APB_DATA_WIDTH_R)
#define WDT_COMP_PARAM_1_APB_DATA_WIDTH_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_POS, WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_APB_DATA_WIDTH_W)
#define WDT_COMP_PARAM_1_APB_DATA_WIDTH_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_POS, WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_APB_DATA_WIDTH_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_POS, WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_LEN)

#define WDT3_WDT_COMP_PARAM_1_APB_DATA_WIDTH_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_POS, WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_LEN,value)


/* WDT_DFLT_RPL */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_POS
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_POS      10
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_LEN      3
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_RPL_R)
#define WDT_COMP_PARAM_1_WDT_DFLT_RPL_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_RPL_W)
#define WDT_COMP_PARAM_1_WDT_DFLT_RPL_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_RPL_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_RPL_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_LEN,value)


/* RSVD_15_13 */

#ifndef WDT_WDT_COMP_PARAM_1_RSVD_15_13_POS
#define WDT_WDT_COMP_PARAM_1_RSVD_15_13_POS      13
#endif

#ifndef WDT_WDT_COMP_PARAM_1_RSVD_15_13_LEN
#define WDT_WDT_COMP_PARAM_1_RSVD_15_13_LEN      3
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_RSVD_15_13_R)
#define WDT_COMP_PARAM_1_RSVD_15_13_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_15_13_POS, WDT_WDT_COMP_PARAM_1_RSVD_15_13_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_RSVD_15_13_W)
#define WDT_COMP_PARAM_1_RSVD_15_13_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_15_13_POS, WDT_WDT_COMP_PARAM_1_RSVD_15_13_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_RSVD_15_13_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_15_13_POS, WDT_WDT_COMP_PARAM_1_RSVD_15_13_LEN)

#define WDT3_WDT_COMP_PARAM_1_RSVD_15_13_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_15_13_POS, WDT_WDT_COMP_PARAM_1_RSVD_15_13_LEN,value)


/* WDT_DFLT_TOP */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_POS
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_POS      16
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_LEN      4
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_TOP_R)
#define WDT_COMP_PARAM_1_WDT_DFLT_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_TOP_W)
#define WDT_COMP_PARAM_1_WDT_DFLT_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_TOP_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_TOP_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_LEN,value)


/* WDT_DFLT_TOP_INIT */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_POS
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_POS      20
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_LEN      4
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_R)
#define WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_W)
#define WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_POS, WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_LEN,value)


/* WDT_CNT_WIDTH */

#ifndef WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_POS
#define WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_POS      24
#endif

#ifndef WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_LEN
#define WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_LEN      5
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_CNT_WIDTH_R)
#define WDT_COMP_PARAM_1_WDT_CNT_WIDTH_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_POS, WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_WDT_CNT_WIDTH_W)
#define WDT_COMP_PARAM_1_WDT_CNT_WIDTH_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_POS, WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_POS, WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_LEN)

#define WDT3_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_POS, WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_LEN,value)


/* RSVD_31_29 */

#ifndef WDT_WDT_COMP_PARAM_1_RSVD_31_29_POS
#define WDT_WDT_COMP_PARAM_1_RSVD_31_29_POS      29
#endif

#ifndef WDT_WDT_COMP_PARAM_1_RSVD_31_29_LEN
#define WDT_WDT_COMP_PARAM_1_RSVD_31_29_LEN      3
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_RSVD_31_29_R)
#define WDT_COMP_PARAM_1_RSVD_31_29_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_31_29_POS, WDT_WDT_COMP_PARAM_1_RSVD_31_29_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_PARAM_1_RSVD_31_29_W)
#define WDT_COMP_PARAM_1_RSVD_31_29_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_31_29_POS, WDT_WDT_COMP_PARAM_1_RSVD_31_29_LEN,value)
#endif

#define WDT3_WDT_COMP_PARAM_1_RSVD_31_29_R        GetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_31_29_POS, WDT_WDT_COMP_PARAM_1_RSVD_31_29_LEN)

#define WDT3_WDT_COMP_PARAM_1_RSVD_31_29_W(value) SetGroupBits32( (WDT3_WDT_COMP_PARAM_1_VAL),WDT_WDT_COMP_PARAM_1_RSVD_31_29_POS, WDT_WDT_COMP_PARAM_1_RSVD_31_29_LEN,value)


/* REGISTER: WDT_COMP_VERSION */

#if defined(_V1) && !defined(WDT_COMP_VERSION_OFFSET)
#define WDT_COMP_VERSION_OFFSET 0xf8
#endif

#if !defined(WDT_WDT_COMP_VERSION_OFFSET)
#define WDT_WDT_COMP_VERSION_OFFSET 0xf8
#endif

#if defined(_V1) && !defined(WDT_COMP_VERSION_REG)
#define WDT_COMP_VERSION_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_VERSION_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_COMP_VERSION_VAL)
#define WDT_COMP_VERSION_VAL  PREFIX_VAL(WDT_COMP_VERSION_REG)
#endif

#define WDT3_WDT_COMP_VERSION_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_VERSION_OFFSET))
#define WDT3_WDT_COMP_VERSION_VAL  PREFIX_VAL(WDT3_WDT_COMP_VERSION_REG)

/* FIELDS: */

/* wdt_comp_version */

#ifndef WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_POS
#define WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_POS      0
#endif

#ifndef WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_LEN
#define WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_LEN      32
#endif

#if defined(_V1) && !defined(WDT_COMP_VERSION_WDT_COMP_VERSION_R)
#define WDT_COMP_VERSION_WDT_COMP_VERSION_R        GetGroupBits32( (WDT3_WDT_COMP_VERSION_VAL),WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_POS, WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_VERSION_WDT_COMP_VERSION_W)
#define WDT_COMP_VERSION_WDT_COMP_VERSION_W(value) SetGroupBits32( (WDT3_WDT_COMP_VERSION_VAL),WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_POS, WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_LEN,value)
#endif

#define WDT3_WDT_COMP_VERSION_WDT_COMP_VERSION_R        GetGroupBits32( (WDT3_WDT_COMP_VERSION_VAL),WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_POS, WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_LEN)

#define WDT3_WDT_COMP_VERSION_WDT_COMP_VERSION_W(value) SetGroupBits32( (WDT3_WDT_COMP_VERSION_VAL),WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_POS, WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_LEN,value)


/* REGISTER: WDT_COMP_TYPE */

#if defined(_V1) && !defined(WDT_COMP_TYPE_OFFSET)
#define WDT_COMP_TYPE_OFFSET 0xfc
#endif

#if !defined(WDT_WDT_COMP_TYPE_OFFSET)
#define WDT_WDT_COMP_TYPE_OFFSET 0xfc
#endif

#if defined(_V1) && !defined(WDT_COMP_TYPE_REG)
#define WDT_COMP_TYPE_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_TYPE_OFFSET))
#endif

#if defined(_V1) && !defined(WDT_COMP_TYPE_VAL)
#define WDT_COMP_TYPE_VAL  PREFIX_VAL(WDT_COMP_TYPE_REG)
#endif

#define WDT3_WDT_COMP_TYPE_REG ((volatile UINT32 *) (WDT3_BASE + WDT_WDT_COMP_TYPE_OFFSET))
#define WDT3_WDT_COMP_TYPE_VAL  PREFIX_VAL(WDT3_WDT_COMP_TYPE_REG)

/* FIELDS: */

/* wdt_comp_type */

#ifndef WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_POS
#define WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_POS      0
#endif

#ifndef WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_LEN
#define WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_LEN      32
#endif

#if defined(_V1) && !defined(WDT_COMP_TYPE_WDT_COMP_TYPE_R)
#define WDT_COMP_TYPE_WDT_COMP_TYPE_R        GetGroupBits32( (WDT3_WDT_COMP_TYPE_VAL),WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_POS, WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_LEN)
#endif

#if defined(_V1) && !defined(WDT_COMP_TYPE_WDT_COMP_TYPE_W)
#define WDT_COMP_TYPE_WDT_COMP_TYPE_W(value) SetGroupBits32( (WDT3_WDT_COMP_TYPE_VAL),WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_POS, WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_LEN,value)
#endif

#define WDT3_WDT_COMP_TYPE_WDT_COMP_TYPE_R        GetGroupBits32( (WDT3_WDT_COMP_TYPE_VAL),WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_POS, WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_LEN)

#define WDT3_WDT_COMP_TYPE_WDT_COMP_TYPE_W(value) SetGroupBits32( (WDT3_WDT_COMP_TYPE_VAL),WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_POS, WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_LEN,value)


/* OFFSET TABLE: */
#define wdt3_offset_tbl_values	WDT_CR_OFFSET, WDT_STAT_OFFSET, WDT_EOI_OFFSET, WDT_TORR_OFFSET, WDT_CCVR_OFFSET, WDT_CRR_OFFSET, WDT_COMP_PARAM_5_OFFSET, WDT_COMP_PARAM_4_OFFSET, WDT_COMP_PARAM_3_OFFSET, WDT_COMP_PARAM_2_OFFSET, WDT_COMP_PARAM_1_OFFSET, WDT_COMP_VERSION_OFFSET, WDT_COMP_TYPE_OFFSET


/* REGISTERS RESET VAL: */
#define wdt3_regs_reset_val	0x10, 0x0, 0x0, 0xFF, 0x7FFFFFFF, 0x0, 0x0, 0x0, 0xFF, 0x7FFFFFFF, 0x10FF1244, 0x3130392A, 0x44570120

#endif

/* End of WDT3 */
/* ///////////////////////////////////////////////////////////////////////*/
